### ISSUE TITLE
web-ext lint

### ISSUE THREAD

**Issue by epistemex** [mozilla/web-ext#1020]
### Is this a feature request or a bug?
bug

### What is the current behavior?

The linter will report error if the manifest contains links to f.ex. graphics resources using forward-slash (on Windows) "gfx/icon_48.png". 

> MANIFEST_ICON_NOT_FOUND   An icon defined in the manifest could not be   Icon could not be found at "gfx/icon_48.png".   manifest.json

If I change this to backward-slash "gfx\\\\icon_48.png" (double backward-slash due to JS special-char) it will pass, however, now I will get an error from the signing process saying:

> "Your add-on failed validation and could not be signed FAIL"

Signing will work when there are forward-slashes.

### What is the expected or desired behavior?

Linting should work with forward slash in paths.

### Version information (for bug reports)

2.0.0

* **Firefox version**: Not relevant
* **Your OS and version**: Windows 8.1
* Paste the output of these commands:

````
node --version && npm --version && web-ext --version
````
v6.10.3
3.10.10
2.0.0

**Comment by kumar303** [comment]
Hi, thanks for filing a bug and sorry about the inconvenience. This is a bug in `addons-linter` tracked here already: https://github.com/mozilla/addons-linter/issues/1431
