### ISSUE TITLE
Using environmental values

### ISSUE THREAD

**Issue by epistemex** [mozilla/web-ext#1021]
### Is this a feature request or a bug?

Bug

### What is the current behavior?

Setting environmental values (Powershell, Windows) works when signing. The vars are read and processed as expected.

The problem is they are *also read* and fed as arguments for other commands, for example, running:

    web-ext lint

or

    web-ext docs

etc., will produce:

    [help menu] +
    Unknown arguments: apiKey, apiSecret

asNeeded ($WEB_EXT_AS_NEEDED=true) will also be added if set (but not $WEB_EXT_SELF_HOSTED).

### What is the expected or desired behavior?

Env vars for signing etc. to be ignored when not signing or used for option combination they are not relevant to.

### Version information (for bug reports)

2.0.0

* **Firefox version**: not relevant (54-55b)
* **Your OS and version**: Windows 8.1
* Paste the output of these commands:

````
node --version && npm --version && web-ext --version
````
v.6.10.3
3.10.10
2.0.0

**Comment by kumar303** [comment]
Hi. Sorry about that. This is a known issue tracked in https://github.com/mozilla/web-ext/issues/793
