### ISSUE TITLE
How to get URL of loaded folder?

### ISSUE THREAD

**Issue by saulshanabrook** [mozilla/web-ext#1043]
### Is this a feature request or a bug?

Feature request

### What is the current behavior?
When I run `web-ext build` and then load that folder into a Firefox browser with `xpinstall.signatures.required` set to `False` it is accessible at some URL `moz-extension://<uuid>`. The `uuid` is, as far as I can tell, randomly generated anew for each profile.

### What is the expected or desired behavior?

I want to be able to make this `uuid` consistent. I am running selenium tests against my extension and need to have a way of getting it's URL so that I can navigate to it.

I am using the `selenium-webdriver` package to create a Firefox profile and add an extension:

```javascript
const firefox = require('selenium-webdriver/firefox');

var profile = new firefox.Profile();
profile.addExtension('/dist/dist/');
profile.setPreference('xpinstall.signatures.required', false);
```

It looks like, [from this issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1271663), that there might be a way to make the ID constant currently, but I cannot figure out how. In my `manifest.json` I am setting the ID like this:

```json
{
  "applications": {
    "gecko": {
      "id": "passit@passit.io",
```

But that is not used in the URL to access the extension.

### Version information (for bug reports)

* **Firefox version**: 56.0b2
* **Your OS and version**: Ubuntu 16.04
* Paste the output of these commands:

````bash
$ node --version && npm --version && web-ext --version
v6.11.1

3.10.10
1.10.1
````

Using Firefox from Docker image `registry.gitlab.com/passit/docker-selenium` built from [this repo](https://gitlab.com/passit/docker-selenium).

**Comment by kumar303** [comment]
Hi. Thanks for taking the time to file an issue. Yes, `uuid` is randomly generated for each new Firefox session. There's not much web-ext can do here (that I can think of). Thus, I can't really think of a reason to keep this issue open.

Can you trigger [`extension.getURL()`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/extension/getURL) from Selenium? Aside from that, you could try connecting directly to the remote debugger to get the uuid (I'm not sure if it will give you the uuid though). Example: https://github.com/mozilla/web-ext/blob/master/src/firefox/remote.js#L129
