### ISSUE TITLE
`web-ext lint` incorrectly calls `tabs.print` and `tabs.printPreview` unsupported

### ISSUE THREAD

**Issue by ExE-Boss** [mozilla/web-ext#1056]
### Is this a feature request or a bug?
bug

### What is the current behavior?
When running `web-ext lint` on a project that uses [`browser.tabs.print()`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/print) or [`browser.tabs.printPreview()`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/printPreview), `web-ext` claims that Firefox hasn’t yet implemented this feature, even though it is supported from Firefox 56+ ([bug 1269300](https://bugzilla.mozilla.org/show_bug.cgi?id=1269300)).

This happens even when [`applications.gecko.strict_min_version`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/applications) is set to `56` or above.

### What is the expected or desired behavior?
Since `browser.tabs.print()` and `browser.tabs.printPreview()` is supported since Firefox 56, `web-ext` shouldn’t complain about it being unsupported.

### Version information (for bug reports)
| Component	| Version	|
| -----	| -----	|
| Firefox	| 55.0.2	|
| OS	| Windows 10 Version 1607 (OS Build 14393.1593)	|
| `node --version`	| v7.8.0	|
| `npm --version`	| 4.2.0	|
| `web-ext --version`	| 2.0.0	|

### See also:
mozilla/addons-linter#1486

**Comment by kumar303** [comment]
Hi. Thanks for the detailed bug report. Could you re-file it in the linter's issue tracker? https://github.com/mozilla/addons-linter/issues

**Comment by ExE-Boss** [comment]
I have now filed this under mozilla/addons-linter#1486.

**Comment by kumar303** [comment]
Thanks!
