### ISSUE TITLE
Your tools write 'Error: Extension is invalid' How can i know what is invalid?

### ISSUE THREAD

**Issue by Dark-Energy** [mozilla/web-ext#1077]
Your tools write 'Error: Extension is invalid' How can i know what is invalid? 
May i where write incorrect comma, write something script is incorrect direction  in one of pages? What me doing?
Could shamanic drum help my in resolve this problem?

Стек-трейс: loadManifestFromWebManifest@resource://gre/modules/addons/XPIInstall.jsm:339:11

**Comment by kumar303** [comment]
Hi, thanks for filing an issue. I agree that this is not a helpful message. The error is thrown by Firefox, not by web-ext. It just gets logged to your console by web-ext.

Thus, there's not too much we can do here.

However, I would suggest running `web-ext lint` which should hopefully tell you what the error is. This will happen automatically after https://github.com/mozilla/web-ext/issues/384

**Comment by Rob--W** [comment]
From Firefox 139, errors will include more details beyond "Extension is invalid": https://bugzilla.mozilla.org/show_bug.cgi?id=1960285
