### ISSUE TITLE
The web-ext usage/help text doesn't reflect how arguments are actually parsed.

### ISSUE THREAD

**Issue by mortie** [mozilla/web-ext#1079]
### Is this a feature request or a bug?

Bug.

### What is the current behavior?

Running just `web-ext` shows this line at the beginning:

    Usage: web-ext [options] command

However, the tool only accepts commands written like `web-ext command [options]`.

### What is the expected or desired behavior?

Either the help message should say `Usage: web-ext command [options]`, or the argument parsing should be updated to support options which appear before the command.

### Version information (for bug reports)

* **Firefox version**: Mozilla Firefox 57.0a1 (That's the current Nightly build from https://aur.archlinux.org/packages/firefox-nightly/) (though this issue doesn't involve Firefox in any way, just web-ext)
* **Your OS and version**: Arch Linux, `Linux vor 4.12.12-1-ARCH #1 SMP PREEMPT Sun Sep 10 09:41:14 CEST 2017 x86_64 GNU/Linux`
* Paste the output of these commands:

````
node --version && npm --version && web-ext --version

v8.5.0
5.3.0
2.0.0
````

**Comment by kumar303** [comment]
Hi. Thanks for taking the time to file a bug.

> Usage: web-ext [options] command

This works fine. I just tried it:

```
web-ext -f nightly run
```
