### ISSUE TITLE
web-ext run to install a non-temporary add-on

### ISSUE THREAD

**Issue by budowski** [mozilla/web-ext#1084]
### Is this a feature request or a bug?
Feature request

### What is the current behavior?
Allow using `web-ext run` for use with add-ons that are not restartless - basically, installing the add-on under the same ID (i.e. a non temporary add-on), so the storage will persist between runs. Of course this means using an unbranded / development build of Firefox.

Currently, if your add-on requires storage (which is the case for most add-ons), this means the add-on starts from scratch every time you run `web-ext run`, which makes development process cumbersome.

**Comment by andymckay** [comment]
For storage, if you use the same profile each time and give you add-on an id in the manifest application > gecko > id, I think you'll find the data is preserved.

**Comment by andymckay** [comment]
See: https://github.com/mdn/webextensions-examples/tree/master/quicknote#running-with-web-ext and yes, this could be documented better somewhere.

**Comment by budowski** [comment]
@andymckay - you're right! Thank you :-)
I used the `--firefox-profile` and `--keep-profile-changes` options before, but didn't set the ID for the extension.
