### ISSUE TITLE
Support a project specific .webextignore

### ISSUE THREAD

**Issue by Croydon** [mozilla/web-ext#1091]
### Is this a feature request or a bug?
Feature request.

### What is the current behavior?
web-ext either packges all project files, even the unwanted ones or requires to specify every single time the ignored files via command parameter, which is stressful and complicated, and a complete chaos where there is more than one project contributor.

### What is the expected or desired behavior?
Add support for a project specific .webextignore file, which works like .jpmignore and .gitignore. That web-ext has no support for that is really wondering me, especially, since there was already a pull request for it: https://github.com/mozilla/web-ext/pull/703

@kumar303 What is with the suggestion you made here? https://github.com/mozilla/web-ext/pull/703#issuecomment-268882468

Maybe just rebasing this pull request and merging it finally?

**Comment by freaktechnik** [comment]
Seems like a dupe of #940

**Comment by Croydon** [comment]
Damn. I used the search but didn't see that. Thanks.
