### ISSUE TITLE
Submit a listed version to AMO

### ISSUE THREAD

**Issue by andymckay** [mozilla/web-ext#1096]
One of the most requested enhancements from the web-ext survey was the ability to submit a listed version of an add-on to AMO. Currently the sign command supports unlisted add-ons and returns the signed version to the user.

I believe there is a valid API for this on AMO, at least according to this bug: https://github.com/mozilla/addons-server/issues/5693

**Comment by sblask** [comment]
Chrome webstore doesn't have an API for this, does it? Otherwise, it would be amazing if an extension could be submitted there too...

**Comment by wagnerand** [comment]
Might be a dupe of https://github.com/mozilla/web-ext/issues/804.

**Comment by spoji** [comment]
> Chrome webstore doesn't have an API for this, does it? Otherwise, it would be amazing if an extension could be submitted there too...

I'm using https://github.com/c301/grunt-webstore-upload for CWS and it works great.

**Comment by andymckay** [comment]
Ah the title on #804 threw me off, yeah it sounds like a dupe. Thanks.

**Comment by kumar303** [comment]
Thanks @andymckay , I updated the title :)
