### ISSUE TITLE
Add option to delay auto-reload (support webpack better)

### ISSUE THREAD

**Issue by mi-g** [mozilla/web-ext#1102]
### Is this a feature request or a bug?

Feature request

See https://github.com/mozilla/web-ext/issues/1102#issuecomment-339143339

### What is the current behavior?

Right now, as soon as a file is modified in the extension directory, the reload is initiated.

This means that if you use a build system, like `webpack`, that takes a separate source code directory to generate the extension files into the target directory, as soon as the first file is modified in the target directory, the extension starts reloading, without the entire extension code being ready. So you have to force another reload with `CTRL+R` to get the correct extension files loaded.

### What is the expected or desired behavior?

We should have an option like `--reload-delay <seconds>` (or `<milliseconds>` maybe) to delay the reload after the watch system detects the last file change. This would allow the entire build to finish before the extension is reloaded.

**Comment by kumar303** [comment]
I see the problem but I don't think adding a delay would fix it. Well, it might fix it some of the time but probably not all of the time.

Is it possible for you to use [`web-ext run --ignore-files ...`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/web-ext_command_reference#--ignore-files_-i) so that only changes to your *built* files triggers the reload? In other words, if you ignore your source files then only changes to the built files should trigger a reload.

**Comment by mi-g** [comment]
Currently only the build directory is being monitored, not the source directory. The problem is that using a build system based on WebPack, when i change a file in the source directory, several files in the build directory are modified within a couple of seconds. Since `web-ext` reacts immediately when the first file is modified, it misses the other ones and i end up reloading the add-on with a `CTRL+R` in the `web-ext` console.

I agree using a timer is not the best solution. What about, an option like `--ignore-files-but <file>`, so that whenever my addon is rebuilt, i make sure `<file>` is the last file to be written to the build directory. Or maybe is it possible to do with the current `ignore-files` using some smart glob patterns ?

**Comment by mi-g** [comment]
Currently only the build directory is being monitored, not the source directory. The problem is that using a build system based on WebPack, when i change a file in the source directory, several files in the build directory are modified within a couple of seconds. Since `web-ext` reacts immediately when the first file is modified, it misses the other ones and i end up reloading the add-on with a `CTRL+R` in the `web-ext` console.

I agree using a timer is not the best solution. What about, an option like `--ignore-files-but <file>`, so that whenever my addon is rebuilt, i make sure `<file>` is the last file to be written to the build directory. Or maybe is it possible to do with the current `ignore-files` using some smart glob patterns ?

EDIT:

I decided to give it a try, but i failed using `--ignore-files` for excluding all files and directories, and i couldn't even try adding an exception.
Given my add-on browser-ready code is in `./addon/build`, shouldn't this script ignore all files and not auto-reload:
```
#!/bin/bash

PWD=$(pwd)
LOGFILE="$PWD/tmp/native-app.log"

WEH_NATIVE_LOGFILE=$LOGFILE web-ext run --source-dir addon/build \
	--ignore-files="addon/**/*" \
	--firefox-profile ./profile --firefox-binary ~/firefox-nightly/firefox \
	--keep-profile-changes --browser-console \
	--verbose
```

**Comment by notnarb** [comment]
> Since web-ext reacts immediately when the first file is modified, it misses the other ones and i end up reloading the add-on with a CTRL+R in the web-ext console.

I am also seeing this bug.  From what I can tell, there appears to be a gap in time where the file watcher's callback to reload the extension is not executing when it should.

I think the ideal solution (technology willing) is for web-ext's file watcher to not stop watching while a reload is occurring, scheduling another reload if a file change occurs *during* the reload. 

---

### Example

My specific case is I am writing an extension in typescript (using webpack as my bundler) and without an explicit ignore of the `.ts` files being written to, firefox will reload before the output `.js` files are written

#### Case: no `--ignore-files` (bug)
```sh
# Save TS File, extension reload triggers
Last extension reload: 17:47:04 GMT-0700 (PDT) # <web-ext-trigger>
# Webpack file creation triggers
[at-loader] Checking started in a separate process...

[at-loader] Ok, 0.37 sec.
Hash: cad53f982af0771be95a
Version: webpack 3.5.3
Time: 609ms
            Asset     Size  Chunks             Chunk Names
    background.js  32.1 kB       1  [emitted]  background
background.js.map  59.4 kB       1  [emitted]  background
 + 6 hidden assets
  [84] ./src/background.ts 8.9 kB {1} [built]
    + 197 hidden modules
# output js file is written, extension reload does not occur until *next* file write
```

#### Case: `--ignore-files='src/**/*.ts'` (my current working workaround)
```sh
# Saved TS file, webpack triggers, web-ext ignores change
[at-loader] Checking started in a separate process...

[at-loader] Ok, 0.348 sec.
Hash: e773927e8482b4c9071e
Version: webpack 3.5.3
Time: 564ms
            Asset     Size  Chunks             Chunk Names
    background.js  32.1 kB       1  [emitted]  background
background.js.map  59.4 kB       1  [emitted]  background
 + 6 hidden assets
  [84] ./src/background.ts 8.9 kB {1} [built]
    + 197 hidden modules
# Webpack writes JS files, extension reload occurs.
# If webpack wrote multiple js files in sequence, web-ext would likely miss them though 
Last extension reload: 17:52:59 GMT-0700 (PDT) # <web-ext-trigger>
```
---

With regards to the title of this issue: "Add option to delay auto-reload"

I think an argument could be made for a configurable 'debounce' time in addition to this (if I knew I would be writing N files (taking 10ms each) as the result of me updating a shared library, I may not want to trigger N extension reloads), but I think that's far from an immediate need.  I think web-ext not 'missing' any file updates is the more important issue to solve

**Comment by mi-g** [comment]
Ok, i get something that seems to work.

I use `--ignore-files="**/!(build.date)*"` and at the last step of my build process `fs.writeFileSync(buildDir+"/build.date",new Date())` so the reload only happens once all the files are ready.

@notnarb is it something you can do in your environment ?

**Comment by notnarb** [comment]
> @notnarb is it something you can do in your environment ?

I'm currently ignoring my typescript files so web-ext does not trigger a reload on the initial file save (this works so long as I am not emitting too many js files on a save).  I think your workaround is a clever way of getting around this issue for now, I'll give it a shot if I start emitting more files and run into this issue again

**Comment by kumar303** [comment]
Sorry, I was not able to catch up with this thread sooner.

Thanks for the extra info. I understand the problem now.

> I think the ideal solution (technology willing) is for web-ext's file watcher to not stop watching while a reload is occurring, scheduling another reload if a file change occurs during the reload.

This sounds like a pretty good solution. 

Another idea is to trigger web-ext's watch action on the trailing edge with more debouncing so that it keeps getting delayed until no more files are getting changed. 

This may not work all of the time and may not be desirable for everyone (in which case it could be a new option like `--watch-and-wait`).

**Comment by mi-g** [comment]
I haven't been able to figure out a situation where this behaviour (*not stop watching while a reload is occurring*) would not be desirable. Shouldn't it be the default instead ?

**Comment by kumar303** [comment]
> Shouldn't it be the default instead

I think it would be a fine solution to the problem. It could introduce a lot of extra reloads though. I was just saying it might be better to add a debounce so that web-ext waits and then reloads at the right time. Either approach should solve the problem at hand.
