### ISSUE TITLE
Current version of web-ext (2.2.0) on npm doesn't work

### ISSUE THREAD

**Issue by cr-nz** [mozilla/web-ext#1104]
I had managed to get my web-ext automatically building my extension in a shell script with this command:

```
#!/usr/bin/env bash
apiKey="user:123:123"
apiSecret="d4455"
web-ext sign -v --api-key="$apiKey" --api-secret="$apiSecret"
```

Then after it was built it recommended to do an upgrade from v2.0.0 to v2.2.0. I did that with npm. Now it no longer works anymore. All I get is this message:

```
[program.js][debug] Getting version from the git revision
```

Not even sure why git is needed!? It should be building based on the manifest file.

Here's the output of `node --version && npm --version && web-ext --version` which makes even less sense:

```
$ node --version && npm --version && web-ext --version
v6.2.1
3.9.3
Usage: web-ext [options] command

Option values can also be set by declaring an environment variable prefixed
with $WEB_EXT_. For example: $WEB_EXT_SOURCE_DIR=/path is the same as
--source-dir=/path.

To view specific help for any given command, add the command name.
Example: web-ext --help run.


Commands:
  build  Create an extension package from source
  sign   Sign the extension so it can be installed in Firefox
  run    Run the extension
  lint   Validate the extension source
  docs   Open the web-ext documentation in a browser

Options:
  --version            Show version number                             [boolean]
  --source-dir, -s     Web extension source directory.
                                                   [string] [required] [default:
                           "/home/c/Documents/deployment/webclient-updatebuild"]
  --artifacts-dir, -a  Directory where artifacts will be saved.
                                                   [string] [required] [default:
         "/home/c/Documents/deployment/webclient-updatebuild/web-ext-artifacts"]
  --verbose, -v        Show verbose output                  [boolean] [required]
  --ignore-files, -i   A list of glob patterns to define which files should be
                       ignored. (Example: --ignore-files=path/to/first.js
                       path/to/second.js "**/*.log")                     [array]
  --no-input           Disable all features that require standard input
                                                            [boolean] [required]
  -h, --help           Show help                                       [boolean]

[git-rev-sync] no git repository found
```

**Comment by mpopp75** [comment]
I get this after updating web-ext from 2.0.0 to 2.2.0 (via "sudo npm install --global web-ext") on my Xubuntu 16.04.3 64bit:

$ web-ext --version
SyntaxError: Unexpected token .
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/lib/node_modules/web-ext/node_modules/whatwg-url/lib/public-api.js:3:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

**Comment by kumar303** [comment]
Hi. Sorry about that. We had some bugs in the deploy script which of course took a couple deploys to fix 🌵 🔥 

You can update to `web-ext 2.2.2` which is now working. Let me know if you run into trouble.

Fixes:
* https://github.com/mozilla/web-ext/pull/1105
* https://github.com/mozilla/web-ext/commit/9e7e7a4ce848c459a1e42724145ae5b6194625ea

**Comment by mpopp75** [comment]
I still get the same error message with version 2.2.2.

**Comment by kumar303** [comment]
@mpopp75 which version of Node and npm do you have?

**Comment by mpopp75** [comment]
Node is version 4.4.3 and npm is version 3.10.5.

**Comment by cr-nz** [comment]
@kumar303 Version 2.2.2 is working fine for me now, many thanks!

**Comment by itseco** [comment]
I'm getting this error with node version 4.2.6 and web-ext version 2.4.0

**Comment by kumar303** [comment]
@itseco Node 6 is required [to install](https://github.com/mozilla/web-ext/#installation-from-npm) web-ext. This is the current [LTS](https://github.com/nodejs/Release) (long term support) version of Node so it should be easy to work with.

**Comment by itseco** [comment]
Thanks thats works
