### ISSUE TITLE
Firefox loads privacy info page

### ISSUE THREAD

**Issue by freaktechnik** [mozilla/web-ext#1114]
### Is this a feature request or a bug?
Not sure, I'd call it a bug.

### What is the current behavior?
When running Firefox using `web-ext run` it tries to load the privacy info page in a second tab. When working offline, loading this page can be really annoying (and it's annoying because of the extra logging that page produces, but that's a different topic). I also would rather not contribute to the google analytics statistics of that page just by testing my extension.

This is especially annoying due to a bug that nightly currently has, where the 60fps tab loading animation and e10s cause page loads to take forever, which seems to be extreme on my machine when I'm offline and it can't reach the remote resource in some cases (sometimes the network requests time out properly and it's no issue).

### What is the expected or desired behavior?
No remote pages are loaded when opening Firefox using `web-ext run` with a temporary profile.

### Version information (for bug reports)

* **Firefox version**: 58.0a1
* **Your OS and version**: elementary OS 0.3 Loki (based on Ubuntu LTS 16.04)
* Paste the output of these commands:

````
v8.7.0
v5.5.1
v2.2.2
````

**Comment by kumar303** [comment]
What is a privacy info page? Can you provide a URL? I'm sure it's something obvious, I just can't think of it.

**Comment by freaktechnik** [comment]
https://mozilla.org/privacy/firefox

**Comment by kumar303** [comment]
ok, maybe we just need to nullify [`toolkit.datacollection.infoURL`](https://dxr.mozilla.org/mozilla-central/source/browser/app/profile/firefox.js#990) or perhaps another one that controls loading it in the tab.

**Comment by rpl** [comment]
@kumar303 if I'm not wrong it should be `datareporting.policy.firstRunURL` (I guess that we can test it by using `web-ext run --pref='datareporting.policy.firstRunURL=""' ...`)

**Comment by freaktechnik** [comment]
@rpl while it does seem like the pref that seems to be the culprit, I can't seem to empty it using the --pref param.

**Comment by rpl** [comment]
@freaktechnik :+1: yeah, I just tried locally and I can confirm that `--pref='datareporting.policy.firstRunURL=""'` is setting the preference value to "\"\"" and the url is still loaded, while `--pref='datareporting.policy.firstRunURL='` successfully prevents the tab to be opened on the https://mozilla.org/privacy/firefox url.

Anyway, this confirm that it is the right preference to set, and so we can proceed to add it to the ones set by default in https://github.com/mozilla/web-ext/blob/bd02dc3127a40e8fd709e2b18293ae2704a3897b/src/firefox/preferences.js#L22 or https://github.com/mozilla/web-ext/blob/bd02dc3127a40e8fd709e2b18293ae2704a3897b/src/firefox/preferences.js#L68
