### ISSUE TITLE
Yarn/NPM lockfile shouldn't be bundled while building

### ISSUE THREAD

**Issue by Avinash-Bhat** [mozilla/web-ext#1136]
### Is this a feature request or a bug?
bug

### What is the current behavior?
1. run `web-ext` with lockfile (NPM/Yarn) in the project directory
2. observe the generated file using any archive manager

### What is the expected or desired behavior?
expected to not have the lock file

### Version information (for bug reports)
^2.2.2

* **Firefox version**:
N/A

* **Your OS and version**:
Windows 10

* Paste the output of these commands:
````
node --version && npm --version && web-ext --version
````
v8.9.0
5.5.1
2.2.2

---

### Additional Details
Actually there should be an ignore file where the user can specify what to include and what not to.
web-ext taking a known default can cause the ignoring logic to overflow with unnecessary files & would waste quite some time.

**Comment by kumar303** [comment]
Hi. Thanks for taking the time to file an issue. I updated https://github.com/mozilla/web-ext/issues/1109 to make sure we also ignore `yarn.lock`.
