### ISSUE TITLE
File watcher too eager for changes

### ISSUE THREAD

**Issue by freaktechnik** [mozilla/web-ext#1137]
### Is this a feature request or a bug?
This is a bug

### What is the current behavior?
- Compile files with webpack
- Launch web-ext run on the compiled sources
- web-ext loads initial extension
- web-ext detects "changes" and reloads the extension

Extension this happens with: https://github.com/freaktechnik/justintv-stream-notifications
Full log of webpack + verbose web-ext run: https://gist.github.com/freaktechnik/c129f478277d676e9d6f2e346f8eb9e2

### What is the expected or desired behavior?
There should be no change detected, since the files have not been touched since launching web-ext run.

### Version information (for bug reports)

* **Firefox version**: 59.0a1
* **Your OS and version**: elementary OS 0.3 (Ubuntu 16.04 derivative)
* Paste the output of these commands:

````
v9.0.0
5.5.1
1.10.1
````

**Comment by kumar303** [comment]
Thanks for the verbose log.

This suggests to me that web-ext is looking in the correct directory (this contains only your built files, right?)
```
[watcher.js][debug] Watching for file changes in /home/martin/dev/justintv-stream-notifications/webextension
```

The first change to trigger a reload happens in that directory:

```
[watcher.js][debug] Changed: /home/martin/dev/justintv-stream-notifications/webextension/background/index.js
[watcher.js][debug] Last change detection: 00:51:57 GMT+0100 (CET)
```

I don't see any changes in the `src/` directory so the watcher is working as expected.

Is it unexpected that these files were changed?

**Comment by freaktechnik** [comment]
It is unexpected that these files were changed, exactly. As the only thing actually writing to that director is webpack that ran just before launching web-ext run. This happens even if the only thing running is web-ext (of course there's a DM etc. but that still shouldn't touch the files for all I know). It also only happens for this extension, so it must be something related to the files being built by webpack or similar.

**Comment by kumar303** [comment]
web-ext uses webpack's [watcher implementation](https://github.com/mozilla/web-ext/blob/master/src/watcher.js#L2) with nothing fancy added except maybe the debouncer.

**Comment by freaktechnik** [comment]
I've added some logging to the watcher on change:
```js
console.log("CHANGE", Date.now(), mtime, start);
```
mtime is the modification time that the change event is getting passed and start is the timestamp when the watcher is started (so the Date.now() passed to the watcher when it starts).

This produces the following output:
```
CHANGE 1512081644234 1512081651821 1512081644206
CHANGE 1512081644237 1512081651821 1512081644206
CHANGE 1512081644237 1512081651821 1512081644206
CHANGE 1512081644238 1512081651821 1512081644206
CHANGE 1512081644238 1512081651821 1512081644206
CHANGE 1512081644238 1512081651821 1512081644206
CHANGE 1512081644239 1512081651821 1512081644206
CHANGE 1512081644239 1512081651821 1512081644206
CHANGE 1512081644240 1512081651821 1512081644206
CHANGE 1512081644241 1512081651821 1512081644206
CHANGE 1512081644241 1512081651821 1512081644206
CHANGE 1512081644241 1512081651821 1512081644206
CHANGE 1512081644242 1512081651821 1512081644206
CHANGE 1512081644242 1512081651821 1512081644206
CHANGE 1512081644242 1512081651821 1512081644206
CHANGE 1512081644243 1512081651821 1512081644206
CHANGE 1512081644243 1512081651821 1512081644206
CHANGE 1512081644246 1512081651821 1512081644206
CHANGE 1512081644246 1512081651821 1512081644206
CHANGE 1512081644246 1512081651821 1512081644206
CHANGE 1512081644246 1512081651821 1512081644206
CHANGE 1512081644247 1512081651821 1512081644206
CHANGE 1512081644247 1512081651821 1512081644206
CHANGE 1512081644247 1512081651821 1512081644206
CHANGE 1512081644247 1512081651821 1512081644206
CHANGE 1512081644247 1512081651821 1512081644206
CHANGE 1512081644248 1512081651821 1512081644206
CHANGE 1512081644248 1512081651821 1512081644206
CHANGE 1512081644248 1512081651821 1512081644206
```

Which doesn't really make much sense to me, since the `mtime` seems to be in the future, so bigger than the current timestamp.

**Comment by freaktechnik** [comment]
Looking at the watchpack package I'm wondering if this is related to https://github.com/webpack/watchpack/issues/25

**Comment by kumar303** [comment]
Looks like it could be related. Is you system clock synchronized and accurate?

**Comment by quentin-sommer** [comment]
Running into a similar issue. I run webpack to output 1 js file and 1 css file and have web-ext watch the destination folder. The extension currently reload in between the two changes. I'm confused about the  behavior of the debounce, does it only let through the first change?

**Comment by freaktechnik** [comment]
> Looks like it could be related. Is you system clock synchronized and accurate?
Yes, however the fs resolution seems to be low.

My current "workaround" is to disable watching, since I'm not running webpack in watch mode either.

**Comment by kumar303** [comment]
I think this is the problem:

https://github.com/mozilla/web-ext/blob/c505c060a16012169b2063fa5ac4c6e0f3b15546/src/watcher.js#L38-L39

Setting `executeImmediately` to true means the debounced function executes on the leading edge. For webpack's case, we want it to execute on the trailing edge--after all files have been built.

I think this was originally set to the leading edge only for speed, so that a reload happens as soon as possible. I think if we reduced the debounce wait time to 600ms (or something) we could switch it to the trailing edge.

@rpl do you think there's any reason we should preserve leading edge execution?

**Comment by kumar303** [comment]
Just to clarify the bug, here's something I see happening in a webpack based project:
- I run webpack in watch mode and `web-ext run` in parallel
- I edit some files
- Webpack begins writing output files
- The extension always reloads twice. This only started happening when I added more output files to my webpack config.

**Comment by quentin-sommer** [comment]
@kumar303 I came to the same conclusion

**Comment by hiikezoe** [comment]
A proper solution I can think of is to provide a webpack plugin to be able to use webpack watch mode.

**Comment by birtles** [comment]
> A proper solution I can think of is to provide a webpack plugin to be able to use webpack watch mode.

That's probably not a bad idea. It doesn't solve the problem for other tools, however. For example, I run the TypeScript compiler in watch mode and this produces the same problem -- I have to save the file twice so that `web-ext` picks up the compiled JS. Still, fixing webpack would fix the problem for a lot of people I suspect, perhaps even the majority.

**Comment by hiikezoe** [comment]
To create the webpack plugin, as far as I can tell, we need to separate the funcitonality to reload temporary installed extension from 'web-ext run' and also need the functionality to detach spawned firefox.   Once they happen it could be easily fit into other task runners (gulp I guess?).  Though  I am not sure about TypeScript watcher,  it should specify task dependencies as well?

I've started implementing the webpack plugin https://github.com/hiikezoe/web-ext-webpack-plugin .  Currently it just invokes lint though.  And it needs  #1290 .

**Comment by freaktechnik** [comment]
A webpack plugin was started about a year ago: https://github.com/rpl/webpack-webext-plugin

It would, however not solve my issue, where I am not using webpack watch, but on the other hand, as I mentioned, I can just disable watching.

**Comment by hiikezoe** [comment]
Gosh!  I wasn't aware of it.   At first glance if the plugin hooks 'done' instead of 'emit' here
https://github.com/rpl/webpack-webext-plugin/blob/master/index.js#L62 , doesn't it solve your issue?

**Comment by hiikezoe** [comment]
And it seems to me that the plugin does a tricky way.   So https://github.com/rpl/webpack-webext-plugin/issues/1 happens?
As I commented, as far as I can tell web-ext needs the functionality to detach spawned firefox instance to solve the issue.

**Comment by hiikezoe** [comment]
FWIW, I've just pushed a forked node-fx-runner to be able to detach firefox instance.

https://github.com/hiikezoe/node-fx-runner/tree/detach
