### ISSUE TITLE
Feature Request!   tabs.removeScript

### ISSUE THREAD

**Issue by Ulf3000** [mozilla/web-ext#1142]
hey mozilla team , tabs.executeScript is a good functionality but we need a similarly easy and quick solution to remove the script again , in the sdk i could just create and destroy a pagemod , the contextmenu content script was even removed automagically in the sdk . 

i demand the same for webext , easy, obvious and logical request imho ! 

thanx for listening !

**Comment by kumar303** [comment]
Hi. this is an issue tracker for the web-ext command line tool, not for the WebExtensions API within Firefox.

However, I think you might find what you need in the contentScripts.register() API https://bugzilla.mozilla.org/show_bug.cgi?id=1332273 (this landed in Firefox 59)

**Comment by rpl** [comment]
The Bugzilla issue for a `tabs.removeScript` is [Bug 1422596 - feature request: tabs.removeScript](https://bugzilla.mozilla.org/show_bug.cgi?id=1422596) and it has also been closed as invalid, I've just added a comment that provides some additional details about why and how to be able to cleanup a content script using the APIs already available:

https://bugzilla.mozilla.org/show_bug.cgi?id=1422596#c2

It is also worth to mention that the new `contentScripts.register` API linked above returns a `script` object that has a `script.unregister()` API method, but it doesn't remove the script already executed (for the same reasons explained in https://bugzilla.mozilla.org/show_bug.cgi?id=1422596#c2), but it removes from the list of the content scripts that can be executed in the next page loads (if they match, e.g. when navigating to a new page or when the current page is being reloaded).
