### ISSUE TITLE
[Feature] Populate manifest.json with package.json information

### ISSUE THREAD

**Issue by MikkCZ** [mozilla/web-ext#1143]
It would be nice if web-ext can populate manifest.json with information from package.json (or vice versa?) like the project name, description, author or version, unless i18n entities are used for them of course. At this moment if I use npm to run tests or build of the extension, I have duplicated information in package.json a manifest.json.

**Comment by anaran** [comment]
What kind of tests are you running and how?

I used to find `jpm test` quite useful and wonder how web-ext extension authors are doing their testing now.

**Comment by MikkCZ** [comment]
See https://github.com/MikkCZ/pontoon-tools for my small project for which I am interested the most. At this moment I only use npm to run eslint, but I want to add Mocha or Jasmine for unit tests. However there may be thousands of other reasons to use npm as a system for add-ons packaging, not just web-ext, but I haven't found any solution to solve the duplicity between package.json and manifest.json so far.

**Comment by kumar303** [comment]
Thanks for taking the time to file an issue. This seems like a good idea but you can already do it without `web-ext` and it seems a bit out of the `web-ext` scope to me.

There are a couple different approaches but I'd suggest building your extension with `webpack` (see [this example](https://github.com/mdn/webextensions-examples/tree/master/webpack-modules)) and then using something like [string-replace-webpack-plugin](https://www.npmjs.com/package/string-replace-webpack-plugin) to build your `manifest.json` using values from your `package.json` file.

> I ... wonder how web-ext extension authors are doing their testing now.

There are lots of ways to test a webextension. Unlike `jpm`, the `web-ext` tool does not prescribe one true way. Take a look at [this example](https://github.com/mdn/webextensions-examples/tree/master/mocha-client-tests) and also the [sinon-chrome](https://github.com/acvetkov/sinon-chrome) library which you can use to make assertions about what APIs are used. Keep in mind that webextensions are very similar to traditional web applications and can often be tested in the same way.
