### ISSUE TITLE
Change --firefox-binary to --firefox

### ISSUE THREAD

**Issue by kumar303** [mozilla/web-ext#116]
`web-ext run --firefox=/path/to/firefox-bin` seems more concise. We should also give it a short alias like `-f`.

**Comment by kumar303** [comment]
we should fix https://github.com/mozilla/web-ext/issues/169 first to avoid confusion when users upgrade their web-ext for this option change

**Comment by shubheksha** [comment]
For this issue, I need to modify [this](https://github.com/mozilla/web-ext/blob/master/src/program.js#L219) line & add an `alias` property like it has been included for other commands -- am I on the right track?

**Comment by kumar303** [comment]
Yes, I think that's the way to go.

**Comment by shubheksha** [comment]
I made the required changes & they're being reflected using the `--help` option. However, I am unable to test it & running into the following error. I've attached the screenshot for reference. 
![image](https://cloud.githubusercontent.com/assets/7693422/17712330/130e642a-6413-11e6-95bd-602388ac2a14.png)

**Comment by kumar303** [comment]
You should be able to use any of these extensions to test it: https://github.com/mdn/webextensions-examples/ You will need to cd into the source directory of one of the examples before executing `web-ext run`.

**Comment by kumar303** [comment]
One thing that may not be obvious is that [yargs](http://yargs.js.org/) has some magic that was turning `--firefox-binary` into the config key `firefoxBinary` when executing [run()](https://github.com/mozilla/web-ext/blob/master/src/cmd/run.js#L163). The `run()` signature probably also needs updating.

**Comment by shubheksha** [comment]
I am a little confused -- the variable `firefoxBinary` is strewn all over in [this](https://github.com/mozilla/web-ext/blob/master/src/cmd/run.js) file. What about those?

**Comment by kumar303** [comment]
Let's say you typed:

    web-ext run --firefox-binary /Applications/FirefoxNightly.app/Contents/MacOS/firefox-bin

This would invoke:

    cmd.run({firefoxBinary: '/Applications/FirefoxNightly.app/Contents/MacOS/firefox-bin', ...});

The variable is passed around to a few things that utilize the Firefox executable path.

**Comment by shubheksha** [comment]
Okay, that makes sense. But I don't really understand the flow even now. 
As you mentioned above, the config key `firefoxBinary` was being created by yargs on its own, so changing the option to `--firefox` should also work in a similar manner? I am sorry if this sounds stupid --  I am a little lost. I went through the yargs docs as well, but didn't find an answer to how this is being done.
From what I understood, `--firefox` will be changed to `firefox`, but that variable is already present in the file in multiple places.

**Comment by kumar303** [comment]
> From what I understood, --firefox will be changed to firefox, 

Yes, that's correct. It's not very well documented in yargs but if you log the [argv variable](https://github.com/mozilla/web-ext/blob/master/src/program.js#L80) you could see the complete object after yargs is done doing the magic translation.

> but that variable is already present in the file in multiple places.

Ah, good point. I see the problem now. There is already an option defined as [firefox=defaultFirefox](https://github.com/mozilla/web-ext/blob/master/src/cmd/run.js#L167) so the new yargs generated `firefox` variable will conflict. I think you'll need to rename this everywhere that it's used. Something like `firefoxApp=defaultFirefox` probably makes sense.

**Comment by shubheksha** [comment]
Firefox can't be found for some reason. Changing the variable names broke something, I guess. Despite giving it the full path to the .exe, it won't work. Hence, the builds are failing too. How can I go about finding what exactly broke?

**Comment by kumar303** [comment]
The [run command docs](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/web-ext_command_reference#web-ext_run) will need updating but we should wait until a new version of `web-ext` is released containing this change.

**Comment by kumar303** [comment]
I updated the docs
