### ISSUE TITLE
Apply package.json config to set option defaults

### ISSUE THREAD

**Issue by kumar303** [mozilla/web-ext#1166]
### Is this a feature request or a bug?

feature

### What is the current behavior?

You can define a custom config file named `web-ext-config.js` (as of https://github.com/mozilla/web-ext/issues/730) in your project directory to set option defaults.

### What is the expected or desired behavior?

It would be nice to specify a custom key in `package.json` like `webExt` that has configuration. This would cut down on the amount of config files littered in one's project directory.

For example, we want to support a case where a developer puts something like this in their `package.json`:

```json
{
  "name": "some-package",
  "version": "1.0.0",
  "webExt": {
    "sourceDir": "./src",
    "verbose": true,
    "run": {
      "firefox": "nightly"
    }
  }
}
```

This `package.json` file contains a custom key named `webExt` which has configuration data. We want to load that data as if it were in a config file. Read this to learn how to do it: https://stackoverflow.com/questions/10065564/add-custom-metadata-or-config-to-package-json-is-it-valid

Config tracker: https://github.com/mozilla/web-ext/issues/176

**Comment by grount** [comment]
Hello, would this be a good first contribution?
If so then to my understanding I should place a ```web-ext-config.js``` file inside the root directory and specify a custom key in ```package.json```?

**Comment by kumar303** [comment]
Hi @grount , thanks for your interest but @ChujunGeng is already working on it in https://github.com/mozilla/web-ext/pull/1266

**Comment by kumar303** [comment]
This was documented some time ago here: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Getting_started_with_web-ext#Setting_option_defaults_in_a_configuration_file
