### ISSUE TITLE
Cannot install: no valid versions of timed-out

### ISSUE THREAD

**Issue by MartinBurian** [mozilla/web-ext#1186]
### Is this a feature request or a bug?
Bug in installation

### What is the current behavior?
I cloned this repo and ran `npm install`:
```
...
3369 verbose Linux 4.11.6-3-ARCH
3370 verbose argv "/usr/bin/node" "/home/martinjr/.node_modules/bin/npm" "install"
3371 verbose node v8.7.0
3372 verbose npm  v5.6.0
3373 error code ENOVERSIONS
3374 error No valid versions available for timed-out
3375 verbose exit [ 1, true ]
```
(full log attached [2018-01-06T19_57_10_209Z-debug.log](https://github.com/mozilla/web-ext/files/1609176/2018-01-06T19_57_10_209Z-debug.log))

It also happens if i npm install web-ext directly.

### What is the expected or desired behavior?
It should install npm dependencies

### Version information (for bug reports)
````
node --version && npm --version && web-ext --version

v8.7.0
5.6.0
bash: web-ext: command not found
````

**Comment by rpl** [comment]
There was a general issue on the npm registry:

npm/registry#255
