### ISSUE TITLE
Package also for chrome

### ISSUE THREAD

**Issue by Mte90** [mozilla/web-ext#119]
Is possible add a parameter for build that package the extension for chrome in a zip file?
Basically the web-ext works also for chrome without the `applications` section in the manifest.json.
Actually to do that I remove that part in the manifest.json and create a zip to upload on the Chrome Web Store with the same files of the firefox version.

**Comment by kumar303** [comment]
Yes, I'd like to add this feature. It would be great if the build step automatically converted the manifest for each platform.

**Comment by bwinton** [comment]
I believe we're looking into [not adding the extra keys](https://wiki.mozilla.org/WebExtensions/Applications) into manifest.json, and instead having a “mozilla.json” file (or something similar), which should make this easier to implement.  :wink:

**Comment by kumar303** [comment]
Chrome package format: https://developer.chrome.com/extensions/crx

**Comment by Mte90** [comment]
Actually to package automatically for firefox and chrome I've written this https://github.com/Mte90/Script/blob/master/pack-ext.py

**Comment by kumar303** [comment]
Does the extension load in Chrome? I don't see it writing the "magic number" to the beginning of the zip file which Chrome's docs say is mandatory: "Chrome requires this constant at the beginning of every .crx package."

**Comment by Mte90** [comment]
the extension create the zip for the chrome web store and works without problems.
The web store require a zip package, the .crx is only outside the web store.

**Comment by kumar303** [comment]
OK, I see.

**Comment by tofumatt** [comment]
I think the answer to this is we should output `.zip` files by default, not `.xpi` files. [AMO now accepts `.zip`](https://github.com/mozilla/addons-server/issues/2727) files (converts them to XPI for Firefox) but for development Firefox will accept `.zip` temporary add-ons.

**Comment by kumar303** [comment]
Oh yeah, good idea. https://github.com/mozilla/web-ext/issues/325

**Comment by kumar303** [comment]
This has been fixed by https://github.com/mozilla/web-ext/pull/328

We're not explicitly supporting the `.crx` format. Instead we build to `.zip` which is supported by both Firefox and Chrome :)

**Comment by kumar303** [comment]
@tofumatt kindly updated all the docs so I'm removing the label:
* https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Getting_started_with_web-ext
* https://developer.mozilla.org/en-US/Add-ons/WebExtensions/web-ext_command_reference

**Comment by Croydon** [comment]
@kumar303 I'm wondering, what is about the manifest?

**Comment by kumar303** [comment]
@Croydon in its current state, you'd have to use only manifest properties that are compatible between Chrome and Firefox (see https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Chrome_incompatibilities).

I'd like to see some workflows that developers are using to manage a web extension supporting both Chrome and Firefox (with differences between the two). This will help guide what sort of features to add for building multiple, varying package files.
