### ISSUE TITLE
Array values are not recognized as is in config file

### ISSUE THREAD

**Issue by MarkaPola** [mozilla/web-ext#1198]
### Is this a feature request or a bug?
a bug

### What is the current behavior?

config file does not recognize, as expected, parameters with array as value. For example, the following config file:
```javascript
module.exports = {
    ignoreFiles: [
        'web-ext-config.js'
    ]
};
```
Following command
```
web-ext build
```
raises the following error:
```
Applying config file: ./web-ext-config.js

UsageError: The config file at .../web-ext-config.js specified the type of "ignoreFiles" incorrectly as "object" (expected type: "array")
```

### What is the expected or desired behavior?
parameter ignoreFiles recognized its value as an array.

### Version information (for bug reports)

* **Firefox version**: irrelevant
* **Your OS and version**: MacOS 10.13.2

````
node --version && npm --version && web-ext --version
````
node: v8.2.1
npm: 5.4.2
web-ext: 2.3.0

**Comment by rpl** [comment]
@MarkaPola thanks a lot for reporting this issue, I've investigated it and opened a pull request (#1199) to fix it.

**Comment by kumar303** [comment]
Thanks again for the bug report. This has been released but it will take about 10 minutes to be published on NPM: https://github.com/mozilla/web-ext/releases/tag/2.3.1
