### ISSUE TITLE
Verbose option ignored when declared in config file

### ISSUE THREAD

**Issue by dessant** [mozilla/web-ext#1214]
### Is this a feature request or a bug?
bug

### What is the current behavior?
web-ext-config.js
```js
module.exports = {
  verbose: true
};
```

```
$ web-ext run -s dist
Applying config file: ./web-ext-config.js
Running web extension from /media/s1/dev/pr/clear-browsing-data/dist
Use --verbose or open Tools > Web Developer > Browser Console to see logging
Installed /media/s1/dev/pr/clear-browsing-data/dist as a temporary add-on
The extension will reload if any source file changes
Press R to reload (and Ctrl-C to quit)
```

### What is the expected or desired behavior?
The process should switch to verbose output after the config file is parsed, or the limitation should be documented.

### Version information (for bug reports)

* **Firefox version**: 57.0.4
* **Your OS and version**: Arch Linux

````
$ node --version && npm --version && web-ext --version
v8.9.1
5.5.1
2.3.1

````

**Comment by kumar303** [comment]
Oof, I don't know how we missed this. Thanks for the bug report. Fixed in https://github.com/mozilla/web-ext/pull/1221
