### ISSUE TITLE
Run an extension in a linked profile for persistence

### ISSUE THREAD

**Issue by kumar303** [mozilla/web-ext#123]
Calling [run --firefox-profile=myprofile](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/web-ext_command_reference#web-ext_run) will copy a custom profile into a temporary profile. It will not affect the original profile. This new feature is to run the extension directly in the custom profile so that any profile changes will be saved. 

Example use case: if you're developing an extension that has a splash screen on install, you may not want to see that screen every time you launch Firefox to test it.

We should probably introduce a new option that can be called alongside the existing ones like this:
````bash
web-ext run --firefox-profile=myprofile --keep-profile-changes
````

**Comment by kumar303** [comment]
I have heard of a few scenarios where users are trying to test specific startup behavior that cannot be accomplished with auto-reloading so we should prioritize this.

One thing to consider is how to deal with adding prefs that web-ext needs to operate. Maybe showing a warning about altering the profile is good enough.

**Comment by saintsebastian** [comment]
If no one minds, I'd like to work on this one. I am not 100% clear on all details, but I think I know this particular part of source enough to figure it out as I go.

**Comment by kumar303** [comment]
That's great, thanks! I updated the issue description with more details.

The change should be pretty straight forward. You can just delete the [call to copyProfile()](https://github.com/mozilla/web-ext/blob/master/src/cmd/run.js#L320) so that the original path is used instead of a copy.

**Comment by kumar303** [comment]
@saintsebastian I just pushed this out too in [1.9.0](https://github.com/mozilla/web-ext/releases/tag/1.9.0). Could you add this new option to the [web-ext run](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/web-ext_command_reference#web-ext_run) option reference?

**Comment by saintsebastian** [comment]
@kumar303 hopefully my description is sufficient. Don't know whether I should mention that it should work together with `--firefox-profile`

**Comment by kumar303** [comment]
This looks great, thanks! I added some clarifications about how it also adds additional prefs.
