### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by webdev23** [mozilla/web-ext#1247]
### Is this a feature request or a bug?

A bug at install, leading to a request.

### What is the current behavior?

Installation fails on ubuntu.

Tried without _--global_, and with _sudo_ rights, both failed.

### What is the expected or desired behavior?

Headless apt install. 

As userscripts are now gone from FF57++, we need a reliable dev tool suite now!

### Version information (for bug reports)

* **Firefox version**: 58
* **Your OS and version**: linux ubuntu mate
* Paste the output of these commands:

````
node --version && npm --version && web-ext --version
````

> v4.2.6
> 3.5.2
> SyntaxError: Unexpected token .
>     at exports.runInThisContext (vm.js:53:16)
>     at Module._compile (module.js:374:25)
>     at Object.Module._extensions..js (module.js:417:10)
>     at Module.load (module.js:344:32)
>     at Function.Module._load (module.js:301:12)
>     at Module.require (module.js:354:17)
>     at require (internal/module.js:12:17)
>     at Object.<anonymous> (/usr/local/lib/node_modules/web-ext/node_modules/whatwg-url/lib/public-api.js:3:15)
>     at Module._compile (module.js:410:26)
>     at Object.Module._extensions..js (module.js:417:10)
>

**Comment by rpl** [comment]
@webdev23 web-ext [requires the current active LTS](https://github.com/mozilla/web-ext/#installation-from-npm) to install and run correctly.

Based on the [nodejs release schedule]((https://github.com/nodejs/Release#release-schedule)): 
- nodejs 6 is the current LTS (long term support) version of Node
- nodejs 4 is near the end of its maintenance period (which is scheduled to end on 2018-04-30).

**Comment by webdev23** [comment]
Thanks for reply.

It appear that I don't use node.js at all. 
I just want to convert/rewrite my few kb usercript sets, who doesn't runs anymore, to web extensions.
Regular package managers are failing to upgrade to the required node LTS v6x+ version.
The command line provided on the nodejs site is also failing for me. 
https://nodejs.org/en/download/package-manager/
I tried a fancy tool called nvm, but it somehow failed.
Didn't not find any solution beside a **full distro upgrade**.
We found this, me and the cat, a bit heavy!

Leaving here, sadly, the node js upgrade for someone in my case:

```
curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | sudo apt-key add -

sudoedit /etc/apt/sources.list.d/nodesource.list

deb https://deb.nodesource.com/node_9.x xenial main
deb-src https://deb.nodesource.com/node_9.x xenial main

sudo apt-get update
sudo apt-get upgrade -V

sudo apt install nodejs

sudo npm install --global web-ext

```
This lead to a loop of:

>  WARN EACCES user "root" does not have permission to access the dev dir "/usr/lib/node

This can be fixed with the flag **unsafe-perm**.

`sudo npm install --unsafe-perm --global web-ext`

Thanks

**Comment by gluons** [comment]
Maybe [nvm](https://github.com/creationix/nvm) is easier to install & manage your node version. 🙂  
No problem with **root** permission.

**Comment by kumar303** [comment]
Sorry for the confusion. I'm closing this since web-ext requires Node 6 as mentioned. Bookmarklets are indeed easy to replicate in an extension. All you need is a [browser action](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/browserAction) that when clicked triggers a handler in the [background script](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Anatomy_of_a_WebExtension#Background_scripts).
