### ISSUE TITLE
manifest.json parser too strict

### ISSUE THREAD

**Issue by freaktechnik** [mozilla/web-ext#1285]
### What is the current behavior?
The manifest.json is parsed using the `json-parser` package, which emits nicer errors, but does not support comments. This was discovered with an error when trying to sign an extension with comments in the manifest by @AntoineTurmel.

### What is the expected or desired behavior?
The parser should be able to handle comments in the manifest.json file.

**Comment by tommai78101** [comment]
Comments are not valid in any JSON files.

https://plus.google.com/+DouglasCrockfordEsq/posts/RK8qyGVaGSr

**Comment by freaktechnik** [comment]
While that is generally true, it does not apply to manifest.json and messages.json files. We sadly have to expect comments in them.

See also https://browserext.github.io/browserext/#pre-parsing

**Comment by tommai78101** [comment]
Ugh, I accidentally deleted my previous comment. Original comment:

> Comments are not valid in all JSON files.

-------

I see, so in this case, only manifest.json and messages.json files are exempt from it? I do not see in the current article saying the messages.json should also ignore comments.
