### ISSUE TITLE
'For Your Project' README Grammar 

### ISSUE THREAD

**Issue by OlyBar** [mozilla/web-ext#1299]
**For your project**
Alternatively, you can install this command as one of the devDependencies of your project. This method can help you control the version of web-ext used by your team. (You don't need **as**)

npm install --save-dev web-ext
Next you can use the web-ext command in your project as an npm script. Here is an example where **(when not where**) the --source-dir argument specifies where to find the source code for your extension.

**These are my thoughts on how these sentences can flow better. This is my first time contributing to an open source project so any advice would greatly be appreciated. Thanks!**

**Comment by Rob--W** [comment]
Hi @OlyBar, thanks for taking your time to open this issue.

The grammar of these cited sentences appear correct.

> This method can help you control the version of web-ext *as* used by your team. 

The presence of "as" is correct: "as" has the third meaning as defined by https://www.merriam-webster.com/dictionary/as

> Here is an example *where* the `--source-dir` argument specifies where to find the source code for your extension.

"when" is used to refer to a time of event, whereas in this case "where" refers to a place ("an example").
To learn more about relative adverbs, see https://english.tutorvista.com/grammar/relative-adverbs.html
