### ISSUE TITLE
Nightly broken again

### ISSUE THREAD

**Issue by Lusito** [mozilla/web-ext#1316]
### What is the current behavior?

If I run `web-ext run -f <path to firefox exe>`, Firefox Nightly starts, but without the add-on.

I get the following error when using --verbose:

```
[firefox/index.js][debug] Firefox stdout: console.error: (new Error("Could not install add-on at '<path to extension>': Error: OS.File has been shut down. Rejecting request to DirectoryIterator_prototype_next", "resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/addons.js", 25))
```

Once it started and I switch to about:debugging, I can load the add-on, so it's not like it can't load or anything.

### What is the expected or desired behavior?

The addon should be loaded. It works if I specify stable Firefox.

### Version information (for bug reports)

* **Firefox version**: 62.0a1 (2018-05-10) (64-bit)
* **Your OS and version**: Windows 7
* Paste the output of these commands:

````
node --version && npm --version && web-ext --version
````
v9.8.0
5.7.1
2.6.0

**Comment by rpl** [comment]
I've been unable to reproduce this locally, on a pretty similar environment:
- windows 7 64 bit
- Nightly 62.0a1 2018-05-10
- node 9.8.0
- npm 5.6.0
- web-ext 2.6.0

@Lusito is there anything in your environment  that may have a role on triggering the issue?
(e.g. other installed software, a particular disks / partitions setup, performance characteristics
of the machine)
or maybe another machine that you could use to try to reproduce the same issue on?

**Comment by Lusito** [comment]
I did have some missing python errors during installation of web-ext. But since it works for stable firefox I don't think it's related. I will try to reproduce this on my laptop when I get some free time.

My Firefox is located at F:\Applications\FirefoxNightly, while my code is located on a different partition on e:\code\firefox-webext\forget-me-not.

**Comment by Lusito** [comment]
Sorry for the delay. I just tested it again and on my Laptop it worked. Then I noticed, that Nightlys CPU usage was very high on my (considerably stronger) desktop pc and the extension would finally get loaded after about 26 seconds, where the 8 year old laptop would take 2 seconds.

So I'm guessing this is more of a Nightly performance issue.

**Comment by rpl** [comment]
@Lusito no worries about the delay, on the contrary thanks for the additional informations.

I guess that the nightly versions on the two machines are exactly the same ones, right?

does the project include a big node_modules dir or some other big directory tree that may be trigger [Bug 1462669 ("Extension dev: Presence of "node_modules" causes very slow extension load")](https://bugzilla.mozilla.org/show_bug.cgi?id=1462669)?

**Comment by Lusito** [comment]
Good idea, I forgot to update my nightly on desktop. It was 13 days older. It seems to be fixed in the latest version, so it might have been that bug (which is resolved fixed).

My node_modules directory was about 230mb.
