### ISSUE TITLE
Build web extensions without an ID

### ISSUE THREAD

**Issue by andymckay** [mozilla/web-ext#132]
In support of https://wiki.mozilla.org/WebExtensions/Applications, this will let you build an extension without an ID.

**Comment by andymckay** [comment]
Tracking: mozilla/addons#61

**Comment by andymckay** [comment]
We slightly changed the specification to not worry about mozilla.json. Instead we'll just cope with it being in one of two fields in manifest.json, see the spec for more.

**Comment by kumar303** [comment]
For this first pass, only the build command can allow extensions without an ID. 

TODO:
* run extensions without an ID (https://github.com/mozilla/web-ext/issues/177)
* sign extensions without and ID (https://github.com/mozilla/web-ext/issues/178)

**Comment by kumar303** [comment]
I don't think this needs any explicit documentation
