### ISSUE TITLE
"Missing required arguments: api-key, api-secret" with correct configuration

### ISSUE THREAD

**Issue by woky** [mozilla/web-ext#1327]
% cat ~/.web-ext-config.js
    module.exports = {
        verbose: true,
        apiKey: '<redacted>',
        apiSecret: '<redacted>'
    };
    % web-ext sign
    <snipped>
    Missing required arguments: api-key, api-secret

I've also tried to wrap api settings in `sign: { }` object.

Passing secrets on command line is generally not a good idea.

**Comment by mantou132** [comment]
i have some problem

**Comment by yan12125** [comment]
Seems this will be fixed once https://github.com/mozilla/web-ext/issues/176 is done.

**Comment by cawa-93** [comment]
I faced the same problem. So what's the solution? What have you come to all these years?

**Comment by cawa-93** [comment]
It seems that the "sign" command completely ignores any configuration file:
```js
// web-ext-config.js
console.log('Log from web-ext-config.js')
throw new Error('Stop working')
```
```
web-ext sign --config=web-ext-config.js
> Missing required arguments: api-key, api-secret
```
