### ISSUE TITLE
`web-ext sign` needs to accept "--ignore-files" option (when used from within a nodejs deploy script)

### ISSUE THREAD

**Issue by gkrishnaks** [mozilla/web-ext#1333]
### Is this a feature request or a bug?
Feature request.

### What is the current behavior?
"web-ext sign" ignores the --ignore-files option. 
web-ext build has this option and excludes the glob pattern matched files.  

### What is the expected or desired behavior?
Web-ext sign should accept --ignore-files option and build a zip without the excluded files - when used from within a nodejs script to deploy from CI Cd pipeline.

Node v8

```
const args = [
    'sign',
    '--source-dir', source,
    '--api-key', process.env.JWT_ISSUER,
    '--api-secret', process.env.JWT_SECRET,
    '--ignore-files', 'package.json package-lock.json yarn.lock .npmrc .yarnc',
  ]

 const child = execa(webextBinPath, args, { stdio: ['ignore', 'pipe', 'inherit'] })

```

(I noticed closed issue #843 . This issue is with respect to calling webext sign from within nodejs script)

**Comment by rpl** [comment]
with code linked in the description, ignore-files is going to be the string "package.json package-lock.json ...", as if you are executing the following command:

```
$ web-ext sign --ignore-files "package.json package-lock.json ...." ....
```

and so the resulting pattern is not matching any of those files, whereas web-ext is supposed to receive an array of those files (actually patterns) as the value of the ignore-files parameter.

You should be able to achieve that by just splitting those patterns into separate strings in the arguments:

```
const args = [
    ...
    '--ignore-files', 'package.json', 'package-lock.json', 'yarn.lock', '.npmrc', '.yarnc',
];
...
```

I'm closing this issue as invalid in the meantime, but feel free to re-open it if you are still able to reproduce it (and in that case, attaching the additional logs produced by web-ext when running in verbose mode may also be useful to investigate the issue).

**Comment by gkrishnaks** [comment]
Thank you, let me try that.
