### ISSUE TITLE
Add option to web-ext build: --filename="%{applications.gecko.id}-%{version}.zip

### ISSUE THREAD

**Issue by motin** [mozilla/web-ext#1335]
### Is this a feature request or a bug?

Feature request

### What is the current behavior?

Built files are named according to [safeFileName(`${extensionName}-${manifestData.version}.zip`)](https://github.com/mozilla/web-ext/blob/master/src/cmd/build.js#L143-L144) without any ability to customize the filename.

### What is the expected or desired behavior?

Add a new option like build --filename="some-file.zip". However, to make it useful, it should also accept parameters for substitution, preferably corresponding to manifest contents. Example: `web-ext build --filename="%{applications.gecko.id}-%{version}.zip`

Originally mentioned here: https://github.com/mozilla/web-ext/issues/855#issuecomment-375214750

### Version information (for bug reports)

web-ext 2.7.0

**Comment by deadcoder0904** [comment]
Any updates on this feature? Would love to have it :)

**Comment by Rob--W** [comment]
Patches are welcome. This is also relatively simple to implement, forward a command-line parameter to https://github.com/mozilla/web-ext/blob/1e6e51b9cacf5f56c9a87f4cbaec9bae07b7ca11/src/cmd/build.js#L147
and add some unit tests.

**Comment by rpl** [comment]
@Rob--W sounds good to you if I assign you as mentor for this bug?

**Comment by Rob--W** [comment]
Yeah, I will mentor this bug.

**Comment by kumar303** [comment]
Since `{}` can't be used in a filename (I think?), the formatting string could probably be as simple as `--filename="{applications.gecko.id}-{version}.zip"`

**Comment by Rob--W** [comment]
`{` and `}` are not forbidden, but they may have special behavior on Windows if the name matches a CSLID. I think that it is reasonable to not support them, so we can use `{}` to mark variables.

Filesystems on Windows have the most restrictions: https://docs.microsoft.com/en-us/windows/win32/msi/filename
Other filesystems have fewer restrictions: https://en.wikipedia.org/wiki/Filename#Comparison_of_filename_limitations

**Comment by birtony** [comment]
I would be happy to work on this feature if that's possible!
