### ISSUE TITLE
Web-ext still does not allow comments in _locales JSONs

### ISSUE THREAD

**Issue by rugk** [mozilla/web-ext#1352]
### Is this a feature request or a bug?
bug

### What is the current behavior?
```js
$ ../node_modules/web-ext/bin/web-ext build
Building web extension from […]/offline-qr-code/src

UsageError: Error parsing messages.json JSONError: Unexpected token / in JSON at position 4 while parsing near '{  // manifest.json  "...' in […]/offline-qr-code/src/_locales/en/messa
```

### What is the expected or desired behavior?
No error.

Browsers also repect comments in these JSON files. Sources:
* https://discourse.mozilla.org/t/manifest-json-should-mention-it-allows-comments/27529
* similar issues: https://github.com/WeblateOrg/weblate/issues/2043

### Version information (for bug reports)

* **Your OS and version**: Fedora 28
* Paste the output of these commands:

````
v8.11.3
5.6.0
2.8.0
````

**Comment by Lusito** [comment]
encountered this as well.. interestingly, web-ext lint is okay with this!
