### ISSUE TITLE
Update to secure version of firefox-profile when available

### ISSUE THREAD

**Issue by groovecoder** [mozilla/web-ext#1358]
I filed https://github.com/saadtazi/firefox-profile-js/issues/98 against this project's `firefox-profile` dependency.

When it is fixed, a new release of `web-ext` should be made that includes the updated version of `firefox-profile`.

**Comment by rpl** [comment]
@groovecoder Thanks for reporting the issue upstream and for opening this issue to keep track of it.

We've just released a new web-ext version (2.9.0) which also have firefox-profile npm dependency updated to version 1.2.0, and so I'm going to close this issue, but feel free to re-open it in case it is not.

**Comment by groovecoder** [comment]
🎉 thanks!
