### ISSUE TITLE
web-ext lint doesn't allow duplicate keys in json files.

### ISSUE THREAD

**Issue by Lusito** [mozilla/web-ext#1360]
### Is this a feature request or a bug?

Bug report

### What is the current behavior?

- Create a locale messages.json file with two entries that have the same key.
- Run web-ext lint => "JSON_DUPLICATE_KEY" "Duplicate keys are not allowed in JSON files."

### What is the expected or desired behavior?

Duplicate keys should be allowed. The JSON specification does not forbid it.

I use duplicate keys to mark groups in my translation tool [web-ext-translator](https://github.com/Lusito/web-ext-translator).
Here, I use this kind of message multiple times:
```json
"__WET_GROUP__": { "message": "Branding" },
...
"__WET_GROUP__": { "message": "Settings" },
```

It is possible to add a suffix to every key, but that is a pain.
It is also possible to use comments, but:
- That is not valid json, even if it is valid in web-extensions
- Doesn't work with web-ext build, as can be seen in #1352 

### Version information (for bug reports)

* Firefox 61
* Windows 7
* Node version: v9.8.0
* web-ext version: 2.8.0

**Comment by Rob--W** [comment]
Although JSON doesn't explicitly forbid duplicate keys, the existence of duplicate keys is usually an error, because a key can only map to one translated value. Therefore it is very reasonable for the tool to reject duplicate keys.

If you don't like the use of prefixes, then you could also consider an extra property in a message to mark it as the start/member of a group.

**Comment by Lusito** [comment]
Wouldn't it be possible to convert this error into a warning? These are also visibly shown to the user when they upload an extension as far as I remember.
Having duplicate keys works perfectly fine when running a web-extension, so rejecting an extension based on this is in my opinion not necessary.

**Comment by Rob--W** [comment]
`web-ext lint` uses addons-linter, and the `JSON_DUPLICATE_KEY` check was introduced by https://github.com/mozilla/addons-linter/pull/1919

Converting it to a warning sounds reasonable, so please open a new issue at https://github.com/mozilla/addons-linter/issues .

**Comment by Lusito** [comment]
Thanks
