### ISSUE TITLE
FR: append hint to 'Server response: Version already exists. (status: 409)'

### ISSUE THREAD

**Issue by tomquas** [mozilla/web-ext#1372]
### Is this a feature request or a bug?
FR

### What is the current behavior?
Building web extension from /.../extension
Server response: Version already exists. (status: 409)
FAIL

WebExtError: The extension could not be signed
...

### What is the expected or desired behavior?
desired: give a hint on which was the latest version signed so that one can easily adapt the manifest accordingly. i know, release management – but things get out of order occasionally, we all know that. today, i have to navigate to AMO and cross fingers that nobody signed a later release and put it on a website, not updating AMO.

### Version information (for bug reports)
````
node --version && npm --version && web-ext --version
v10.11.0
6.4.1
2.9.1
````

**Comment by rpl** [comment]
@tomquas web-ext is currently just printing the [error received from the server](https://github.com/mozilla/addons-server/blob/d71d63cc1e350ddebe495cda6ea4247edcb35414/src/olympia/signing/views.py#L131-L135), and so web-ext can't provide that information on its own, only the server have access to the versions already submitted.

Do you mind to file an issue on the [addons-server github repo](https://github.com/mozilla/addons-server) to ask the AMO developers their opinion related to this enhancement request?

**Comment by tomquas** [comment]
@rpl sure, done.
