### ISSUE TITLE
Bug in One-Click YouTube Videos Download 1.1.9

### ISSUE THREAD

**Issue by cldjrt** [mozilla/web-ext#1373]
When this addon is activated it show vertical and horizontal scrolling bar in middle of the video image ! Not exactly what I'm expecting. 
I use it with  Firefox Quantum 62.0.3 (64 bit) on Mac OS X 10.11.6

![screen shot 2018-10-07 at 15 46 24](https://user-images.githubusercontent.com/43925418/46580085-36c2eb00-ca48-11e8-9554-e95df274bb5f.png)

**Comment by Rob--W** [comment]
Could you explain why this bug was reported here? How does it relate to the project (the `web-ext` CLI tool)?

**Comment by cldjrt** [comment]
I'm sorry but I have no idea.
I just click on the link made by Julie-Rodriguez on the Firefox extensions page to report a bug.

________________________________
De : Rob Wu <notifications@github.com>
Envoyé : dimanche 7 octobre 2018 16:42
À : mozilla/web-ext
Cc : cldjrt; Author
Objet : Re: [mozilla/web-ext] Bug in One-Click YouTube Videos Download 1.1.9 (#1373)


Could you explain why this bug was reported here? How does it relate to the project (the web-ext CLI tool)?

**Comment by Rob--W** [comment]
That add-on is unaffiliated with Mozilla. If I were you, I would remove [the add-on](https://addons.mozilla.org/en-US/firefox/addon/oneclickyoutubevideosdownload/), since it inserts an advertisement in every page that you are visiting (=the scrollbars that you are seeing).

**Comment by cldjrt** [comment]
Thank you for this good advise

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
