### ISSUE TITLE
Consider using TravisCI for Windows testing

### ISSUE THREAD

**Issue by kumar303** [mozilla/web-ext#1380]
### Is this a feature request or a bug?

feature

### What is the current behavior?

We use Appveyor for Windows CI but it's a little flaky.

### What is the expected or desired behavior?

TravisCI just announced Windows support: https://blog.travis-ci.com/2018-10-11-windows-early-release

Maybe it will be less flaky?

**Comment by EnTeQuAk** [comment]
We should do that for the linter too, AppVeyor is really bad, doesn't run node8+10 tests in parallel etc. I'll try switch the linter too :)
