### ISSUE TITLE
Add init command to start a web extension

### ISSUE THREAD

**Issue by kumar303** [mozilla/web-ext#141]
It might be a nice shortcut to provide an `init` command similar to jpm that starts a web extension from scratch by interactively prompting you for manifest values.

**Comment by andymckay** [comment]
There are a few projects that kind of do this already:
* https://github.com/yeoman/generator-chrome-extension
* http://extensionizr.com/

There are probably more, would it make sense to work with an existing project on this?

**Comment by kumar303** [comment]
whoops, we had a dupe issue (with a bit more traction) in https://github.com/mozilla/web-ext/issues/540 . I moved your link suggestions over there, thanks.
