### ISSUE TITLE
Check for updates to self and alert users

### ISSUE THREAD

**Issue by tofumatt** [mozilla/web-ext#142]
Because it's likely to be installed globally and not manually updated (I, and--anecdotally--many other developers, aren't in the habit of updating their globally installed commands on a regular basis), `web-ext` should check for updates to itself every once in awhile. A day or two is probably fine.

It should simply alert the user to the fact that there's a new version and the `npm` command to install it.

**Comment by kumar303** [comment]
Yeah, seems like a useful feature. In jpm, many people reported bugs from old versions.

**Comment by kmaglione** [comment]
@kumar303 Can you add some more details about how to implement this?

Thanks!

**Comment by kumar303** [comment]
The ultimate goal would be to run a web-ext command and see something like this:
````
$ web-ext build
...
Your extension has been built: /path/to/extension.xpi

Additionally, your web-ext version is at 1.0.1 but 1.0.5 is available.
Run `npm upgrade -g web-ext` to get the latest version.
````

To implement it, we can probably use the registry client: https://github.com/npm/npm-registry-client (I don't think it needs credentials to simply fetch latest package data).

The current web-ext version is already exposed in [program.main()](https://github.com/mozilla/web-ext/blob/master/src/program.js#L113) but it will probably probably need to be passed into the Program object like `program = new Program({version: version(absolutePackageDir)})`

**Comment by kumar303** [comment]
Some other nice to haves:
- An option that will disable the version checks.
- Suppress version checking if there is no Internet access. Example: doing `web-ext run` on an airplane because why not.

**Comment by kumar303** [comment]
I decided this isn't such a good first bug because interaction with the NPM API could be complex

**Comment by kumar303** [comment]
@shubheksha I saw your message about using this: https://github.com/yeoman/update-notifier Looks great!
