### ISSUE TITLE
Add command to sign a web extension

### ISSUE THREAD

**Issue by kumar303** [mozilla/web-ext#145]
Similar to [jpm sign](https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/jpm#jpm_sign), one should be able to run `web-ext sign` to build and sign the extension.

**Comment by kumar303** [comment]
The jpm signing parts have been extracted to https://github.com/mozilla/sign-addon

**Comment by jc3213** [comment]
@kumar303 could we still use `jpm sign` to sign addons?

**Comment by kumar303** [comment]
Yes, of course! But `jpm sign` will only work for SDK add-ons and pre-SDK add-ons. It will not support web extensions.

**Comment by jc3213** [comment]
Then this node lib is to sign all types of add-ons?

**Comment by kumar303** [comment]
`jpm sign` will always support signing SDK add-ons. At first, jpm will also sign older `install.rdf` add-ons. However, in the future I think older add-ons will need to use the [sign-addon](https://github.com/mozilla/sign-addon/issues/9) command directly.

**Comment by kumar303** [comment]
This is documented now https://developer.mozilla.org/en-US/Add-ons/WebExtensions/web-ext_command_reference#web-ext_sign
