### ISSUE TITLE
Firefox WebExtension debugging is broken

### ISSUE THREAD

**Issue by sunknudsen** [mozilla/web-ext#1489]
### Is this a feature request or a bug?

Bug

### What is the current behavior?

Opening the add-on debugger fails with the following error:

```
Browser Toolbox connection status:

Connecting to localhost:63443, ws: false
[Exception... "Component returned failure code: 0x804b000d (NS_ERROR_CONNECTION_REFUSED) [nsIInputStream.available]"  nsresult: "0x804b000d (NS_ERROR_CONNECTION_REFUSED)"  location: "JS frame :: resource://devtools/shared/base-loader.js -> resource://devtools/shared/security/socket.js :: onInputStreamReady :: line 329"  data: no]
onInputStreamReady@resource://devtools/shared/base-loader.js -> resource://devtools/shared/security/socket.js:329:9
```

<img width="900" alt="screen shot 2019-01-08 at 10 57 01 am" src="https://user-images.githubusercontent.com/2117655/50842564-fa4ba780-1334-11e9-842c-db591c746f99.png">

### What is the expected or desired behavior?

Opening the add-on debugger works as shown on https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Debugging.

### Steps to reproduce bug

- Inside the build folder, run `web-ext run --verbose` // This step opens a Firefox development window
- Navigate to `about:debugging` using address bar
- Make sure `Enable add-on debugging` is checked
- Click `Debug`

### Version information (for bug reports)

* **Firefox version**: Firefox 64.0
* **Your OS and version**: MacOS 10.13.6
* Paste the output of these commands:

````
node --version && npm --version && web-ext --version
````

v10.11.0
6.4.1
2.9.3

**Comment by kumar303** [comment]
Thanks for jumping on IRC to discuss this. We think it may be a platform issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1514215

**Comment by sunknudsen** [comment]
There is a similar bug report on Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1514215

**Comment by sunknudsen** [comment]
@kumar303 According to the bug report on Bugzilla, the issue has also occurred on Windows. Btw, sorry for the duplicate link above. Think we posted both links at the same time.

**Comment by sunknudsen** [comment]
@kumar303 Let me know if I can help out.

**Comment by sunknudsen** [comment]
Dropping more debug info here in case it can help.

When I click `Debug` on `about:debugging`, I get the following errors:

```
[firefox/index.js][debug] Firefox stderr: Can't find symbol 'GetGraphicsResetStatus'.
[firefox/index.js][debug] Firefox stdout: Debugger Server for Browser Toolbox listening on port: 50159
[firefox/index.js][debug] Firefox stdout: 1546972284687	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid host permission: resource://pdf.js/
1546972284687	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid host permission: about:reader*
[firefox/index.js][debug] Firefox stdout: JavaScript error: chrome://global/content/viewSourceUtils.js, line 20: TypeError: can't redefine non-configurable property "Services"
[firefox/index.js][debug] Firefox stdout: Can't find symbol 'GetGraphicsResetStatus'.
[firefox/index.js][debug] Firefox stdout: console.error: ({})
```

**Comment by sunknudsen** [comment]
Rebooted and bug is gone.

Note to self: always try to reboot computer before submitting bug reports.
