### ISSUE TITLE
web-ext requires Node >= 10

### ISSUE THREAD

**Issue by Vinnl** [mozilla/web-ext#1556]
### Is this a feature request or a bug?

Bug

### What is the current behavior?

When you try to install web-ext on Node 8, you receive an error that you need Node 10. The reason for this is the `addons-linter` dependency, which depends on `dispensary`, which [requires Node 10](https://github.com/mozilla/dispensary/blob/master/package.json#L10).

It doesn't really matter for me as I can use 10 just fine, but since the release notes explicitly mention bumping the required version to 8, you might want to fix this.

### What is the expected or desired behavior?

web-ext to be able to be installed in Node 8 just fine.

### Version information (for bug reports)

````
node --version && npm --version && web-ext --version
````

This was in CI, but using web-ext 3.0.0.

**Comment by rpl** [comment]
Hi @Vinnl, the "engines" specified in the package.json should be just an advice about which versions are officially supported, but it should prevent the installation to complete successfully, unless the user has explicitly configured npm to be more strict about it using the `engine-strict` config flag.

Which is the npm version and the npmrc you are using? (on the CI service, if you are only able to trigger this issue there).

**Comment by Vinnl** [comment]
Hi @rpl, this might be because I'm using Yarn. It has an [`--ignore-engines`](https://yarnpkg.com/en/docs/cli/install#toc-yarn-install-ignore-engines) flag, and [this bug report](https://github.com/yarnpkg/yarn/issues/638) seems to imply that if it is omitted, Yarn blocks installation of packages with incompatible engines.

You can see the error message here: https://gitlab.com/Flockademic/plaudit/-/jobs/176730003

**Comment by kumarharsh** [comment]
Maybe this can be closed? NodeJS 10 is now LTS, and NodeJS 8 will be dropped from maintenance in a few months: https://nodejs.org/en/about/releases/

**Comment by Vinnl** [comment]
@kumarharsh Well, I guess, if web-ext also updates it engine to refer to Node 10, and it's official policy to require that.

**Comment by kumar303** [comment]
Node 8 is about to enter its [end of life](https://github.com/nodejs/Release) so `web-ext` should officially move to Node 10 and begin running tests in Node 12.

**Comment by kumar303** [comment]
Support for Node 8 was dropped in https://github.com/mozilla/web-ext/pull/1731

@rpl (or whoever makes the changelog), I guess this commit won't show up because of the `chore:` prefix but someone will need to remember to list this as a breaking change 😀

**Comment by rpl** [comment]
@kumar303 eh, thanks for point it out that the related commit landed with the chore prefix, I haven't noticed it otherwise I would have asked @wagnerand to change it before merging the PR.

(As an additional way to remember that the next release may be going to break the backward compatibility for some of the users, one week ago I explicitly renamed the currently active project "next major release (4.0.0)" ;-))
