### ISSUE TITLE
web-ext 3.0 broken

### ISSUE THREAD

**Issue by jeffg2k** [mozilla/web-ext#1572]
Web-ext 2.9.3 worked fine, Web-ext 3.0.0 crashes.

> (function (exports, require, module, __filename, __dirname) { require("source-map-support").install(),module.exports=function(e){var t={};function n(i){if(t[i])return t[i].exports;var r=t[i]={i:i,l:!1,exports:{}};return e[i].call(r.exports,r,r.exports,n),r.l=!0,r.exports}return n.m=e,n.c=t,n.d=function(e,t,i){n.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:i})},n.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},n.t=function(e,t){if(1&t&&(e=n(e)),8&t)return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;var i=Object.create(null);if(n.r(i),Object.defineProperty(i,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var r in e)n.d(i,r,function(t){return e[t]}.bind(null,r));return i},n.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return n.d(t,"a",t),t},n.o=function(e,t){r
> SyntaxError: Unexpected token function
>     at createScript (vm.js:56:10)
>     at Object.runInThisContext (vm.js:97:10)
>     at Module._compile (module.js:542:28)
>     at Object.Module._extensions..js (module.js:579:10)
>     at Module.load (module.js:487:32)
>     at tryModuleLoad (module.js:446:12)
>     at Function.Module._load (module.js:438:3)
>     at Module.require (module.js:497:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/usr/local/lib/node_modules/web-ext/bin/web-ext:3:40)

MacOS 10.14.4

````
node --version && npm --version && web-ext --version
v6.10.1
6.9.0
````
Crashes just running --version..

**Comment by Rob--W** [comment]
`web-ext` 3.0.0 requires Node >= 8 (see release notes @ https://github.com/mozilla/web-ext/releases/tag/3.0.0 ). You should upgrade your from Node.js 6.10.1 to a more recent version.
