### ISSUE TITLE
Log web-ext version

### ISSUE THREAD

**Issue by kumar303** [mozilla/web-ext#161]
The program should start by logging the web-ext version. This will help when checking output in bug reports.

**Comment by eviljeff** [comment]
Can you provide more details on how a contributor would get started with this?

**Comment by kumar303** [comment]
The goal here is to make each web-ext command begin by logging the version. Output would look something like:

````
$ web-ext build
Version: 1.0.1
Your extension is ready: /path/to/extension.xpi
````

My comment [here](https://github.com/mozilla/web-ext/issues/142#issuecomment-204115191) about how to pass the version to the `Program` class also applies.

**Comment by Croydon** [comment]
For every command? I guess this could ending up being annoying spam in the console.

**Comment by kumar303** [comment]
I would be fine with only showing the version when run with ``--verbose``. In which case, it will depend on https://github.com/mozilla/web-ext/issues/33
