### ISSUE TITLE
Add parameter "--watch-file" to allow reloading after build is done

### ISSUE THREAD

**Issue by Juraj-Masiar** [mozilla/web-ext#1626]
### Is this a feature request or a bug?
Feature

### What is the current behavior?
`web-ext` will try to reload add-on too soon. If you are using some builder, this will often result in partially loaded add-on as your sources are only being build.
See the related bug that tries to solve the save problem with a delay parameter: https://github.com/mozilla/web-ext/issues/1573

### What is the expected or desired behavior?
As @Rob--W suggested: https://github.com/mozilla/web-ext/issues/1573#issuecomment-482526896 one solution would be to watch only single file, that would be modified last when build is done, for example some "build.version".
Even though it requires changes in your bundler, it's still easy to do and it's reactive - so it will save time and your CPU as `web-ext` will not try to reload not fully build add-on.

**Comment by rpl** [comment]
@Rob--W would you mind to add a comment with some pointers and details about what should be implemented? Thanks!

**Comment by Rob--W** [comment]
Currently, the watching feature (of `web-ext run`) watches a directory and all of the files within. I suggest to resolve this feature request by allowing the user to change the directory, from `sourceDir` to the location as given via the command line.

The directory ends up being used here:
https://github.com/mozilla/web-ext/blob/358a63ad6bf0f1ea8964daa5848ac25c3695ebe4/src/watcher.js#L46

Previously, I described how to read the commandline argument, and forward it all the way down. While the final details are different, the start should still be accurate.
https://github.com/mozilla/web-ext/issues/1573#issuecomment-496253303

**Comment by Shivansh2407** [comment]
Please I want to contribute to this , so can you explain me the issue and how to implement this

**Comment by Rob--W** [comment]
@Shivansh2407 See the first comment at the top of this issue, the explanation at https://github.com/mozilla/web-ext/issues/1626#issuecomment-535494888 and the link to the other comment from that comment.

**Comment by jezhou** [comment]
@Rob--W I would love to take a stab at this if it's up for grabs.

If I understand the problem correctly, bundlers like Webpack will produce code that won't be completely hot swapped into `web-ext` (too eager?). This change will add an option that will only hot swap / reload the extension if a single watched file is changed (which can be "touched" in whatever bundler/builder a developer is using after the builder is done, will probably require configuration on the developer's part).

If this understanding is good enough, I can try to whip up a PR and maybe ask you some questions along the way.

It seems like this solution would also indirectly solve these issues as well?

- #1102 
- #1137

**Comment by Juraj-Masiar** [comment]
Actually I would like to note something here.
When I was reporting this here, at that time I was using custom build script that was building my extension and during the process the extension was incorrectly reloaded.

However ever since I moved to Webpack, I have no longer this problem. The Webpack is swapping build sources only when the whole build is done and it's seems to be fast enough to not cause this issue anymore.

**Comment by Rob--W** [comment]
@jezhou Up for grabs. Your understanding is about correct; this feature request addresses the general problem of reloading too eagerly.
