### ISSUE TITLE
Add signing timeout option

### ISSUE THREAD

**Issue by kumar303** [mozilla/web-ext#163]
Add a command line option to configure the [timeout](https://github.com/mozilla/sign-addon/#programmatic-use) parameter of `signAddon()`. Maybe something like `web-ext sign --timeout ...`. This might be helpful for when AMO is overloaded which can still happen even though we've made improvements.

**Comment by eviljeff** [comment]
Can you provide more details on how a contributor would get started with this?

**Comment by kumar303** [comment]
The patch would need to:
1) Add an sub-option to the sign command, currently configured in https://github.com/mozilla/web-ext/blob/master/src/program.js#L138-L156
2) Adjust the call to `signAddon()` so it included `signAddon({timeout: options.timeout})`. This is in https://github.com/mozilla/web-ext/blob/master/src/cmd/sign.js#L33-L41

**Comment by sharang-d** [comment]
I'd like to take a stab at this.

This is what I have so far:
```diff
diff --git a/src/cmd/sign.js b/src/cmd/sign.js
index a583eb3..e623a32 100644
--- a/src/cmd/sign.js
+++ b/src/cmd/sign.js
@@ -12,7 +12,7 @@ const log = createLogger(__filename);
 
 export default function sign(
     {verbose, sourceDir, artifactsDir, apiKey, apiSecret,
-     apiUrlPrefix}: Object,
+     apiUrlPrefix, timeout}: Object,
     {build=defaultBuilder, signAddon=defaultAddonSigner,
      preValidatedManifest=null}: Object = {}): Promise {
 
@@ -38,6 +38,7 @@ export default function sign(
           apiKey,
           apiSecret,
           apiUrlPrefix,
+          timeout,
           verbose,
           xpiPath: buildResult.extensionPath,
           id: manifestData.applications.gecko.id,
diff --git a/src/program.js b/src/program.js
index c122628..40b076d 100644
--- a/src/program.js
+++ b/src/program.js
@@ -167,6 +167,11 @@ Example: $0 --help run.
         demand: true,
         type: 'string',
       },
+      'timeout' : {
+        describe: 'A length in millesconds to give up after if the add-on ' +
+                  'hasn\'t been signed',
+        type: 'number',
+      },
     })
     .command('run', 'Run the web extension', commands.run, {
       'firefox-binary': {
```
Do you think this would suffice?

I went through the required code in https://github.com/mozilla/sign-addon to understand what was needed.

I'm unsure in regards to how this should be tested manually. I would like to know how one would go about "signing" a web extension(and where I can find one). @kumar303 It would be great if you could point me in the right direction.

Also I see that a label "needs user docs" is attached. I'm guessing this means adding the info about this change to some kind of API doc but I can't find it!

**Comment by kumar303** [comment]
Hi, thanks for taking a look at this

> Do you think this would suffice?

The patch looks good so far! It will need a test but since we are trusting the `signAddon` interface, all you have to do is modify [this test](https://github.com/mozilla/web-ext/blob/master/tests/test-cmd/test.sign.js#L92) to assert that `timeout` is passed from the configuration to the `signAddon()` function.

> I'm unsure in regards to how this should be tested manually.

You just need to create access credentials, as [documented here](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/web-ext_command_reference#web-ext_sign), and then you can run `web-ext sign` on any add-on. The add-on can be just for testing (it will not be listed on addons.mozilla.org). You could also log into addons.mozilla.org and delete the add-ons that were created after you are finished.

An easy way to test this manually would be to do something like `web-ext sign --timeout 1 --api-key ...` which should time-out immediately and abort the signing attempt.

> Also I see that a label "needs user docs" is attached

You don't need to write docs for this patch. We will use this label to add the docs later.

**Comment by kumar303** [comment]
Thanks again for the patch. Do you have an MDN account? If so, could you document the new `--timeout` option? It should be straight forward to edit this section: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/web-ext_command_reference#web-ext_sign

**Comment by sharang-d** [comment]
Made the edit. Let me know how it looks.

**Comment by kumar303** [comment]
Looks perfect, thanks. I'll remove the tag now.
