### ISSUE TITLE
Force reloading required in web-ext run testing

### ISSUE THREAD

**Issue by DevinBayly** [mozilla/web-ext#1631]
### Is this a feature request or a bug?
This is a bug report.

### What is the current behavior?

In this bug I will start web-ext run from my extension root, and then in the browser navigate to a page that is laid out in the manifest permissions. Upon page load nothing is done to inject the content scripts into the page until I return to the terminal and hit ```r``` and then the extension shows up in the debugging sources and responds to the page. Many aspects of the extension that I'm interested in creating need to be up as soon as the page loads, and I recall this being the behavior until a couple of days ago. I was using 2.9.3 but now I'm on 3.0.0 and it still occurs.

source of extension

[extension.zip](https://github.com/mozilla/web-ext/files/3274094/extension.zip)

### What is the expected or desired behavior?

I would have thought that each page that matches the permissions laid out in the manifest would see the extension load in them automatically instead of just at the user request in the terminal. Perhaps this is an option that I missed recently.
### Version information (for bug reports)

* 67.0.1 (64-bit)
* Ubuntu 16.04
````
node --version && npm --version && web-ext --version
````
v9.2.0
6.9.0
3.0.0

**Comment by rpl** [comment]
we took a look to the attached extension and it doesn't declare its content scripts in the manifest but it is calling tabs.executeScript as soon as the background page is being started, which will try to execute a content script in the currently selected tab, which may not work for timing reasons (e.g. there may not be any tab yet that the extension can execute a script into, e.g. the tab may still be an about:blank one).
