### ISSUE TITLE
_locales folder names should have underscore, not dash.

### ISSUE THREAD

**Issue by losnappas** [mozilla/web-ext#1632]
### Is this a feature request or a bug?

Bug

### What is the current behavior?

`web-ext build` an extension with a localization for en-US throws errors. [The folder name is supposed to be "en_US"](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Internationalization#Providing_localized_strings_in__locales) but web-ext complains that it's not "en-US". 

### What is the expected or desired behavior?

Should not throw errors.

### Version information (for bug reports)

* **Firefox version**: 67
* **Your OS and version**: ubuntu 19.04
* Paste the output of these commands:

````
node --version && npm --version && web-ext --version
````
$ node --version && npm --version && web-ext --version
v10.15.2
6.9.0
3.0.0

**Comment by Rob--W** [comment]
Could you provide an example of a project that throws the reported error? Did you possibly put an invalid value in the `default_locale` field in manifest.json?

**Comment by losnappas** [comment]
```json
{
  "description": "test",
  "manifest_version": 2,
  "name": "test",
  "version": "0.3",
  "homepage_url": "https://www.exapmle.org",
  "default_locale": "en-US",

  "browser_action": {
	  "default_title": "test"
  },

 "permissions": [
    "activeTab",
    "menus",
    "<all_urls>"
  ]
}
```

then I have `_locales/en_US/messages.json`

From the internationalization page, I understood that this was how it is supposed to be. Is en-US an invalid value?

>Note that if the subtag includes a basic language plus a regional variant, then the language and variant are conventionally separated using a hyphen: for example, "en-US". However, in the directories under _locales, the separator must be an underscore: "en_US".

**Comment by Rob--W** [comment]
Thanks for the example. The directories must use underscores, but the `default_locale` field can apparently contain hyphens. I've submitted a PR to address the issue.
