### ISSUE TITLE
sign with --ignore-files argument causes "This command does not take any arguments" error

### ISSUE THREAD

**Issue by carlin-q-scott** [mozilla/web-ext#1641]
### Is this a feature request or a bug?
Bug

### What is the current behavior?

I get the following error when I try to supply the --ignore-files argument:
> This command does not take any arguments

### What is the expected or desired behavior?
I should be able to ignore files when signing.

### Version information (for bug reports)

* **Firefox version**: 67.0.4
* **Your OS and version**: Windows 10 1903
* **Shell version**: Powershell 5.1.18362.145
* Paste the output of these commands:

````
node --version; npm --version; web-ext --version 
v12.3.1
6.9.0
3.1.0
````

### Additional details
I did not have this issue with web-ext v3.0.0. In fact, I just downgraded and retried the same command without issue.

**Comment by Rob--W** [comment]
Could you provide the exact command that you're running, and local and global web-ext config files if any?

Also, how did you install `web-ext`? Is it globally installed, or a project-specific dependency referenced through `package.json`?

**Comment by carlin-q-scott** [comment]
I installed web-ext as a developer dependency in my package.json, and I'm not using web-ext config files.

The exact command I'm using can be found [here in my repo](https://github.com/carlin-q-scott/browser-media-players/commit/343f5b610fc506fba2ac2919026ad9d7c12ed1fc#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L34).
`web-ext sign --channel=unlisted --api-key ******* --api-secret ******* --ignore-files tests deploy docs data/pageMods.json icon425.png package* jsconfig.json`

I've since moved to using the "webExt" property in package.json instead and that works fine.

**Comment by Rob--W** [comment]
Did it work before, with web-ext 3.0.0 ?

`--ignore-files` does not work like that. Usage is: `-ignore-files tests --ignore-files deploy --ignore-files docs`, or short: `-i tests -i deploy -i docs`.

The documentation is misleading, because the example suggests that it should have been possible to use `--ignore-files tests deploy docs:

```
$ web-ext --help
...
  --ignore-files, -i   A list of glob patterns to define which files should be
                       ignored. (Example: --ignore-files=path/to/first.js
                       path/to/second.js "**/*.log")                     [array]
```

**Comment by carlin-q-scott** [comment]
@Rob--W Yes, it works perfectly with web-ext 3.0.0 and it supports a list of files to ignore; I've been using it like that for over a year. Why would the build and sign commands parse arguments differently?

**Comment by Rob--W** [comment]
Thanks for checking again. I investigated the bug and submitted a patch at #1652 to fix the issue.
