### ISSUE TITLE
--target / -t flag with an invalid value does not result in any meaningful error message

### ISSUE THREAD

**Issue by Rob--W** [mozilla/web-ext#1642]
### Is this a feature request or a bug?
Bug

### What is the current behavior?
When an unrecognized value is passed to the `--target` flag (anything besides `firefox-desktop` or `firefox-android`), `web-ext` starts up and exits immediately, without errors.

```
$ web-ext run -t someinvalidvalue
Running web extension from /tmp/testextension
The extension will reload if any source file changes
Press R to reload (and Ctrl-C to quit)
```

### What is the expected or desired behavior?
There should be a warning or error message when the 

### Version information (for bug reports)

* **Firefox version**: not relevant
* **Your OS and version**: not relevant
* Paste the output of these commands:

````
node --version && npm --version && web-ext --version
v11.15.0
6.9.0
3.0.0
````

**Comment by Rob--W** [comment]
This can easily be fixed by adding the `choices` array with the supported values (firefox-desktop, firefox-android) at https://github.com/mozilla/web-ext/blob/644188ae0142550e1c88b2d6aa14d62c854807c8/src/program.js#L444

**Comment by onlywicked** [comment]
Hello,
I would like to contribute to this project. So, can I take this issue?

**Comment by Rob--W** [comment]
@onlywicked That's quick! Sure, feel free to try and work on this issue. You can ask questions here, and open a pull request if you have something that you'd like to be reviewed.

Once you're able to fix the bug (following my previous suggestion) and manually verify the result, also add a unit test that passes an invalid target. You can put the test in https://github.com/mozilla/web-ext/blob/master/tests/unit/test-cmd/test.run.js

**Comment by onlywicked** [comment]
Thanks for your suggestion. I have sent a pull request.
Please have a look into it and guide me if there is an issue with it.
