### ISSUE TITLE
Urgent bug: Error: Validation took too long to complete

### ISSUE THREAD

**Issue by cr-nz** [mozilla/web-ext#1681]
### Is this a feature request or a bug?

Bug

### What is the current behavior?

```
Error: Validation took too long to complete; last status: {"guid":"firefox@mega.co.nz","active":false,"automated_signing":true,"url":"https://addons.mozilla.org/api/v3/addons/firefox@mega.co.nz/versions/3.68.21/uploads/8376e3f35a3c4181929f3ab7f7234501/","files":[],"passed_review":false,"pk":"8376e3f35a3c4181929f3ab7f7234501","processed":true,"reviewed":false,"valid":true,"validation_results":{"success":true,"compatibility_summary":{"warnings":0,"errors":0,"notices":0},"notices":5,"warnings":20,"errors":0,"messages":[{"message":"Permission not supported...
    at Timeout._onTimeout (web-ext/node_modules/sign-addon/dist/webpack:/src/amo-client.js:222:16)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
```

### What is the expected or desired behavior?

The extension should sign successfully. Instead I get the error above even after trying multiple times. It was working fine yesterday and I signed and validated 2-3 extensions. Then today it broke.

### Version information (for bug reports)

````
node --version && npm --version && web-ext --version

v6.3.0
3.10.3
Detached: b215d3d917c84eab023ac529e4d2154e7cd57b6e-b215d3d917c84eab023ac529e4d2154e7cd57b6e
````

This was a version that always worked even if unstable changes were put in the master branch.

I have also tried on the latest `web-ext` version and the same issue occurs.

Is the signing server experiencing issues? The code changes we added since yesterday are minimal (e.g. adding a CSS class) and shouldn't have caused our extension to take too long to sign now.

**Comment by cr-nz** [comment]
I will note that after uploading it to the Addons Mozilla site it was signed without issues. It seems like a server issue that started today with the web-ext command line signing tool.

**Comment by Rob--W** [comment]
Could you share an XPI that failed to be signed, and the closest older version that managed to be signed successfully?

**Comment by cr-nz** [comment]
Actually I have updated to the latest web-ext version and upgraded my NodeJS to v12.9.0 and npm to 6.10.2 (to fix the async error). Now it is working properly and signing the extension fine.

**Comment by sshahcodes** [comment]
Hi,
I am facing similar issue suddenly. It's same old codebase that never had this problem. Update has commented `console.log` only.
```
Error: Signing took too long to complete; last status: {"guid":"{97eeef94-56df-45cf-a7f1-76106bbd5ff9}","active":false,"automated_signing":true,"url":"https://addons.mozilla.org/api/v3/addons/%7B97eeef94-56df-45cf-a7f1-76106bbd5ff9%7D/versions/1.0.22/uploads/1bdcaae87f9144a58f721c7561f548c7/","files":[{"download_url":"https://addons.mozilla.org/api/v3/file/3522109/trasa-1.0.22-an+fx.xpi?src=api","hash":"sha256:f2ebc959531a325d793517f444fbbb1868e0081d1e44a93288efb43f56856163","signed":false}],"passed_review":false,"pk":"1bdcaae87f9144a58f721c7561f548...
    at Timeout.r [as _onTimeout] (/usr/lib/node_modules/web-ext/node_modules/sign-addon/dist/webpack:/src/amo-client.js:312:11)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
```
node --version && npm --version && web-ext --version
```
$ node --version && npm --version && web-ext --version
v12.16.1
6.13.4
4.1.0
```

**Comment by mtatarau90** [comment]
Hi Guys, did anyone find a fix for this bug ? 

Thanks
