### ISSUE TITLE
chromium extension-runner reloadAllExtensions should wait wssBroadcast to be processed by the connected clients 

### ISSUE THREAD

**Issue by rpl** [mozilla/web-ext#1686]
As a followup to #1392, the `chromium` extension-runner should wait the `"webExtReloadAllExtensions"` message (broadcasted from the websocket server part of the `chromium` extension runner) to have been received and handled by all the connected clients [1] (See https://github.com/mozilla/web-ext/pull/1392/files#r231533242).

[1]:where the connected client is the "extension manager extension" used to remotely control a chromium instance, in particular to reload the extension passed to the `web-ext run` command automatically when one of its file has been changed).

**Comment by ccarruitero** [comment]
I want to work on this.

@rpl, I think this can be solved by making the `wssBroadcast` an async function, so we can await in the `reloadAllExtensions`. What do you think?
