### ISSUE TITLE
web-ext should log errors and usage info on unknown command line interface options

### ISSUE THREAD

**Issue by rpl** [mozilla/web-ext#169]
STR:
- run web-ext with an unkown command line option:
  ```$ web-ext run --unknown-option```
- **expected behavior**: web-ext log an error message complaining that `--unknown-option` does not exist, print the usage info for the command and exit with a non-zero exit code
- **actual behavior**: the unknown cli option is ignored and no error logged

**Comment by kumar303** [comment]
I think [yargs.strict()](http://yargs.js.org/docs/#methods-strict) is all we need to solve this!

**Comment by sharang-d** [comment]
Tried that in #226 ..
Doesn't seem to help. Will probably take a closer look at this post #226.
In the meantime if anyone wants to take it up that is fine with me.

**Comment by kumar303** [comment]
The fix for this is
````diff
diff --git a/src/program.js b/src/program.js
index 55902fc..8bc7645 100644
--- a/src/program.js
+++ b/src/program.js
@@ -34,7 +34,7 @@ export class Program {
       if (!commandOptions) {
         return;
       }
-      return yargs.options(commandOptions);
+      return yargs.strict().options(commandOptions);
     });
     this.commands[name] = executor;
     return this;
````
but it would be great to also add an automated test for this, if possible.

**Comment by kumar303** [comment]
I filed https://github.com/yargs/yargs/issues/489 to make yargs more testable in-process

**Comment by kumar303** [comment]
It looks like we can use `.exitProcess(false)` or `.fail(customHandler)` to write tests for this. More details: https://github.com/yargs/yargs/issues/489
