### ISSUE TITLE
Enable "devtools.browserconsole.contentMessages" before running Firefox

### ISSUE THREAD

**Issue by M-Reimer** [mozilla/web-ext#1702]
### Is this a feature request or a bug?
Maybe both. The bug is that "console.log" no longer is visible in a browser console launched via "--bc" parameter. The feature request is that the mentioned pref should be set to "true" so "console.log" is visible again.

### What is the current behavior?
If I have "console.log" in my Addon, then these messages aren't shown in browser console.

I'm currently "working around" this "bug" in all my Addons:
https://github.com/M-Reimer/togglewebsitecolors/commit/b2a4b7130e8d72857e28935cd628b674cf529505

But I think this shouldn't be needed if "--bc" is on the command line. In this case the developer wants to see messages caused by his Addon.

### What is the expected or desired behavior?
Messages should be visible

### Version information (for bug reports)

* **Firefox version**: 69
* **Your OS and version**: Arch Linux (rolling release)
* Paste the output of these commands:

````
$ node --version && web-ext --version
v12.10.0
3.1.1

No "npm" installed on my system
````

**Comment by rbrishabh** [comment]
Hey @rpl, now that #1669 is almost landed, can I take this one up?

**Comment by rpl** [comment]
@rbrishabh sure thing, once the last round of changes needed on #1669 are completed, feel free to pick this one.

The default preferences that web-ext is setting in the Firefox profiles are managed by following js module: https://github.com/mozilla/web-ext/blob/master/src/firefox/preferences.js

Let me know if you need any additional pointers.

**Comment by rbrishabh** [comment]
@rpl! Alright, now that #1669 is done, I am looking into this!
