### ISSUE TITLE
--start-url option does not accept array anymore

### ISSUE THREAD

**Issue by rensbaardman** [mozilla/web-ext#1707]
### Is this a feature request or a bug?
bug

### What is the current behavior?
When running
```
web-ext run --start-url example.com foobar.com
```
it does not run with the two urls as start urls, but says
```
Run the extension

Options:
   [...]
  --start-url, -u, --url           Launch firefox at specified page      [array]
   [...]

This command does not take any arguments
```

Notice that the command options docs (still) specifies an array as argument to `--start-url`, suggesting this should be possible. (see [this line in the src](https://github.com/mozilla/web-ext/blob/961da0c27cea875484338fcb0801d10229672df1/src/program.js#L519))

### What is the expected or desired behavior?
Prior to v3.1.0 (I think), this worked as expected: executing the command would run the extension in Firefox, starting with the two (or more) urls as open tabs. 

The problem is probably the same regression as mentioned in https://github.com/mozilla/web-ext/pull/1652. There was also [a comment](https://github.com/mozilla/web-ext/pull/1652#pullrequestreview-261360878) explicitly mentioning this case. Note that the `[array]` specification in the cli options, contradicts [an earlier comment](https://github.com/mozilla/web-ext/pull/1652#issuecomment-510965920) that "The old behavior was not documented".

I suggest a similar fix as in that case, since disabling array support (requiring `--start-url example.com --start-url foobar.com`) would technically be a breaking change.

Else, the cli options man page should be changed (fine with me too if the solution would be too cumbersome to implement).

### Version information (for bug reports)

* **Firefox version**: 69.0
* **Your OS and version**: macOS 10.11.6
* Paste the output of these commands:

````
node --version && npm --version && web-ext --version
````
v10.16.0
6.11.3
3.1.1

**Comment by Rob--W** [comment]
`--start-url` / `-u` is documented to take only one parameter:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/web-ext_command_reference#--start-url

This is expected behavior, but I'm keeping the issue open until we have improved the output of `web-ext run --help`.

**Comment by rensbaardman** [comment]
I just came across https://github.com/mozilla/web-ext/issues/797, which makes a valid point: if you can only set multiple URLs by adding multiple flags, it is not possible to do so with an environment variable. So this requires the ability to pass an array.

I am willing to try come up with a PR (which depends on fixing this yargs issue first: https://github.com/yargs/yargs/issues/821), but I might need some guidance later on. I can then also update the MDN docs.

Does that work for you?

**Comment by Rob--W** [comment]
It's not clear what you're asking - are you going to fix the output of `--help`, or are you going to re-introduce support for multiple URLs in `--start-url`?

I have a very small preference for supporting exactly one value per `--start-url` / `-u` parameter, like this:

`web-ext run -u example.com -u example.com/page2`

.. but if `yargs` is fixed and we can fully rely on `yargs` for consistent behavior without too many hacks, then I wouldn't be against the following (previous behavior):

`web-ext run -u example.com example.com/page2`

**Comment by rensbaardman** [comment]
Sorry for the confusion. My proposal is to accept arrays, so the previous behaviour (your second example). This would allow setting multiple URLs via environment variables.

I will try to tackle the `yargs` issues first. Depending on whether that is successful / easy, I will come back here with either a solution that accepts arrays, or just improving the `--help` output. Is that okay?

**Comment by Rob--W** [comment]
Either approach is fine to me.

**Comment by Rob--W** [comment]
We're going to publish a major version bump, because Node 8 is almost EOL, and we want to bump the version requirement to Node 10+. This issue is one of the issues that may result in backwards-incompatible behavior, so if you plan to submit a PR, please do so.
