### ISSUE TITLE
'sign --channel=unlisted' fails when --id is set

### ISSUE THREAD

**Issue by Saphareas** [mozilla/web-ext#1737]
### Is this a feature request or a bug?
It's a bug (I think)

### What is the current behavior?
When running ```web-ext sign --channel=unlisted``` while the --id is set to an existing extension and the listed extension's version is newer (or equal) than the one submitting, the process fails with

 ```
Server response: Version already exists. Latest version is: x.x.x. (status: 409)
FAIL

o: The extension could not be signed
    at /usr/local/lib/node_modules/web-ext/dist/webpack:/src/cmd/sign.js:125:9
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at j.execute (/usr/local/lib/node_modules/web-ext/dist/webpack:/src/program.js:234:11)
```

### What is the expected or desired behavior?
The sign command should either ignore the --id or check the last unlisted version instead of the last listed one.

### Version information (for bug reports)

* **Firefox version**: 69.0.3 (64-Bit)
* **Your OS and version**: Pop!_OS 19.10
* Paste the output of these commands:

````
node --version && npm --version && web-ext --version
v12.2.0
6.10.0
3.2.0
````

Edit: I set the Api key and secret via env vars.

**Comment by diox** [comment]
AMO doesn't support using the same version number for both unlisted & listed versions, so that behavior is expected when you use the same version number. Do you get the same error with a different version number ?

**Comment by Saphareas** [comment]
Now that's something I didn't know.

> Do you get the same error with a different version number ?

No, with a different version (I appended 'u' for 'unlisted') there are no problems. So after all, everything works as expected.
