### ISSUE TITLE
web-ext lint JS_SYNTAX_ERROR when React JSX is used

### ISSUE THREAD

**Issue by MikkCZ** [mozilla/web-ext#1759]
### Is this a feature request or a bug?
bug

### What is the current behavior?

When React with JSX syntax is used in the project, `web-ext lint` reports JS_SYNTAX_ERROR for any file where JSX syntax is used.

### What is the expected or desired behavior?
`web-ext` should be able to handle JSX syntax the same way eslint can.

### Version information (for bug reports)

* **Your OS and version**: Fedora 30
* Paste the output of these commands:

````
node --version && npm --version && web-ext --version

v10.16.3
6.9.0
3.2.1
````

**Comment by kumar303** [comment]
This is working as intended. You cannot run a browser extension in Firefox or Chrome using React JSX syntax. You will need to use webpack (or the equivalent) to convert it to ECMAScript.

There is an example here of how to do it but the libraries are out of date: https://github.com/mdn/webextensions-examples/tree/f369ddc6421591c78d978bd9f4d7d23c5da77e2d/react-es6-popup
