### ISSUE TITLE
The Chromium launcher mutes audio by default

### ISSUE THREAD

**Issue by guihkx** [mozilla/web-ext#1774]
### Is this a feature request or a bug?
It depends... But I'll go with **request**.

### What is the current behavior?
The default launch flags for Chromium/Chrome currently include [`--mute-audio`](https://github.com/GoogleChrome/chrome-launcher/blob/v0.11.2/src/flags.ts#L22-L23) (which mutes the whole browser), but that flag [`is not filtered out by web-ext`](https://github.com/mozilla/web-ext/blob/3.2.1/src/extension-runners/chromium.js#L114-L115). 

### What is the expected or desired behavior?
Whilst I do agree that such flag might be useful for a lot of people, I believe that the default behavior shouldn't be to mute the entire browser, from a consistency standpoint, at least. That's because the Firefox launcher doesn't do that by default.

````
node --version && yarn --version && yarn web-ext --version
v13.2.0
1.21.0
3.2.1
````

**Comment by kumar303** [comment]
I'd call this a bug because it's surprising behavior. Thanks for filing.

**Comment by jezhou** [comment]
This seems easy enough – I'll be glad to give a shot at it if no ones claimed it yet 😄
