### ISSUE TITLE
Make Chromium not prompt the user to set it as the default browser

### ISSUE THREAD

**Issue by mariyan-borisov** [mozilla/web-ext#1781]
### Is this a feature request or a bug?
This is a feature request.

### What is the current behavior?
When starting Chromium using `web-ext run -t chromium` it checks whether it is the default browser and prompts the user to set it as one when it isn't.

### What is the expected or desired behavior?
Chromium should not prompt the user to set it as the default browser.

**Comment by mariyan-borisov** [comment]
The `--no-default-browser-check` command line flag can be used to achieve the desired behavior as follows:
`web-ext run -t chromium --arg=--no-default-browser-check`

**Comment by rpl** [comment]
@mariyan-borisov has kindly fixed the bug in the upstream package \o/

I've currently marked this as "state: blocked by upstream", we are going to fix it from the renovatebot PR (e.g. #1745).

**Comment by rpl** [comment]
Closing (fixed as part of #1865)
