### ISSUE TITLE
Don't log info about the built extension when signing

### ISSUE THREAD

**Issue by kumar303** [mozilla/web-ext#181]
When signing an extension, web-ext will first build the extension in a temp directory. When running in non-verbose mode, there is no reason to output information about this since it's an implementation detail. This *extension is ready* log line should be hidden when not running with `--verbose`:

````
$ web-ext sign --api-key ... --api-secret ...
Building web extension from /Users/kumar/dev/bookmarker-ext/moz-webext
Your web extension is ready: /var/folders/h7/rttdqkks7fl_txp9_rr4j4840000gn/T/tmp-web-ext-1114CJEXjz51BXXp/getting_started_example-1.2.25.xpi
Validating add-on [..........................................................................................................................................................................................................................................................]
Validation results: https://addons.mozilla.org/en-US/developers/upload/01f733ef20b443fcaa5973e6860d1326
Downloading signed files: 100%
Downloaded:
    ./web-ext-artifacts/getting_started_example-1.2.25-fx.xpi
SUCCESS
````

**Comment by wagnerand** [comment]
See https://wiki.mozilla.org/Add-ons/Contribute/AMO/Code if this is your first AMO bug you work on.

**Comment by wagnerand** [comment]
Mentor: @kumar303

**Comment by kumar303** [comment]
One thing that will be a little tricky about this bug is that the "extension is ready" message *should* show up for the `build` command but *should not* show up for the `sign` command.

Here is an example of how the `build` command output should look (this is how it currently looks):
````
$ web-ext build
Building web extension from /Users/kumar/dev/webextensions-examples/beastify
Your web extension is ready: /Users/kumar/dev/webextensions-examples/beastify/web-ext-artifacts/beastify-1.0.zip
````
The sign command's output should look just like how it is in the description of this issue but it *should not* include this line:
````
Your web extension is ready: /var/folders...
````
The `sign` command calls the `build` command internally because it needs to build an extension before it can sign it. I think the key here is to add a hint when calling the `build` function from the `sign` command, something like this:
````
build({sourceDir, artifactsDir: tmpDir.path()}, 
      {manifestData, showReadyMessage: false})
````
The hint would be `showReadyMessage: false`.

**Comment by saintsebastian** [comment]
Thanks for the clarification, I will start working on it.
