### ISSUE TITLE
ESLint dependency conflicts with existing ESLint in project

### ISSUE THREAD

**Issue by EvHaus** [mozilla/web-ext#1823]
### Is this a feature request or a bug?

Bug

### What is the current behavior?

When you add `web-ext` to an existing project via `npm install --save-dev web-ext` (as per README instructions), it can break ESLint code editor integration for that project if the project is in a monorepo. To set this up, your project will need to have the following directory structure:

- project/
    - package.json (contains `eslint@6.8.0` as a `devDependency`)
    - packages/
        - packageA/
            - someJavascriptFile.js
            - package.json (contains `web-ext` as a `devDependency`)
        - packageB/
            - someOtherJavascriptFile.js
    
This is a common directory structure for a monorepo using [Lerna](https://github.com/lerna/lerna) or [Yarn workspaces](https://yarnpkg.com/lang/en/docs/workspaces/). In this example, the idea is that both "packageA" and "packageB" projects are reusing the same ESLint configuration which is defined in the root of the project.

Unfortunately, when `projectA` now installs `web-ext` as a dependency, it brings along the `addons-linter` package for the ride, which inside of it has an old version of `eslint@5.16.0` as a dependency. This means that when developers open `someJavascriptFile.js` for edit in their code editor, the code editor will pick up the 5.15.0 version of ESLint that got injected into `packageA/node_modules` instead of the monorepo's version (in this example - 6.8.0). This happens because code editors will scan upwards from the selected file looking for the nearest `node_modules/eslint/.bin/eslint`.

### What is the expected or desired behavior?

The ideal behavior is that installing `web-ext` doesn't inject a custom version of `eslint` into your `node_modules`. However, I'm not sure this is possible without breaking the linting feature of `web-ext`.

I don't know what the solution here is, but I wanted to put it up for question as it caused some issues for my team. We got around this by manually editing the `package-lock.json` file in `projectA` to ensure that the `eslint` dependency is not installed at all. But this is a very hacky solution.

### Version information (for bug reports)

* **Firefox version**: N/A
* **Your OS and version**: N/A
* Paste the output of these commands:

````
node v10.17.0
npm 6.13.4
web-ext 4.0.0
````

**Comment by Rob--W** [comment]
The linter is a part of the tool, and we're probably not going to remove the dependency.

Would it be an option for you to use legacy bundling? Then the dependency tree won't be flattened, and the `eslint` dependency should not interfere with your project. Due to the duplication, the resulting `node_modules` directory will have a larger file size though . See https://docs.npm.red/misc/config#legacy-bundling

**Comment by EvHaus** [comment]
You're right. I think legacy bundling could be a possible solution, but it's definitely not ideal as it's not the "preferred npm way" moving forward.

I'll close this issue as I'm not sure there's anything actionable here, but maybe if others run into this in the future they can see it and suggest a possible workaround.
