### ISSUE TITLE
deterministic filenames

### ISSUE THREAD

**Issue by escapewindow** [mozilla/web-ext#1844]
Feature request: deterministic filenames

### What is the current behavior?

We create a `web-ext-artifacts/LOWERCASE_PACKAGE-VERSION.zip`

### What is the expected or desired behavior?

We are allowed to specify a name, e.g. with `--output <filename>`. This doesn't have to be the default behavior, but it avoids having to wrap the web-ext build with another command that renames it.

We're automating how we sign and ship XPIs. Having a deterministic name, without having to download `n` package.json files to determine what the version is, allows us to simplify our automation. Currently we have a hardcoded version [here](https://github.com/mozilla-extensions/xpi-manifest/blob/master/xpi-manifest.yml) that we have to bump every time the version bumps in package.json.

**Comment by Rob--W** [comment]
This has been requested before at #1335.
