### ISSUE TITLE
`web-ext build` should ignore the `artifacts-dir`.

### ISSUE THREAD

**Issue by bwinton** [mozilla/web-ext#186]
When I build my web-extension, it includes an empty directory (`web-ext-artifacts/`) where it put the previous build of the XPI. 
Since we know that's a place for the artifacts, we should probably not add it to the XPI.  (Alternatively, maybe we should skip all empty directories, in case people put stuff in their artifact directory, or build their XPIs into the root directory.)

``` sh
🌒  🕞  bwinton@15:22/reviewboard-collapse/ (master) $ web-ext build
Building web extension from /Users/bwinton/Programming/addons/WebExtensions/reviewboard-collapse
Your web extension is ready: /Users/bwinton/Programming/addons/WebExtensions/reviewboard-collapse/web-ext-artifacts/reviewboard_collapser-1.0.xpi
🌒  🕞  bwinton@15:23/reviewboard-collapse/ (master) $ unzip -l web-ext-artifacts/reviewboard_collapser-1.0.xpi
Archive:  web-ext-artifacts/reviewboard_collapser-1.0.xpi
  Length     Date   Time    Name
 --------    ----   ----    ----
        0  04-08-16 15:23   web-ext-artifacts/
    16725  04-08-16 15:23   LICENSE
     6056  04-08-16 15:23   icon.png
       97  04-08-16 15:23   README.md
     1638  04-08-16 15:23   content.js
      451  04-08-16 15:23   manifest.json
 --------                   -------
    24967                   6 files
🌒  🕞  bwinton@15:23/reviewboard-collapse/ (master) $
```

**Comment by kumar303** [comment]
I guess the empty dirs are harmless but it should be easy to fix. Ignoring any empty directory seems fine.

**Comment by wagnerand** [comment]
See https://wiki.mozilla.org/Add-ons/Contribute/AMO/Code if this is your first AMO bug you work on.

**Comment by wagnerand** [comment]
Mentor: @kumar303

**Comment by iamVP7** [comment]
I tried web-ext build with the latest source, I found even when I don't have the folder (web-ext-artifacts), I am getting the empty folder in .xpi

**Comment by kumar303** [comment]
Hi @iamVP7 -- how is the patch going? Let me know if you need additional help on it.

**Comment by kumar303** [comment]
Actually, this isn't such a good first bug because it involves making some architectural changes to [FileFilter](https://github.com/mozilla/web-ext/blob/master/src/cmd/build.js#L133).

This isn't very high priority because the problematic files *inside* `web-ext-artifacts` (such as other XPI files) are already ignored now.
