### ISSUE TITLE
Add support for Reference Browser in ADB discovery

### ISSUE THREAD

**Issue by jonalmeida** [mozilla/web-ext#1870]
### Is this a feature request or a bug?
Feature

### What is the current behavior?

[Reference Browser](https://github.com/mozilla-mobile/reference-browser/) is what many teams use to prototype mobile browser features. Adding support for webext debugging would make it easier.

### What is the expected or desired behavior?
To have 

### Version information (for bug reports)

n/a

**Comment by rpl** [comment]
Fixed in #1871
