### ISSUE TITLE
`web-ext run` cannot install a temporary add-on with FF Nightly (build >= 2020-04-14)

### ISSUE THREAD

**Issue by willdurand** [mozilla/web-ext#1884]
`web-ext run` cannot install a temporary add-on when we use it with FF Nightly (since yesterday).

The error message is:

```
$ ./bin/web-ext run --firefox "/Users/williamdurand/projects/mozilla/gecko/objdir-frontend-debug-artifact/dist/NightlyDebug.app/Contents/MacOS/firefox" -s ~/Downloads/web-extension-permission-example-master
Applying config file: ./package.json
Running web extension from /Users/williamdurand/Downloads/web-extension-permission-example-master
Use --verbose or open Tools > Web Developer > Browser Console to see logging

WebExtError: Temporary add-on installation is not supported in this version of Firefox (you need Firefox 49 or higher). For older Firefox versions, use --pre-install
    at FirefoxDesktopExtensionRunner.startFirefoxInstance (/Users/williamdurand/projects/mozilla/web-ext/dist/webpack:/src/extension-runners/firefox-desktop.js:278:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

```

I used `mozregression` to find the root cause of this error because it comes from some RDP/FF-related code (thanks for the suggestion @rpl). The error is caused by this patch: https://phabricator.services.mozilla.com/D70174

The `listTabs` method does not return global actors anymore and we cannot retrieve `addonsActor` (if I understand correctly). It looks like we should be using `getRoot` instead and I confirm that this sketch of patch fixes the issue locally:

```diff
diff --git a/src/firefox/remote.js b/src/firefox/remote.js
index 2a16e09..a67a5e0 100644
--- a/src/firefox/remote.js
+++ b/src/firefox/remote.js
@@ -90,7 +90,7 @@ export class RemoteFirefox {
     addonPath: string
   ): Promise<FirefoxRDPResponseAddon> {
     return new Promise((resolve, reject) => {
-      this.client.request('listTabs', (error, tabsResponse) => {
+      this.client.request('getRoot', (error, tabsResponse) => {
         if (error) {
           return reject(new WebExtError(
             `Remote Firefox: listTabs() error: ${error}`));
```

That being said, we need to guarantee backward compatibility so we have to make sure the `getRoot` method is (1) available and (2) return the `addonsActor` in all FF versions we support. In addition, we should have a more future-proof and robust solution so that it won't break again.

### Version information (for bug reports)

* **Firefox version**: `central/default`
* **Your OS and version**: MacOS 10.13.6
* Paste the output of these commands:

````
$ node --version && npm --version && web-ext --version
v13.4.0
6.13.4
4.1.0
````

**Comment by rpl** [comment]
Thanks Will for noticing and investigating this issue!
This is definitely something we should fix sooner rather than later, otherwise web-ext run wouldn't be usable on Nightly until we do that. In my opinion we should get this in the next minor release.

From a quick look on searchfox, it seems that getRoot has been introduced in Firefox 65 ([Bug 1485661](https://bugzilla.mozilla.org/1485661), which is way before the last ESR (68) and so if that is right we may just replace listTabs with getRoot without doing anything complicate to keep a bit of backward compatibility.

**Comment by rpl** [comment]
while discussing with @Rob--W about this, he did mention to me that he used `web-ext run` to track down regressions using mozregress and that is actually a good point. If it wouldn't make the fix too much complicate we could try to keep it backward compatible for versions older than 65.

**Comment by juliandescottes** [comment]
Hi! Sorry that the change broke webext, as said in the previous comments,`getRoot` is what should be used here. 

We should think about adding a small test in m-c to check that the APIs you use (getRoot & listAddons from what I could see) are still working (ideally with webext peers as blocking reviewers for any change on it)
