### ISSUE TITLE
Cannot load extensions on android build variants

### ISSUE THREAD

**Issue by jonalmeida** [mozilla/web-ext#1891]
This is a follow-up from this PR where we learnt that build variants aren't supposed: https://github.com/mozilla/web-ext/pull/1871#issuecomment-605400070
### Is this a feature request or a bug?
Bug

### What is the current behavior?

1. Install a local `debug` build of [Reference Browser](https://github.com/mozilla-mobile/reference-browser/); affects Fenix too.
2. Run the following command:
```
web-ext run -t firefox-android --android-device=<device ID here> --firefox-apk=org.mozilla.reference.browser.debug --firefox-apk-component=BrowserActivity
```
3. Observe.

### What is the expected or desired behavior?
You should be able to install your web extension.

### What is the actual behaviour?

You see the following output in your terminal:

```
Error: Activity class {org.mozilla.reference.browser.debug/org.mozilla.reference.browser.debug.BrowserActivity} does not exist.
    at /Users/jalmeida/src/web-ext/node_modules/adbkit/lib/adb/command/host-transport/startactivity.js:57:21
    at tryCatcher (/Users/jalmeida/src/web-ext/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/jalmeida/src/web-ext/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/Users/jalmeida/src/web-ext/node_modules/bluebird/js/main/promise.js:577:18)
    at Async._drainQueue (/Users/jalmeida/src/web-ext/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/Users/jalmeida/src/web-ext/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/jalmeida/src/web-ext/node_modules/bluebird/js/main/async.js:15:14)

```

### Version information (for bug reports)

* **Firefox version**: Desktop: 77.0a1 (2020-04-21) (64-bit), Android: GV 77.0.20200422093542
* **Your OS and version**: Mac OS 10.15.4 (19E287) / Android 10
* Paste the output of these commands:

````
node --version && npm --version && web-ext --version
````
v13.11.0
6.13.7
4.1.0

**Comment by Rob--W** [comment]
Thanks for filing.

Fixing this is relatively simple, see

https://github.com/mozilla/web-ext/pull/1871#issuecomment-610472381
(`component` there refers to https://github.com/mozilla/web-ext/pull/1871#issuecomment-605310726)

**Comment by rpl** [comment]
mentor: @Rob--W

**Comment by MikeM711** [comment]
Hi, is anyone working on this?

I have been prodding around the repo today, looks interesting! I was able to get this [minimalist extension](https://github.com/mozilla/web-ext/pull/1871#issuecomment-605348049) to work using a source installation of Web-ext in Firefox with an Android Emulator:

` web-ext run -t firefox-android --android-device=<device ID here> --firefox-apk=--firefox-apk=org.mozilla.firefox`

And, as expected, if we were to swap `org.mozilla.firefox` with `org.mozilla.reference.browser`, the Reference Browser (R-B?) is able to launch in Android, but the extension is not able to be built.

Looks like it gets stuck at ` Building web extension from <FILEPATH>`, and then eventually a timeout error, `WebExtError: Timeout while waiting for the Android Firefox Debugger Socket`

Would I be able to take this on?

**Comment by Rob--W** [comment]
@MikeM711 Have you enabled "Remote debugging via USB" in the Settings view of the Reference Browser?

**Comment by MikeM711** [comment]
@Rob--W Oh wow - you're right, it's good now

Currently going ahead and building a local `debug` build of the Reference Browser. Looks like I need the `android-components` and `application-services` repos along with the `reference-browser`, if I'm not mistaken?

**Comment by jonalmeida** [comment]
> @Rob--W Oh wow - you're right, it's good now
> 
> Currently going ahead and building a local `debug` build of the Reference Browser. Looks like I need the `android-components` and `application-services` repos along with the `reference-browser`, if I'm not mistaken? Will be fiddling around with it.
> 

You shouldn't need to build custom app services and android components for this. The pre-built dependencies should just work. If they do not, please file an issue and we'll fix it asap. 🙂

**Comment by MikeM711** [comment]
@jonalmeida Ah, I think I got it! Got the debug build of the Reference Browser to work. 🙂

Before I proceed, here are my findings, let me know what you think. Maybe the extra info is useful?

**Reference Browser Debug**

I am able to install my extension in the Reference Browser debug build:
`web-ext run -t firefox-android --android-device=<device ID here> --firefox-apk=org.mozilla.reference.browser.debug`

If I tack on `--firefox-apk-component=BrowserActivity`, I got the same `Error: Activity class` as the original post.

**Reference Browser**

I am able to install my extension in the Reference Browser:
`web-ext run -t firefox-android --android-device=<device ID here> --firefox-apk=org.mozilla.reference.browser`

If I tack on `--firefox-apk-component=BrowserActivity`, the extension will only install until I personally clicked the "Reference Browser" app. Quick question, is this the intended functionality? Tried to go through the web-ext and reference browser docs/source code to get some hints, but I'm not too sure.

**Firefox and Firefox Nightly**

Out of curiosity, I have also tested my extension using Firefox and Firefox Nightly (fennec_auora) and I got similar results to Reference Browser debug - I am able to install my extension with these browsers; however, tacking on the activity-alias (I believe that is what it is called?) `--firefox-apk-component=BrowserActivity`, I get that `Error: Activity class` error for both, like the Reference Browser debug.

What do you guys think?

**Comment by jonalmeida** [comment]
> If I tack on --firefox-apk-component=BrowserActivity, the extension will only install until I personally clicked the "Reference Browser" app. Quick question, is this the intended functionality? 

I would differ to Rob on this.

> however, tacking on the activity-alias (I believe that is what it is called?) `--firefox-apk-component=BrowserActivity`, I get that `Error: Activity class` error for both, like the Reference Browser debug.

Yes, this is the bug: using `--firefox-apk-component` when browser apps have an `activity-alias` causes an error.

**Comment by Rob--W** [comment]
> If I tack on `--firefox-apk-component=BrowserActivity`, the extension will only install until I personally clicked the "Reference Browser" app. Quick question, is this the intended functionality?

Nope. The intended behavior is that `web-ext run ...` launches the browser app, with the extension installed, without further steps (other than enabling debugging mode if needed).

**Comment by MikeM711** [comment]
I did a little more investigating today, hopefully I'm on the right track here.

https://github.com/mozilla/web-ext/blob/e60411282655cbb23426544b8b5658f435505394/src/util/adb.js#L277-L285

From the above `adbClient.startActivity()`, I found that if I hard-coded `component` into `component: 'org.mozilla.reference.browser.debug/.App'`, the Reference Browser debug instantly loads up (which is basically as if you are not providing an `activity-alias`, of course).

If I hard-coded `component: org.mozilla.reference.browser.debug/org.mozilla.reference.browser.BrowserActivity` , from https://github.com/mozilla/web-ext/pull/1871#issuecomment-605400070, the Reference Browser debug waits until the user manually launches the Reference Browser debug app.

**Quick Solution**

So I'm thinking we can solve the initial problem by sending in something like the following instead:
```javascript
component = `${apk}/${apkWithoutDebugNameIfAny}.${apkComponent}`
``` 
like the 2nd hard-code (works for non-debug browser cases too). One thing to note though, is if you were to use just the Reference Browser (no debug), simply ```${apk}/.${apkComponent}``` (the original way) should work for these non-debug cases - looks cleaner.

**Issue**

The issue is, of course, the current state of `BrowserActivity` does not launch the app browser, we have to manually open it.

**Some Findings**

I have also noticed that `.BrowserTestActivity` also instantly launches the Browser, like `/.App`. 

What I'm seeing is, in [AndroidManifest.xml](https://github.com/mozilla-mobile/reference-browser/blob/1a99279d874cc1a53d8740711c45a12531d1c879/app/src/main/AndroidManifest.xml) of the Reference Browser repo, the aliases that instantly fire have `<action android:name="android.intent.action.MAIN" />`.

**Solution Extended**

Do you think we should have `<action android:name="android.intent.action.MAIN" />` under the `<intent-filter>` of `.BrowserActivity` in the Reference Browser? I think this might make my "Quick Solution" work.

**Actions param**

I'm also noticing that the `action` param doesn't really do much for us in the above `adbClient.startActivity()`, if I'm not mistaken? Maybe my testing and extension just never needed it? It looks like it would force a "MAIN" action, but if I comment it out, I don't notice anything different.

**End**

Those are my thoughts so far. Hope I'm on the right track, and didn't make any weird calls, haha.

**Comment by MikeM711** [comment]
I think I may have a solution, let me know what you all think.

I was able to run the command in question by doing these few things:

**Step 1: Working BrowserActivity for debug**

https://github.com/mozilla/web-ext/blob/a58280d2c36ec7b0b8233984de238c0f24233aeb/src/util/adb.js#L274-L285

In the above code block, we can rewrite `apk` before the `component` line:

```javascript
apk = apk.replace('.debug', ''); // rewrite apk
const component = apkComponent ?
  `${apk}/.${apkComponent}` : `${apk}/.App`;
```

With this we can successfully run the original command in question, while retaining the ability to run other browsers.

**Testing**

I have successfully used the `/.App` Reference Browser, fennec_aurora, fenix and firefox; and I have also successfully used `BrowserActivity` for Reference Browser, and `HomeActivity` for fenix.

Quick question: would we ever have to worry about a new browser that includes "Debug" as a name? As an example a "Debug Browser" name: `org.mozilla.debug.browser`. If this is possible, I can make the `.replace()` line more specific.

**Step 2: Instant Launch**

Seeing how the intended behavior of `BrowserActivity` is to launch the browser app with the extension installed, I was able to successfully do that by inserting `<action android:name="android.intent.action.MAIN" />` between the `<intent-filter>` tags for `.BrowserActivity` in the Reference Browser repo, shown below:

https://github.com/mozilla-mobile/reference-browser/blob/1a99279d874cc1a53d8740711c45a12531d1c879/app/src/main/AndroidManifest.xml#L39-L48

To demonstrate, I hard-coded the `component` in the above code block to be,
```javascript
component:  'org.mozilla.reference.browser.debug/org.mozilla.reference.browser.BrowserActivity'
```

Passing the `org.mozilla.reference.browser.debug` APK in this setup will have the Reference Browser debug app launch with the extension installed.

**Step 2: Solution**

With that said, what are your thoughts on inserting `<action android:name="android.intent.action.MAIN" />` inside the Reference Browser repo for `.BrowserActivity`?

**Comment by jonalmeida** [comment]
`.debug` is not a stable variant type, it's defined by the app. For example, in Fenix there is another variant called [`performancetest`](https://github.com/mozilla-mobile/fenix/blob/9ce9fbc889c8f58a3a76a9d0a40ddb74da4993f9/app/build.gradle#L62).

**Comment by MikeM711** [comment]
Just installed `org.mozilla.fenix.performancetest`, I see. So the hard-coded answer to that one is `org.mozilla.fenix.performancetest/org.mozilla.fenix.` + `activity-alias`. I also see the `.nightly`, `.beta`, etc. build variants too.

Would it be ok to write down all of the package names of Mozilla browser builds and do a `.startsWith` check, on the incoming `apk`? Similar to what we do below:

https://github.com/mozilla/web-ext/blob/a58280d2c36ec7b0b8233984de238c0f24233aeb/src/util/adb.js#L120-L124

So the result will be

```javascript
const browserList = [
  'org.mozilla.fennec',
  'org.mozilla.fenix',
  'org.mozilla.geckoview',
  'org.mozilla.firefox',
  'org.mozilla.reference.browser',
];

let browserName;

for (const browser of browserList){
  if (apk.startsWith(browser)){
    browserName = browser;
    break;
  };
};

const component = apkComponent && browserName ?
    `${apk}/${browserName}.${apkComponent}` : `${apk}/.App`;
```

Just tested this with `web-ext run -t firefox-android --android-device=<device ID here> --firefox-apk=org.mozilla.reference.browser.debug --firefox-apk-component=BrowserActivity`

And with `web-ext run -t firefox-android --android-device=<device ID here> --firefox-apk=org.mozilla.fenix.performancetest --firefox-apk-component=HomeActivity`

Both launch their respective browsers with the extension installed.

**Comment by Rob--W** [comment]
@MikeM711 What would be the advantage of your proposal, over the following logic:

1. If `apkComponent` has a `.`, use  `${apk}/${apkComponent}`
2. Else if apkComponent is given, use current logic: `${apk}/.${apkComponent}`
3. Else use current fallback: `${apk}/.App`

This would solve the issue here, without requiring a hard-coded list of values. Usage example:

```
web-ext run -t firefox-android --android-device=<device ID here> --firefox-apk=org.mozilla.reference.browser.debug --firefox-apk-component=org.mozilla.reference.browser.BrowserActivity

And with web-ext run -t firefox-android --android-device=<device ID here> --firefox-apk=org.mozilla.fenix.performancetest --firefox-apk-component=org.mozilla.fenix.HomeActivity
```

**Comment by MikeM711** [comment]
@Rob--W Yeah I felt a little uneasy with that hard-coded list, you're right about trying to move away from it.

I like your idea. Nothing hard-coded. I typed it up and did some testing with it to get some thoughts down.

```javascript
let component;

if(!apkComponent) { // elminating undefined possibility
  component = `${apk}/.App`;
} else if (apkComponent.includes('.')) {
  component = `${apk}/${apkComponent}`;
} else if (apkComponent) {
  component = `${apk}/.${apkComponent}`;
} else { // fallback
  component = `${apk}/.App`;
}
```

I would say the advantage of my idea over the above logic is that the `--firefox-apk-component` is less verbose when it comes to using build variants.

In the above block, for example, I can run `apk=org.mozilla.fenix` and write `apk-component=HomeActivity` no problem (2nd "else if"). But, if I were to use a variant, such as `apk=org.mozilla.fenix.performancetest` I must write `apk-component=org.mozilla.fenix.HomeActivity` (1st "else if"). I feel that having to write `org.mozilla.fenix` twice inside the command may seem redundant? Would that be reasonable to suggest?

I'll be exploring this more in the meantime (nothing hard-coded), if this suggestion is not too nit-picky.

**Comment by Rob--W** [comment]
For non-debug builds, the following will be equivalent after my suggestion:
```
--apk-component=.HomeActivity
--apk-component=HomeActivity
```

For non-debug builds, the fully-qualified name could be a reasonable alternative.

I'm not completely against hardcoding some official builds, but only if the list is reliable.

With your startsWith-approach, "org.mozilla.fenix.nightly" would map to "org.mozilla.fenix.HomeActivity". Is that correct?

**Comment by MikeM711** [comment]
> For non-debug builds, the following will be equivalent after my suggestion:

Just tried it, interesting! `.HomeActivity` follows the `includes()` condition. I can see someone looking through the android manifest, noticing `.HomeActivity` and using that directly.

> With your startsWith-approach, "org.mozilla.fenix.nightly" would map to "org.mozilla.fenix.HomeActivity". Is that correct?

Yeah, if I say `--firefox-apk=org.mozilla.fenix.nightly --firefox-apk-component=HomeActivity`, the complete component will be `org.mozilla.fenix.nightly/org.mozilla.fenix.HomeActivity` which loads the fenix nightly browser (installed using google play) with the extension, just tested.

No apk-component gives: `org.mozilla.fenix.nightly/.App`

**Comment by Rob--W** [comment]
Let's implement my suggestion so that `web-ext run` always works even if the app is not on the hard-coded list.

I am willing to consider a hard-coded list for common/official app builds, but want to ask people who actually build those mobile apps to verify that the logic is sane. If there is any ambiguity, a hard-coded list will lead to confusion, which is what I'd like to avoid.

**Comment by MikeM711** [comment]
I agree with that - just created a PR.

Side note - What are your thoughts on adding 
```
<action android:name="android.intent.action.MAIN" />
``` 
between the `<intent-filter>` tags for `.BrowserActivity` in the Reference Browser repo?

https://github.com/mozilla-mobile/reference-browser/blob/1a99279d874cc1a53d8740711c45a12531d1c879/app/src/main/AndroidManifest.xml#L39-L48

I use that line to instantly launch my local `debug` of the Reference Browser for the `.BrowserActivity` component:

```
--firefox-apk-component=org.mozilla.reference.browser.BrowserActivity
```

**Comment by jonalmeida** [comment]
> I agree with that - just created a PR.
> 
> Side note - What are your thoughts on adding
> 
> ```
> <action android:name="android.intent.action.MAIN" />
> ```
> 
> between the `<intent-filter>` tags for `.BrowserActivity` in the Reference Browser repo?
> 
> https://github.com/mozilla-mobile/reference-browser/blob/1a99279d874cc1a53d8740711c45a12531d1c879/app/src/main/AndroidManifest.xml#L39-L48
> 
> I use that line to instantly launch my local `debug` of the Reference Browser for the `.BrowserActivity` component:
> 
> ```
> --firefox-apk-component=org.mozilla.reference.browser.BrowserActivity
> ```

You can only have one activity with the main action since it's the entry point for an app from the launcher. We keep it on the `.App` alias (which points to the `BrowserActivity`) for legacy reasons to avoid breaking older builds.
