### ISSUE TITLE
Prompt the user to turn on remote debugging on GeckoView-based Android browsers

### ISSUE THREAD

**Issue by jonalmeida** [mozilla/web-ext#1899]
### Is this a feature request or a bug?
feature request.. but maybe a UX bug?

### What is the current behavior?

1. Install a Firefox browser (Fenix, Reference Browser, etc.)
2. Do NOT turn USB debugging on.
3. Attempt to load a web extension.
4. Observe the verbose logging in your console:

```
artifacts-1588115774818/private_relay-1.3.0.xpi
[util/temp-dir.js][debug] Removing temporary directory: /var/folders/0j/nt95_fk10rs89j1nt5bgscgw0000gn/T/tmp-web-ext-7582362y8GW89PLr7
[util/adb.js][debug] Run adb shell command on 99181FFAZ003HC: ["cat","/proc/net/unix"]
[util/adb.js][debug] Run adb shell command on 99181FFAZ003HC: ["cat","/proc/net/unix"]
[util/adb.js][debug] Run adb shell command on 99181FFAZ003HC: ["cat","/proc/net/unix"]
[util/adb.js][debug] Run adb shell command on 99181FFAZ003HC: ["cat","/proc/net/unix"]
```
 - (Optional step), turn USB debugging on and observe the extension correctly installed.

### What is the expected or desired behavior?
 - The tool is trying to communicate to the browser but requires remote debugging to be enabled.
 - It should prompt the user after n-attempts saying something along the lines of, "Unable to connect, have you turned USB debugging on?"

### Version information (for bug reports)

This does **NOT affect Fennec Android browsers** for some reason; USB debugging on is not a requirement.

* **Firefox version**: Firefox Preview 4.2, Reference Browser 2020-04-14
* **Your OS and version**: Android
* Paste the output of these commands:

````
node --version && npm --version && web-ext --version
````
v13.11.0
6.13.7
4.2.0

**Comment by rpl** [comment]
Hi @jonalmeida 
web-ext should already be prompting the user to enable remote debugging even before trying to connect to the remote browser instance:
https://github.com/mozilla/web-ext/blob/8c88b5324a61bfe4deee5eb3edbc07bd3352ab92/src/extension-runners/firefox-android.js#L566-L568

is that not happening for you?

**Comment by jonalmeida** [comment]
No, I haven't see this in my usage so far.

**Comment by rpl** [comment]
> No, I haven't see this in my usage so far.

@jonalmeida would you mind to double-check again and search for it in your logs?

I did just try locally and the message is definitely there as expected, here is what I see on my system:

```
$ ./bin/web-ext run -t firefox-android -s ~/.../borderify --android-device MYDEVICEID --firefox-apk org.mozilla.fenix.nightly

Applying config file: ./package.json
Running web extension from /.../borderify
Selected ADB device: MYDEVICEID
Stopping existing instances of org.mozilla.fenix.nightly...
Starting org.mozilla.fenix.nightly...

Waiting for org.mozilla.fenix.nightly Remote Debugging Server...
Make sure to enable "Remote Debugging via USB" from Settings -> Developer Tools if it is not yet enabled.

Building web extension from /.../borderify
```

My guess is that you missed it while running web-ext in verbose mode and an higher amount of logs may have made it less visible.

**Comment by jonalmeida** [comment]
You're right! That line was hidden from the `--verbose` logging so all I was seeing is a constant attempt to read from adb.

@rpl I'll close this if that's the expected result.
