### ISSUE TITLE
Create official documentation

### ISSUE THREAD

**Issue by kumar303** [mozilla/web-ext#19]
Document how to use the web-ext command. This will probably live on MDN because we'd want contributors to edit it easily.

**Comment by yash14123** [comment]
I would like to work on this. 
Please assign me the task.

**Comment by kumar303** [comment]
Hey yash, that would be a tremendous help, thank you. Are you familiar with editing [MDN](https://developer.mozilla.org/en-US/)? It's just like a wiki so it's pretty easy but it has some quirks to it. The documentation will live there but we haven't decided where it should go yet.

**Comment by yash14123** [comment]
Sure. I can start with it till then ?

**Comment by kumar303** [comment]
Sounds great. I made a [stub page](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/web-ext) so feel free to start editing it.

The approach I like for documentation is to present it in two ways:
1. Tell a story for what/why/how the developer would want to use this tool
2. Provide a well indexed reference of documentation topics for developers who are already familiar with number 1.

You can look at the [jpm docs](https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/jpm) for ideas but it doesn't need to follow that format exactly.

**Comment by kumar303** [comment]
Let me know if you run into any trouble getting started with this on MDN.

**Comment by kumar303** [comment]
I started labeling all the completed user features that need to be documented: https://github.com/mozilla/web-ext/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+label%3A%22needs+user+docs%22

**Comment by kumar303** [comment]
@theaverageguy thanks for your interest in the project! Sorry if you were having trouble with MDN (profile creation is still disabled). 

We have kicked off the documentation so I'm closing this issue. There are still lots more docs to write. See https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Getting_started_with_web-ext
