### ISSUE TITLE
Memory leak with each reload

### ISSUE THREAD

**Issue by Juraj-Masiar** [mozilla/web-ext#1910]
### Is this a feature request or a bug?
Bug

### What is the current behavior?
Each extension reload consumes about 100MB of memory.
I'm developing for a few hours today and my Firefox with 5 tabs now takes 8 GB of RAM!
My new extension is small, but it's using Vue, Vuetify and some other libraries so it's a bit heavy. My other extensions takes only about 20MB of RAM with each reload.
I'm executing web-ext using:
```
web-ext run --firefox=firefoxdeveloperedition --pref=browser.ctrlTab.recentlyUsedOrder=false --pref=signon.rememberSignons=true --start-url "about:devtools-toolbox?type=extension&id=admin@fastaddons.com_PrivateNotes" --start-url about:debugging#/runtime/this-firefox
```
I'm not sure if this was always the case or I didn't noticed it before (because the leak is smaller for my other extensions and I have a lot of system memory).

### What is the expected or desired behavior?
Smaller memory leak? :)

### Version information (for bug reports)

* **Firefox version**: 77.0b7 (64-bit)
* **Your OS and version**: Win 10 1909
* Paste the output of these commands:

````
node --version && npm --version && web-ext --version
v14.0.0
6.14.2
4.2.0
````

**Comment by Rob--W** [comment]
Could you attach the smallest extension that you can create that reproduces this problem?
That would make it easier for us to investigate this bug.

**Comment by Juraj-Masiar** [comment]
Okok, steps to reproduce:
1) load any of your extensions (bigger extension === bigger leak) using web-ext
1) wait some time and check memory usage
1) focus the console window where it runs and press "R" 10 times (to reload extension 10 times)
1) wait some time and check memory usage

Please let me know if you are not able to reproduce.

**Comment by Rob--W** [comment]
I tested with Firefox 77.0b6, web-ext 4.2.0, Linux:

1. Created an extension with an empty content script, a 10 MB background script consisting of `var x = "x (repeated 20M x)";`
2. Started Firefox with the extension with `web-ext run -f beta`
3. Open the system's task manager and/or `about:performance` to monitor memory usage.
4. Press `R` repeatedly

I didn't see any noticeable change in memory usage.
Please try to reduce the problem to a reasonably small test case that can be reproduced.

**Comment by Juraj-Masiar** [comment]
I've send you my source code to your email, I hope it's fine.
All you need to do is extract it, cd into "firefox_dev" folder and execute:
```
web-ext run --firefox=firefoxdeveloperedition --pref=browser.ctrlTab.recentlyUsedOrder=false --pref=signon.rememberSignons=true --start-url "about:devtools-toolbox?type=extension&id=admin@fastaddons.com_PrivateNotes" --start-url about:debugging#/runtime/this-firefox
```
I hope this helps.

**Comment by Rob--W** [comment]
After reloading with the extension that you mailed I see a spike in memory usage, but soon after that it drops.

I monitored memory usage using an external tool (ksysguard),

I also used `about:memory` to measure the memory usage (Press "Minimize memory usage" to force a feel GC and CC to see if there is a true memory leak).

How did you determine that there was a memory leak?

**Comment by Juraj-Masiar** [comment]
Interesting - I do see the spike in memory usage (like 300MB) and then it goes down (by 200MB) leaving 100MB lost. And there is no limit, currently my development instance of Firefox takes 2.8GB (new instance starts on 0.4GB) and executing GC, CC and Minimize memory usage did nothing.

HA - I found the problem - it's the inspect tab, once it's closed, it will release all the memory:
900MB when started
1600MB after 10 reloads
2600MB another 10 reloads
3700MB another 10 reloads
1100MB after closing `about:devtools-toolbox?type=extension&id=admin%40fastaddons.com_PrivateNotes` tab

Also, this is not really related to `web-ext`.
I should have investigated this deeper in the beginning. I'm sorry for wasting your time :(, I've got too angry when my PC run out of memory and I saw 8GB in my testing FF.

**Comment by Rob--W** [comment]
> HA - I found the problem - it's the inspect tab, once it's closed, it will release all the memory:

Sounds familiar. I have the same issue if I open the global JS console or the Browser Toolbox and then forget to close it. When I do finally close it, Firefox is frozen for a short while (probably busy trying to clean up garbage) and then I got some memory back.
