### ISSUE TITLE
web-ext run fails on Firefox 77.0.1 Ubuntu due to listTabs returning falsey value

### ISSUE THREAD

**Issue by GrayedFox** [mozilla/web-ext#1921]
### Is this a feature request or a bug?
Bug

### What is the current behavior?

`web-ext run` fails to start firefox and reports "Temporary addon installation is not supported in this version of Firefox..." despite the fact that `firefox -v` reports current, up to date version.

Running with verbose logging revealed the following:

```
[firefox/remote.js][debug] Connecting to Firefox on port 6005
[firefox/index.js][debug] Firefox stdout: Started devtools server on 6005
[firefox/remote.js][debug] Retrying Firefox (4); connection error: Error: connect ECONNREFUSED 127.0.0.1:6005
[firefox/remote.js][debug] Connecting to Firefox on port 6005
[firefox/remote.js][debug] Connected to the remote Firefox debugger on port 6005
[firefox/remote.js][debug] listTabs returned a falsey addonsActor: undefined
[extension-runners/firefox-desktop.js][debug] Caught: c: This is an older version of Firefox that does not provide an add-ons actor for remote installation. Try Firefox 49 or higher.
[program.js][error] 
o: Temporary add-on installation is not supported in this version of Firefox (you need Firefox 49 or higher). For older Firefox versions, use --pre-install
    at c.sourceDir [as startFirefoxInstance] (/home/grayedfox/.nvm/versions/node/v10.16.3/lib/node_modules/web-ext/dist/webpack:/src/extension-runners/firefox-desktop.js:274:51)
    at process._tickCallback (internal/process/next_tick.js:68:7)

[program.js][debug] Command executed: run
```

I believe this could be a regression and have a similar or identical root cause as [this issue](https://gihub.com/mozilla/web-ext/issues/1884).

### What is the expected or desired behavior?

Firefox is launched by web-ext as normal

### Version information (for bug reports)

* **Firefox version**: 77.0.1
* **Your OS and version**: Ubuntu 18.04.4 LTS
* Paste the output of these commands:

````
node --version && npm --version && web-ext --version
v10.16.3
6.14.5
3.1.1
````

**Comment by GrayedFox** [comment]
Workaround: add the following construct to your manifest.json
```
  "applications": {
    "gecko": {
      "id": "someon@email.com"
    }
  }
```

And launch web-ext with the `--pre-install` flag.

**Comment by Rob--W** [comment]
Same root cause, not a regression. You're using an old version of `web-ext`. Update to the latest version (4.2.0 or newer - https://github.com/mozilla/web-ext/releases/tag/4.2.0 ) to resolve your issue.

**Comment by GrayedFox** [comment]
Strange, I couldn't update my globally installed web-ext the usual way - only by uninstalling it completely did npm correctly pickup the 4.2 version.

Cheers.

**Comment by Rob--W** [comment]
To install the latest version, use `npm install web-ext@latest`
