### ISSUE TITLE
 Support for android build variants without requiring a fully qualified value in the `--apk-component` flag

### ISSUE THREAD

**Issue by MikeM711** [mozilla/web-ext#1935]
Relevant discussion: https://github.com/mozilla/web-ext/issues/1891#issuecomment-632423453 and https://github.com/mozilla/web-ext/pull/1918#issuecomment-644250208.

### Is this a feature request or a bug?
Feature

### What is the current behavior?

In order to run an android build variant with an `apkComponent`, we need to pass in a fully qualified value in the `--apk-component` flag.

For example, the below command will successfully install an extension on the `performancetest` build of [Fenix](https://github.com/mozilla-mobile/fenix/) using the `HomeActivity` component.

```
web-ext run -t firefox-android --android-device=<device ID here> --firefox-apk=org.mozilla.fenix.performancetest --firefox-apk-component=org.mozilla.fenix.HomeActivity
```

### What is the expected or desired behavior?

The desired behavior would be having a successful install by requiring a shorter value in the `--apk-component` flag. Using the above command as an example, the below command would be its equivalent.
```
web-ext run -t firefox-android --android-device=<device ID here> --firefox-apk=org.mozilla.fenix.performancetest --firefox-apk-component=HomeActivity
```

### Version information (for bug reports)

* **Firefox version**: Desktop: 77.01.1 (64-bit), Android: 68.8.0
* **Your OS and version**: Mac: 10.13.3, Android 10
* Paste the output of these commands:

````
node --version && npm --version && web-ext --version
````

v12.16.3
6.14.4
master-d61d94cbcf4834ec7613e80e51fc655dce06275c

**Comment by MikeM711** [comment]
@Rob--W Would you like to have a hardcoded list outside of `adb.js` or keep it inside the file? 

Originally I was thinking right inside the `src` directory, in case we would need to reuse the list somewhere else in the future.

**Comment by Rob--W** [comment]
Since it's not really related to ADB, a separate file, e.g. `src/firefox/package-identifiers.js` sounds good to me.

**Comment by MikeM711** [comment]
I have everything set up, just have a quick question:

The `test.adb.js` file uses `geckoview_example` as an android build to test with. I can get the tests and everything working by sticking the `geckoview_example` in the list of browsers. Is this okay to do? 

The good thing is that the application stops you from using packages that aren't installed, before it touches the list to begin with.

I can post a PR if that makes the explanation easier.

**Comment by Rob--W** [comment]
I just checked, and `web-ext` does support geckoview_example, after enabling Remote Debugging via the app:

```
web-ext run -t firefox-android --android-device emulator-5554 --firefox-apk=org.mozilla.geckoview_example --firefox-apk-component=GeckoViewActivity
```

I'm not entirely sure what you mean without the PR, but if the added item / list is compatible with how geckoview_example actually works, then it's fine to add it.

**Comment by MikeM711** [comment]
Oh wow, I thought geckoview_example was just a placeholder, whoops - I see it is an actual build.

Just made the PR.
