### ISSUE TITLE
Fails to install extension on the new Nightly for Android

### ISSUE THREAD

**Issue by ghostwords** [mozilla/web-ext#1949]
### Is this a feature request or a bug?
Bug

### What is the current behavior?

Running the following command to open our extension on Firefox Nightly launches Nightly but fails to load the extension:

`./node_modules/.bin/web-ext run -s src/ --target firefox-android --adb-bin /opt/Android/Sdk/platform-tools/adb --android-device XXX --firefox-apk org.mozilla.fenix --verbose`

Specifically, `web-ext` gets stuck repeatedly running an adb shell command that queries `/proc/net/unix`:
```
...
[cmd/build.js][debug] Manifest declared default_locale, localizing extension name
[extension-runners/firefox-android.js][debug] Uploading privacy_badger-2020.6.29 on the android device
[util/adb.js][debug] Pushing /tmp/tmp-web-ext-19598yxp3tz1jGdPO/privacy_badger-2020.6.29.zip to /sdcard/web-ext-artifacts-1594229787246/privacy_badger-2020.6.29.xpi on XXX
[extension-runners/firefox-android.js][debug] Upload completed: /sdcard/web-ext-artifacts-1594229787246/privacy_badger-2020.6.29.xpi
[util/temp-dir.js][debug] Removing temporary directory: /tmp/tmp-web-ext-19598yxp3tz1jGdPO
[util/adb.js][debug] Run adb shell command on XXX: ["cat","/proc/net/unix"]
[util/adb.js][debug] Run adb shell command on XXX: ["cat","/proc/net/unix"]
[util/adb.js][debug] Run adb shell command on XXX: ["cat","/proc/net/unix"]
...
```

Substituting `org.mozilla.firefox` for `--firefox-apk` successfully launches Firefox with the extension installed. Similarly, this worked with the `org.mozilla.fenix.nightly` APK, but stopped working when Nightly switched codebases a few days ago (?).

### Versions
Today's Firefox Nightly for Android (Nightly 200708 06:05)
web-ext 4.3.0

**Comment by Rob--W** [comment]
I'm still seeing `@org.mozilla.fenix.nightly/firefox-debugger-socket` in the output of `cat /proc/net/unix`.

Did you inadvertently disable "Remote debugging via USB"?

**Comment by ghostwords** [comment]
I don't think I did ... Why would launching the extension with the `org.mozilla.firefox` APK succeed immediately before or after the failed attempt to launch with `org.mozilla.fenix`?

**Comment by ghostwords** [comment]
To hopefully clarify, I used to test on Nightly Preview (`org.mozilla.fenix.nightly`) successfully. Then sometime recently Nightly Preview got updated to say that it's now deprecated and I should switch to Nightly.

`web-ext` without `--firefox-apk` helpfully informed me Nightly is `org.mozilla.fenix`. However, launching for `org.mozilla.fenix` gets stuck as per my original report above.

Launching for stable Firefox (`org.mozilla.firefox`) still works.

**Comment by Rob--W** [comment]
You had probably enabled remote debugging for `org.mozilla.firefox`.

> I don't think I did

It is off by default, so if you have a fresh install, remote debugging is going to be disabled by default. Please double-check your settings to see if it is enabled.

**Comment by ghostwords** [comment]
That was it, thank you for your help!

May I suggest this would be a good spot for `web-ext` to detect that remote debugging is disabled in the Firefox app and let the user know how to enable it?

Also, I first tried going to `about:debugging` to enable remote debugging. It doesn't seem to exist on Android, and there was no hint to visit Settings instead.

Then, when I went online to look up where the remote debugging setting lives on Android, I came across https://extensionworkshop.com/documentation/develop/developing-extensions-for-firefox-for-android/#debug-your-extension which points to a [broken link](https://developer.mozilla.org/docs/Tools/Remote_Debugging/Debugging_Firefox_for_Android_with_WebIDE#Enable_remote_debugging_in_Firefox_for_Android) for how to set up Firefox remote debugging over USB.

**Comment by Rob--W** [comment]
Looks like we will need to update that page for Android debugging, thanks. --> https://github.com/mozilla/extension-workshop

`web-ext` does already suggests to enable debugging: https://github.com/mozilla/web-ext/blob/d61d94cbcf4834ec7613e80e51fc655dce06275c/src/util/adb.js#L305-L316
Did the message not appear?

**Comment by ghostwords** [comment]
>Did the message not appear?

I guess I didn't wait long enough. Kept seeing `[util/adb.js][debug] Run adb shell command on XXX: ["cat","/proc/net/unix"]` over and over, didn't seem like it was going anywhere.

Had I seen `Timeout while waiting for the Android Firefox Debugger Socket`, that would have been something for me to look up, so helpful that way (had I waited long enough), yes, but I don't think this message makes it clear I need to go and enable debugging inside the Firefox app itself.

This is just some usability feedback based on my experience.

**Comment by Rob--W** [comment]
We can definitely tweak the duration and/or the message. You are not the first to be surprised by it.

**Comment by Rob--W** [comment]
Closing this in favor of #1969 to address the visibility of the instruction.
