### ISSUE TITLE
Temporary profile directory (without `--keep-profile-changes`) is not removed

### ISSUE THREAD

**Issue by Rob--W** [mozilla/web-ext#1957]
### Is this a feature request or a bug?
Bug

### What is the current behavior?
When `web-ext run` is executed, a temporary profile directory is created in `/tmp`.
Upon quitting Firefox, the directory is still there.

### What is the expected or desired behavior?
The directory should be removed upon exiting from `web-ext`.

### Version information (for bug reports)

web-ext 4.2.0 on Linux - issue independent of node/Firefox version.

**Comment by rpl** [comment]
@Rob--W I can't reproduce this issue (I tried on nodejs v12.16.3 and web-ext 4.2.0 and the current master), there may be something missing in the STR that could allow me to reproduce it if this issue can be reproduced consistently for you.

**Comment by Rob--W** [comment]
Can't reproduce either. I guess that I had too many `web-ext` instances around that generated profiles.
