### ISSUE TITLE
Show addons-linter version for `web-ext --version`

### ISSUE THREAD

**Issue by wagnerand** [mozilla/web-ext#1958]
### Is this a feature request or a bug?

Feature request

### What is the current behavior?

```
% web-ext --version
4.3.0
```

### What is the expected or desired behavior?

```
% web-ext --version
web-ext 4.3.0
addons-linter 2.0.1
```

**Comment by Rob--W** [comment]
Although not directly supported by `web-ext`, you can query the version as follows:

```
$ npm version web-ext | grep lint
addons-linter: 1.26.0
```

Or look it up online via package.json (replace 4.3.0 if needed, Ctrl-F `addons-linter`):

https://github.com/mozilla/web-ext/blob/4.3.0/package.json

Would this address your needs?

**Comment by wagnerand** [comment]
I know of the workarounds, but that information would make it easier to follow up on issue reports.

**Comment by rpl** [comment]
@wagnerand web-ext is currently using exact versions for all its dependencies and so in bug reports we can deduce which was the exact addons-linter version based on the web-ext version reported.

I'm not totally against this but I was wondering if there is any use case where what I described above isn't enough and explicitly state the version would be better.

**Comment by rpl** [comment]
We discussed this in the triage meeting and we (Rob, Will and I) agreed to wontfix this issue for the reason described in my previous comment.

Feel free to re-open if there is any use case that wouldn't be covered and would require this change.
