### ISSUE TITLE
`firefoxdeveloperedition` alias resolves surprisingly on macOS

### ISSUE THREAD

**Issue by watters** [mozilla/web-ext#1960]
### Is this a feature request or a bug?

A bug.

### What is the current behavior?

Using the `firefoxdeveloperedition` alias for the `-f` option results in an attempt to launch a binary within `/Applications/FirefoxDeveloperEdition.app` rather than `/Applications/Firefox Developer Edition.app`, which fails (error below).

It looks like `web-ext` delegates alias resolution to [`node-fx-runner`](https://github.com/mozilla-jetpack/node-fx-runner). I have filed [a corresponding issue](https://github.com/mozilla-jetpack/node-fx-runner/issues/47) against `node-fx-runner`, but thought it was worth noting here as well because the alias is explicitly documented by `web-ext`.

As noted in the `node-fx-runner` issue, there are a couple of ways it attempts to resolve this alias, and they all appear to fail. I've worked around it, but it may be worth fixing OR at least removing from the documented set of options. I'm happy to do the work in `web-ext` or `node-fx-runner`.

#### Reproduction

Install _Firefox Developer Edition_ from the official download location on macOS.

Command: 

`web-ext -f firefoxdeveloperedition run`

Output:
```
Running web extension from /Users/watters/Dropbox/code/birdcage/dist
Error: spawn /Applications/FirefoxDeveloperEdition.app/Contents/MacOS/firefox-bin ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```
### What is the expected or desired behavior?

The expected behavior is that _Firefox Developer Edition_ would be launched.

### Version information (for bug reports)

* **Firefox Developer Edition 79.0b7 (64-bit)**:
* **macOS Catalina Version 10.15.5**:
* Paste the output of these commands:

```
node --version && npm --version && web-ext --version
```

```
v12.17.0
6.14.5
4.3.0
````

**Comment by Rob--W** [comment]
It would be nice to fix this with the next minor release, but if we don't have a minor release the major version would be good too.
