### ISSUE TITLE
Signing fails with "Signing took too long to complete" but also succeeds

### ISSUE THREAD

**Issue by EvHaus** [mozilla/web-ext#1984]
### Is this a feature request or a bug?

Bug

### What is the current behavior?

When running the `webExt.cmd.sign({...})` command, we're seeing an intermittent behavior where the response comes back with a "Signing took too long to complete" error, but the signing also succeeds and downloads the signed extension.

The code being executed is:

```js
const response = await webExt.cmd.sign({
      apiKey: FIREFOX_ADDON_MANAGER_KEY,
      apiSecret: FIREFOX_ADDON_MANAGER_SECRET,
      artifactsDir: SIGNED_EXTENSION_DIR,
      sourceDir: UNSIGNED_EXTENSION_DIR,
      timeout: 300000,
});

if (response.errorDetails) throw new Error(response.errorDetails);
```

When this code runs, sometimes everything works just as expected. There are no errors and the signing process is flawless. However, periodically (I would say 1 out of every 5 times) we get the following output:

```
Building web extension from /code/built/firefox
Validating add-on [...................................................................................................]
Validation results: https://addons.mozilla.org/en-US/developers/upload/78b76011e24a409cbafcae1266cd7abe
Signing add-on [......................................................................................................]

(node:62975) UnhandledPromiseRejectionWarning: Error: Signing took too long to complete; last status: {"guid":"hidden@hidden.io","active":false,"automated_signing":true,"url":"https://addons.mozilla.org/api/v4/addons/hidden@hidden.io/versions/2.45.14/uploads/78b76011e24a409cbafcae1266cd7abe/","files":[{"download_url":"https://addons.mozilla.org/api/v4/file/3612605/hidden-2.45.14-an+fx.xpi?src=api","hash":"sha256:74b15e530b05209e63a49a740eda8aec87f0aa534c2d699562b3e548aabc5d1b","signed":false}],"passed_review":false,"pk":"78b72222e24a409cbafcae1266cd7abe","processed":true,"reviewed":false,"valid"...
    at Object.exports.sign (/extension/scripts/publishFirefox.ts:200:15)

Signing add-on [......................................................................................................]
Downloading signed files: 100%
Downloaded:
    /code/built/zip-ff-signed/hidden-2.45.14-an+fx.xpi
```

Note that we get both an error, and a successful response.

This creates a problem from us in terms of recovery. We can't simply retry the script again because the version has now been added to AMO so we need to re-bump the version number in order to retry from start to finish.

### What is the expected or desired behavior?

Either success every time, or (if there is an error), then return an error and abort the signing process.

### Version information (for bug reports)

* **Firefox version**: N/A
* **Your OS and version**: MacOS 10.15.6
* Paste the output of these commands: 

````
node --version && npm --version && web-ext --version
````

v10.17.0
6.14.7
5.0.0

**Comment by rpl** [comment]
@EvHaus the default timeout for the sign command is bit higher then the value passed in the snipped above (the default is 900000, 15 minutes, see [sign-addon sources here](https://github.com/mozilla/sign-addon/blob/7e1d7ffe2d2e85b57ce8e477250c2cc97874da77/src/amo-client.js#L162) or [the backport of the longer timeout in web-ext v3.2.1](https://github.com/mozilla/web-ext/commit/7aa8660f308fc38069c3e57eafb138e47adb949f)).

Have you already tried to leave it to the default value or to pass an higher timeout value?

**Comment by EvHaus** [comment]
Interesting... Ok. We'll try that for the next few days and see how that goes. Thanks.

**Comment by rpl** [comment]
> Interesting... Ok. We'll try that for the next few days and see how that goes. Thanks.

Thanks! I'll keep this issue open in the meantime. Let me know how it goes so that we can then decide if we should do more triaging for this issue or just close it.

**Comment by rpl** [comment]
@EvHaus I'm closing this issue as invalid for now (based on the previous comments), feel free to reopen if increasing the timeout didn't fix the issue for you and we can evaluate what to do next.

**Comment by EvHaus** [comment]
Looks like that did the trick. We haven't seen any failures for the past 2 weeks.
