### ISSUE TITLE
Feature request: TypeScript definition

### ISSUE THREAD

**Issue by Jack-Works** [mozilla/web-ext#1986]
I found this project is written in `flow`, so I use https://github.com/Khan/flow-to-ts and https://api-extractor.com/ to generate a single `.d.ts` file but it will be nice to have an official type definition file!

**Comment by Jack-Works** [comment]
Here is our generated version of type definition for `web-ext`

**Comment by Jack-Works** [comment]
DimensionDev/Maskbook@60eb776

**Comment by rpl** [comment]
@Jack-Works thanks for looking into this, I was not even aware of flow-to-ts.

During our triaging yesterday I discussed about this issue with the rest of the team and we agreed that our preference would be to not integrate the generated file into this repo but as a separate npm package, for a couple of reasons:

- providing the typescript type signature as part of the web-ext npm package would actually require us to create some new automation to regenerate it as part of the regular developer workflow for this project (and also test that the generated type definitions are correct).
- there is also a chance that in some cases (probably not many, but still not completely impossible) a change to the flow types may trigger an unexpected issue in the automated type definition conversion (that would also need to be investigated).

Nevertheless, this may be a good addition to the type definitions npm packages that are being created from the [DefinitelyTyped repository](https://github.com/DefinitelyTyped/DefinitelyTyped) and we would be glad to help you with feedback comments on the pull request you could create in the DefinitelyTyped repo (if you like this idea and decide to create it) and then we would be open to link the official type definition npm package in our README.

I'm going to close this issue as wontfix, but feel free to mention me in the DefinitelyTyped pull request (and to open a new pull request to link that package in our README once a web-ext type definitions package is being released from that repo).

**Comment by benjick** [comment]
@Jack-Works which decl.js file did you use? Can't find the correct one

**Comment by Jack-Works** [comment]
https://www.npmjs.com/package/web-ext-types
