### ISSUE TITLE
JSON_INVALID lint error returns null file name instead of actual JSON file name

### ISSUE THREAD

**Issue by pdehaan** [mozilla/web-ext#1993]
### Is this a feature request or a bug?
Bug?

### What is the current behavior?

I was trying to test the webExt API to lint a project and noticed that it seems to send the `webExt.cmd.lint` output directly to STDOUT instead of returning it to my code, so I piped the output to disk (res.json) and noticed that I get an `JSON_INVALID` error because the file is temporarily empty (and in my `sourceDir`, but the error gives me a `null` value for the `file` prop (and I feel like it should know the file path, and lists it in the `emptyFiles[]` array in the `metadata`):

```json
{
    "count": 2,
    "summary": {
        "errors": 2,
        "notices": 0,
        "warnings": 0
    },
    "metadata": {
        "totalScannedFileSize": 233371,
        "emptyFiles": [
            "res.json"
        ],
        "jsLibs": {},
        "unknownMinifiedFiles": []
    },
    "errors": [
        {
            "_type": "error",
            "code": "TYPE_NO_MANIFEST_JSON",
            "message": "manifest.json was not found",
            "description": "No manifest.json was found at the root of the extension. The package file must be a ZIP of the extension's files themselves, not of the containing directory. See: https://mzl.la/2r2McKv for more on packaging."
        },
        {
            "_type": "error",
            "code": "JSON_INVALID",
            "message": "Your JSON is not valid.",
            "description": "Unexpected end of JSON input",
            "file": null
        }
    ],
    "notices": [],
    "warnings": []
}
```

```js
// lint-test.js
const webExt = require("web-ext");

webExt.cmd.lint({
    sourceDir: ".",
    output: "json",
    verbose: false,
    pretty: true,
  });
```

### What is the expected or desired behavior?

If I get a `JSON_INVALID` error, it should list the correct filename instead of `null`.

### Version information (for bug reports)

* **Firefox version**:
* **Your OS and version**: macOS 10.15.6
* Paste the output of these commands:

```sh
> node --version && npm --version && web-ext --version

v14.7.0
6.14.7
5.0.0
```

**Comment by rpl** [comment]
@pdehaan this is going to be technically an [addons-linter](https://github.com/mozilla/addons-linter) issue, would you mind to file this issue in that repo?

**Comment by pdehaan** [comment]
Closing in favor of upstream https://github.com/mozilla/addons-linter/issues/3282
