### ISSUE TITLE
Replace adbkit dependency

### ISSUE THREAD

**Issue by apriljunge** [mozilla/web-ext#2025]
### Is this a feature request or a bug?
Feature request

### What is the current behavior?
Currently [adbkit](https://github.com/openstf/adbkit) is a dependency of web-ext. This project is [not maintained any more](https://github.com/openstf/adbkit#this-project-along-with-other-ones-in-openstf-organisation-is-provided-as-is-for-community-without-active-development). Adbkits dependencies will never get updated.

Currently node-forge, one of adbkits dependencies, has a [vulnerability](https://snyk.io/vuln/SNYK-JS-NODEFORGE-598677).

To solve this and future problems, adbkit should be replaced.

**Comment by rpl** [comment]
It looks that `@devicefarmer/adbkit` may be replacing the now unmaintained `adbkit` package, they released a patch release [2.11.2](https://github.com/DeviceFarmer/adbkit/releases/tag/v2.11.2) 24 days ago.

The node-forge dependency has not been updated yet, there is a pending pull request at DeviceFarmer/adbkit#28

**Comment by dotboris** [comment]
A fix for `node-forge` has been released (v0.10.0) and `@devicefarmer/adbkit` has released v2.11.3 with the update: https://github.com/DeviceFarmer/adbkit/blob/v2.11.3/package.json#L40
