### ISSUE TITLE
Hook up the linter

### ISSUE THREAD

**Issue by andymckay** [mozilla/web-ext#204]
I made some stupid mistakes with permissions the other day, writing an extension. Hooking up web-ext lint to point to the amo-linter might future proof my stupidity. Unlikely though.

**Comment by kumar303** [comment]
Documented:
* https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Getting_started_with_web-ext#Checking_for_code_lint
* https://developer.mozilla.org/en-US/Add-ons/WebExtensions/web-ext_command_reference#web-ext_lint
