### ISSUE TITLE
web-ext sign command fails when an extension id is provided on CLI and manifest

### ISSUE THREAD

**Issue by Alappin** [mozilla/web-ext#2040]
### Is this a feature request or a bug?

Bug

### What is the current behavior?

**running the sign command below with the "--id"**

web-ext sign --source-dir srcDir --artifacts-dir artDir --api-key key --api-secret secret --id extid

**when the manifest contains extension id**

```json
{
  "manifest_version": 2,
  "name": "extension",
  "browser_specific_settings": {
    "gecko": {
      "id": "extid"
    }
  }
}
```

**causes error**

s: Cannot set custom ID extid because manifest.json declares extid ID 

### What is the expected or desired behavior?

The sign command should still succeed as before as one of the "extension ids" used to be ignored. This seems to be a regression.

### Version information (for bug reports)

* **Firefox version**: latest
* **Your OS and version**: Ubuntu 18.04.5
* Paste the output of these commands:

````
node --version && npm --version && web-ext --version
````
v12.18.4
6.14.6
5.1.0

**Comment by Rob--W** [comment]
What do you mean by "succeed" and what is the regression? When two extension IDs are specified, there is ambiguity. According to the message of `web-ext sign --help`, "This has no effect if the extension already declares an explicit ID in its manifest.".

According to the source code, this behavior has already been there for at least the past four years: https://github.com/mozilla/web-ext/blame/94eab872fc378e65ad96dfcec60b226ebebdfdc8/src/cmd/sign.js#L89-L95

**Comment by Alappin** [comment]
By "succeed",  I mean that it did not throw an error. The command would successfully sign regardless of the both extension ids being specified.

Upon further investigation, I discovered that the error was not being thrown in version "4.2.0" of web-ext. So, I don't know exactly what changed between that version and "5.1.0". 

My main suspicion is that it seems to be related to some other bug report https://github.com/mozilla/web-ext/issues/1901. The theory being that, if browser_specific_settings where not being used due to this bug, then the checking code

```
https://github.com/mozilla/web-ext/blame/94eab872fc378e65ad96dfcec60b226ebebdfdc8/src/cmd/sign.js#L89-L95
```

was essentially useless due to the bug. When the bug then got fixed, anyone who had specified both extension ids started getting errors. This just a theory.

On the other hand, my 2 cents would be that, specifying both IDs should only be considered an ambiguity if the specified values are different not by virtue of having both. It is pretty common to have multiple values of the same key coming in from different sources where by they are applied due to predefined precedence rules.

**Comment by Rob--W** [comment]
When the ID is already set, specifying the same ID does not serve any purpose. It could conceal a bug in a build system, and fail when the developer changes the ID (whether in the CLI or in manifest.json).

I'm inclined to keep the behavior as is.

**Comment by Alappin** [comment]
I partially agree with what you are saying. I can concede on the precedence rules approach since it's a fair point that this might conceal a bug when a developer accidentally specifies different IDs. 

I still do think that the current check can be improved to the below:

```
      if ((id && manifestId) && (id !== manifestId)) {
        throw new UsageError(
          `Cannot set custom ID ${id} because manifest.json ` +
          `declares ID ${manifestId}`);
      }
```

In this case, the definition of ambiguity is more justifiable since having a developer providing two different IDs creates an ambiguous situation. However, had the provided IDs been the same, then it wouldn't matter either way.

**Comment by Rob--W** [comment]
Currently, the behavior is clear: `--id` cannot be specified if the manifest file contains the ID.

Special-casing `id` would help with your specific use case, but has potential to cause confusion down the line, when an unsuspecting developer changes the manifest file and/or webext config and/or command line flag.

For this reason, the current behavior is preferred and we'll close this issue.

**Comment by hymccord** [comment]
I just ran into this and wanted to mention something from the docs: https://extensionworkshop.com/documentation/develop/web-ext-command-reference/

For the command `web-ext sign`, it specifically says for the `--id` option:
```txt
A custom identifier string for the extension. This has no effect if the extension already declares an identifier in its manifest. This option may be useful for signing versions of an exisiting extension that you own.
```

That indicates to me that it will _not_ throw an error. The docs may need to be updated to reflect that.
