### ISSUE TITLE
browser.downloads.erase doesn’t work reliably

### ISSUE THREAD

**Issue by GrippenDynamik** [mozilla/web-ext#2045]
### Is this a feature request or a bug?
Bug

### What is the current behavior?
Attached test extension:
[removefile.zip](https://github.com/mozilla/web-ext/files/5359189/removefile.zip)
When you click the browser action, the test extension downloads a file (which is packaged with the extension), into the standard download directory.
When the file has finished downloading, the extension removes the file from disk and then erases it from the download history.

Firefox 81.0 (64-Bit):
When I load the extension with
about:debugging > This Firefox > Load Temporary add-on
everything works fine.

But when I run the extension with
web-ext run
the downloaded file remains in the download history.
But:
If I then click the browser action again, the old file is removed from the download history, and only the new file is now in the download history.
And if I click the browser action multiple times in quick succession, all files disappear from the download history.
After that, the extension works like it should: When I click once on the browser action, the file is both removed from disk and from the download history.

Firefox Developer Edition 81.0b9 (64-Bit):
The bug occurs in both cases:
about:debugging > This Firefox > Load Temporary add-on
web-ext run

### What is the expected or desired behavior?
The downloaded file should always be removed from the download history.

### Version information (for bug reports)

* **Firefox version**:
Firefox 81.0 (64-Bit)
Firefox Developer Edition 81.0b9 (64-Bit)
* **Your OS and version**:
Manjaro Linux with XFCE
(ML uses a rolling release model; my version is up-to-date)
* Paste the output of these commands:

````
node --version && npm --version && web-ext --version
````
v14.12.0
6.14.7
5.2.0

**Comment by Rob--W** [comment]
Is this a bug specific to `web-ext`? If not, please file a bug at https://bugzilla.mozilla.org/ instead.

**Comment by GrippenDynamik** [comment]
Firefox 81.0 (64-Bit):
It's specific to web-ext

Firefox Developer Edition 81.0b9 (64-Bit)
It occurs both with and without web-ext

I'll file a report on https://bugzilla.mozilla.org/

**Comment by GrippenDynamik** [comment]
> Assigned to me to try the STR locally (but this is unlikely to be a web-ext bug, it may be a Firefox bug to report on bugzilla)

I've reported it:
https://bugzilla.mozilla.org/show_bug.cgi?id=1670407

Looks like it no longer happens in Nightly.

**Comment by rpl** [comment]
Closing as invalid from a web-ext perspective (filed on bugzilla as a Firefox bug).
