### ISSUE TITLE
Command to install extension from source permanently in profile of choice

### ISSUE THREAD

**Issue by krisfris** [mozilla/web-ext#2091]
### Is this a feature request or a bug?
Feature request

### What is the current behavior?
Currently you have to do several things to get an extension installed from source.

1. web-ext sign
2. web-ext build
3. Rename zip file to .xpi
4. Drag to browser
5. Click on confirm button

### What is the expected or desired behavior?
Run `web-ext install --firefox-profile default` and the extension will be permanently installed in your browser.

This would be great to quickly install your own extensions as well as others you clone from GitHub, especially if you want to update it frequently.

**Comment by imshubh4141** [comment]
@krisfris Are you working on the feature??Else may I implement this?

**Comment by krisfris** [comment]
I'm not working on it, you can go ahead.

**Comment by rpl** [comment]
This is outside of the scope of the web-ext cli command, any user can just achieve something similar by signing the extension using `web-ext sign`  and then copying the xpi file into the Firefox profile where the user may want to sideload it, once Firefox is started will warn the user of a new sideloaded extension and ask the user to confirm if the sideloaded extension should be approved.

If that isn't enough, the web-ext package can also be used as a library and integrate it in your own nodejs project to reuse the parts that are already provided by the web-ext commands (See https://github.com/mozilla/web-ext#using-web-ext-in-nodejs-code).

Closing as wontfix.
