### ISSUE TITLE
Support firefox x64 in windows x64

### ISSUE THREAD

**Issue by vietngoc** [mozilla/web-ext#213]
Hi, i am us firefox x64 and nodejs x64 in windows 10 x64. When i run web-ext, i receive notify error: 
Running web extension from E:\Labs\test
Building web extension from E:\Labs\test
Your web extension is ready: C:\Users\xxx\AppData\Local\Temp\tmp-web-ext-4120GVW04J5ZfM39\test-1.0.xpi
Running Firefox with profile at C:\Users\xxx\AppData\Local\Temp\dcdc0135-aaa1-410d-8a8e-bead2534a8c4
Firefox error: Error: spawn C:\Program Files (x86)\Mozilla Firefox\firefox.exe ENOENT
Error: spawn C:\Program Files (x86)\Mozilla Firefox\firefox.exe ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:437:9)
    at process._tickCallback (node.js:351:17)
Can you fix soon?

**Comment by Croydon** [comment]
The same bug is happening with jpm. Would be cool if this is getting fixed in both applications :)

**Comment by kumar303** [comment]
I don't have a windows machine to reproduce this but the bug is probably in https://github.com/mozilla-jetpack/node-fx-runner (which is also used by jpm). If someone could help patch that, it would be very helpful. Either myself or @bwinton can help review and merge the code.

**Comment by vietngoc** [comment]
i recently have created a pull request here. https://github.com/mozilla-jetpack/node-fx-runner/pulls/15. I think we should remove support firefox 32bit in windows x64.

**Comment by welwood08** [comment]
Any ETA on that fix getting into a release so new users won't hit this issue like I did? FWIW I manually modified my install of fx-runner with above patch and it works fine.

**Comment by kumar303** [comment]
Sure, I can try to cut a release for this on Monday (but it might happen the following week).

**Comment by HarveyWilliams** [comment]
If anyone else runs into this issue while waiting for the fix to get released, you can do the following:

- Open a CMD prompt with admin privileges at `C:\Program Files (x86)`
- Run `mklink /J "Mozilla Firefox" "C:\Program Files\Mozilla Firefox"`

This will create a directory at `C:\Program Files (x86)\Mozilla Firefox` which is a reference to the 64bit directory.

**Comment by kumar303** [comment]
Hi. Sorry for the delay. This has been fixed in `fx-runner` and applied to web-ext in https://github.com/mozilla/web-ext/commit/6a5582e

I also just pushed this out in version `1.10.1` - https://www.npmjs.com/package/web-ext

Could you test it out and let me know if it fixed the issue?

**Comment by welwood08** [comment]
After `npm uninstall -g web-ext && npm install -g web-ext` to get 1.10.1, can confirm that `web-ext run` correctly finds Firefox x64 on Windows x64 now. Thanks!
