### ISSUE TITLE
Feature request: Add build.filename option for config files

### ISSUE THREAD

**Issue by RC-14** [mozilla/web-ext#2171]
### Is this a feature request or a bug?
feature request

### What is the current behavior?
It's not possible to change the default file name of "web-ext build" in config files.

### What is the expected or desired behavior?
That the "filename" value for build in config files changes the value of the "--filename" parameter of "web-ext build".

**Comment by rpl** [comment]
@RC-14 thanks for filing this issue, the filename can actually be already configured from a config file, but there is currently a legit bug: 
- the filename config is wrongly part of the global options (but build is the only command that is currently expecting it).

And so at the moment a config file like this works:
```js
module.exports = {
  filename: 'my-filename-fromconfig-{applications.gecko.id}.xpi',
};
```

Nevertheless I think we may want to move the filename option into the build-specific options, and it would be a backward incompatible change and so we would be likely including it in the next major release (we intend to release it pretty soon).

**Comment by RC-14** [comment]
@rpl Thank you for your quick reply and help.
