### ISSUE TITLE
No way to temporarily install on Firefox for Android Nightly on Android 11

### ISSUE THREAD

**Issue by M-Reimer** [mozilla/web-ext#2173]
### Is this a feature request or a bug?
Bug

### What is the current behavior?
At least on Android 11 the actual file access permission, I can give to Firefox Nightly, is "File access, media only". I can't just add permission for just file access.

This results in the following output when actually trying to "run" my Add-on:

```
Selected ADB device: XXXXX
Stopping existing instances of org.mozilla.fenix...
Old artifacts directories have been found on XXXXX device. Use --adb-remove-old-artifacts to remove them automatically.
Starting org.mozilla.fenix...
Waiting for org.mozilla.fenix Remote Debugging Server...
Make sure to enable "Remote Debugging via USB" from Settings -> Developer Tools if it is not yet enabled.
Building web extension from /home/mozdev/git/togglereferrer
Waiting for org.mozilla.fenix Remote Debugging Server...
Make sure to enable "Remote Debugging via USB" from Settings -> Developer Tools if it is not yet enabled.
You can connect to this Android device on TCP port 40691

o: installTemporaryAddon: Error: Error: Could not install add-on at '/sdcard/web-ext-artifacts-1614420488018/toggle_referrer-5.4.0.xpi': [Exception... "Component returned failure code: 0x80520015 (NS_ERROR_FILE_ACCESS_DENIED) [nsIZipReader.open]"  nsresult: "0x80520015 (NS_ERROR_FILE_ACCESS_DENIED)"  location: "JS frame :: resource://gre/modules/addons/XPIInstall.jsm :: XPIPackage :: line 321"  data: no]
    at /usr/lib/node_modules/web-ext/dist/webpack:/src/firefox/remote.js:137:27
    at Client.handleMessage (/usr/lib/node_modules/web-ext/node_modules/@cliqz-oss/firefox-client/lib/client.js:162:7)
    at Client.readMessage (/usr/lib/node_modules/web-ext/node_modules/@cliqz-oss/firefox-client/lib/client.js:221:10)
    at Client.onData (/usr/lib/node_modules/web-ext/node_modules/@cliqz-oss/firefox-client/lib/client.js:187:16)
    at Socket.emit (node:events:378:20)
    at addChunk (node:internal/streams/readable:313:12)
    at readableAddChunk (node:internal/streams/readable:288:9)
    at Socket.Readable.push (node:internal/streams/readable:227:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

### What is the expected or desired behavior?

I don't know how this can be fixed... Maybe if the extension would be replaced with ".mp3" to "fake media access"?

Some information about this: https://developer.android.com/about/versions/11/privacy/storage

As the "--filename" parameter to "web-ext run" seems to do nothing, I have not managed to try what happens if the file extension is just "zip" or even ".jpg".

### Version information (for bug reports)

* **Firefox version**: Nightly
* **Your OS and version**: Android 11
* Paste the output of these commands:

````
node --version && npm --version && web-ext --version
````
v15.10.0
6.14.11
5.5.0

**Comment by danielzgtg** [comment]
I opened a pull request to fix this: #2200

To work around the problem in the meantime, do:

1. Run `vim .nvm/versions/node/*/lib/node_modules/web-ext/dist/web-ext.js`
2. Type `:s/sdcard/data\/local\/tmp/`
3. Type `:wq`
