### ISSUE TITLE
Firefox instances are marked as "Browser is under remote control"

### ISSUE THREAD

**Issue by Juraj-Masiar** [mozilla/web-ext#2196]
### Is this a feature request or a bug?
Both I guess?

### What is the current behavior?
Somehow new Firefox 87 detects web-ext as "Remote control".
This was not the case before, although this protection was present in Firefox for some time now.
As the style looks bad and make URL almost unreadable, is there is way to prevent it in web-ext?

![Screenshot 2021-03-12 16 56 35](https://user-images.githubusercontent.com/6358971/110966621-beb62900-8355-11eb-890a-f383e654f386.png)

There is a bug for making it "less annoying" but it's a year old and it doesn't seem to be going anywhere:
https://bugzilla.mozilla.org/show_bug.cgi?id=1594435

### Version information (for bug reports)

* **Firefox version**: 87
* **Your OS and version**: Win 10 20H2

````
v14.0.0
6.14.11
5.5.0
````

**Comment by karelkral** [comment]
I am encountering this behavior also when running Firefox from Visual Studio Code debugger. Please change it!

**Comment by Juraj-Masiar** [comment]
This has been improved in Firefox 90 by changing the background color to dark red which has much better contrast so the text is now visible again:
![Screenshot 2021-06-02 09 38 10](https://user-images.githubusercontent.com/6358971/120443461-f4801200-c386-11eb-97e0-d61e5b2df465.png)

This is good enough for me, but maybe others still would like to have this fixed/removed? But if this is on Firefox side, it may not be possible from web-ext side.

**Comment by MurzNN** [comment]
I've removed the striped background via this custom css in the `chrome/userChrome.css` file:
```css
:root[remotecontrol] #urlbar-background {
  background: white !important;
}
```
