### ISSUE TITLE
Also check errno when catching errors having a specific code

### ISSUE THREAD

**Issue by kumar303** [mozilla/web-ext#220]
There is a [helper](https://github.com/mozilla/web-ext/blob/master/src/errors.js#L70) in web-ext which is used like:

    thing().then(...).catch(onlyErrorsWithCode('ECONNREFUSED', ...));

It looks for `error.code` but in NodeJS `error.errno` is an [alias](https://nodejs.org/api/errors.html#errors_system_errors) for this. The `onlyErrorsWithCode()` function should also check `error.errno`.

**Comment by wagnerand** [comment]
See https://wiki.mozilla.org/Add-ons/Contribute/AMO/Code if this is your first web-ext bug you work on.

Mentor for this bug is @kumar303.
