### ISSUE TITLE
Remove the need to click OK when connecting to the remote debugger

### ISSUE THREAD

**Issue by kumar303** [mozilla/web-ext#224]
Since web-ext is a development tool, it only adds friction to the process when you have to click OK in Firefox to allow the remote debugger connection. @rpl has an idea for using an add-on to disable this prompt :)

**Comment by rpl** [comment]
@kumar303 I took a rapid look and the good news is that now it is much more simple than in the past:
we can just use an existent preference, isn't it great? :-)

```diff
diff --git a/src/firefox/preferences.js b/src/firefox/preferences.js
index adc8106..ec08e15 100644
--- a/src/firefox/preferences.js
+++ b/src/firefox/preferences.js
@@ -75,6 +75,7 @@ prefs.firefox = {
   'startup.homepage_welcome_url.additional' : '',
   'devtools.errorconsole.enabled' : true,
   'devtools.chrome.enabled' : true,
+  'devtools.debugger.prompt-connection' : false,

```

References:
- https://dxr.mozilla.org/mozilla-central/source/devtools/shared/security/auth.js#199

NOTE: this will be even more important if we want to run integration tests around the "run auto-reload" feature on a build machine.

**Comment by andymckay-limited-access** [comment]
We looked at this the good first bug triage and we felt it probably wasn't a good first bug.

**Comment by kumar303** [comment]
This is just a one line patch to https://github.com/mozilla/web-ext/blob/master/src/firefox/preferences.js#L19

**Comment by kumar303** [comment]
I'm adding this as part of the patch to https://github.com/mozilla/web-ext/issues/222
