### ISSUE TITLE
web-ext depends on obsolete, deprecated or unsupported npm modules

### ISSUE THREAD

**Issue by rathann** [mozilla/web-ext#2275]
### Is this a feature request or a bug?
Bug.

### What is the current behavior?

```
npm install --no-optional --only=prod
 Downloading prod dependencies
npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
npm WARN deprecated event-to-promise@0.8.0: Use promise-toolbox/fromEvent instead
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
```

### What is the expected or desired behavior?
No
```
npm WARN deprecated ...
```
lines in output.

### Version information (for bug reports)

* **Firefox version**: **89.0**
* **Your OS and version**: **Fedora 34**
* Paste the output of these commands:

````
node --version && npm --version && web-ext --version
v14.17.0
6.14.13
6.2.0
````

**Comment by rathann** [comment]
Related: #1334 and #2130 .

**Comment by rpl** [comment]
babel-eslint is actually part of the dev dependencies, not sure why the reporter got it while running `--only=prod`, but it would be good to track replacing that as well (it may not be worth having a separate bug and so I opted to add it to the list in in #2130 issue description).

All other deprecation warning are  already being tracked by #2130, and so I'm going to close this one as a duplicate.
