### ISSUE TITLE
Local installation? 

### ISSUE THREAD

**Issue by matanster** [mozilla/web-ext#2293]
Thank you for this great project! 

Currently it may seem as if only global installation is possible, which may require root permissions for installing files to `/usr/lib/node_modules`. I noticed that attempting a non-global installation, the install still tries to install to the directory. 

It would be cleaner to allow non-global installation, which would allow things such as installing the latest commit, side-by-side versions and also possibly making some CI processes more easily reproducible. I think it would also be more robust from a security perspective. 

Ubuntu 20.04

````
node --version && npm --version && web-ext --version
v16.6.0
7.19.1
6.2.0
````

**Comment by Rob--W** [comment]
`web-ext` doesn't force you to use a global installation.

If you install using `npm install web-ext`, then it would install to your current directory by default (or maybe an ancestor containing `node_modules` or `package.json`?).

If you install using `npm install -g web-ext`, then it would install to the directory specified by the `prefix` config option. To change the default location, create a user-specific `.npmrc` that sets the `prefix` options, see:

- https://docs.npmjs.com/cli/v7/configuring-npm/npmrc
- https://docs.npmjs.com/cli/v7/using-npm/config#prefix
