### ISSUE TITLE
Remove android.permission.READ_EXTERNAL_STORAGE permission requirement

### ISSUE THREAD

**Issue by Rob--W** [mozilla/web-ext#2312]
Follow-up to https://github.com/mozilla/web-ext/pull/2306/files#r698444621

web-ext doesn't need to ask for the READ_EXTERNAL_STORAGE permission on Android, because the profile/add-on is now stored in `/data/local/tmp` instead of `/sdcard`: https://github.com/mozilla/web-ext/blame/c884696fd3ea496c67959337f98d4e39bdb08871/src/util/adb.js#L14 (#2200).

Let's remove the code that does it to simplify the implementation.

**Comment by snapfast** [comment]
Facing issue because of this 
![image](https://github.com/mozilla/web-ext/assets/5176514/c8b73487-195c-4bfa-9095-1b835cb39e43)

**Comment by ioanarusiczki** [comment]
@willdurand thanks for the steps for testing this. 

I didn't make an update to the latest web-ext so after the command I had the error displayed
![webextandroid_720](https://github.com/mozilla/web-ext/assets/33448286/1bfec468-ac84-4245-9858-ccec5972f3a6)

Updated to the latest commit - [1d35140](https://github.com/mozilla/web-ext/commit/1d35140c7bdf7669c061f806264c28eef534c0c8) and first revoked the granted permission then I ran the command again and I this error is no longer displayed, I could make a temporary upload with success using the emulator. 

Command is `web-ext run -t firefox-android -s . --android-device=emulator-5554 ----firefox-apk=org.mozilla.fenix.debug`

![webextandroid3](https://github.com/mozilla/web-ext/assets/33448286/97bb3780-0708-4707-ac3c-5e75d8b924df)
