### ISSUE TITLE
Signing took too long to complete

### ISSUE THREAD

**Issue by mtatarau90** [mozilla/web-ext#2314]
### Is this a feature request or a bug?

Bug.

### What is the current behavior?
Hi Guys,

I tried to sign an unlisted addon , but for a few months I encounter the next error “Signing took too long to complete”.It Is strange because everything went fine until April, and my code was not changed. I saw this issue on a few github repositories but no one has an answer.

What i tried until now:

1. To sign with different version of web-ext (4, 5, 6)
2. To create a new addon with the same code base and a different id.

Unfortunately no solution worked for me.

Another strange thing is that the addon is uploaded but remains in “Awaiting Review”. I have an addon that is in “Awaiting Review” for more than a month

### What happened?
`Error: Signing took too long to complete; last status: {"guid":"it@mysite.com","active":false,"automated_signing":true,"url":"https://addons.mozilla.org/api/v3/addons/it@mysite.com/versions/21.6/uploads/d79e8409195942ec9e172d2a39979eac/","files":[{"download_url":"https://addons.mozilla.org/api/v3/file/3835741/xxx-21.6-an+fx.xpi","hash":"sha256:5f9824f2a0f7b0dc595ba47313b61801426ac3bf101fb1baa4e530dccacf1a37","signed":false}],"passed_review":false,"pk":"d79e8409195942ec9e172d2a39979eac","processed":true,"reviewed":false,"valid"...
at Timeout._onTimeout (/Users/xxx/Work/prj/node_modules/web-ext/node_modules/sign-addon/dist/webpack:/src/amo-client.js:312:11)
at listOnTimeout (node:internal/timers:557:17)
at processTimers (node:internal/timers:500:7)`

Timeout is set to 30 minutes

### What is the expected or desired behavior?
`Addons server should have returned my signed .xpi file.`

````
node --version && npm --version && web-ext --version
````
`
v16.4.2
7.18.1
6.3.0
`

**Comment by willdurand** [comment]
Thanks for filing this issue. I saw you also created an issue in addons-server, no need to create too many issues :)

In some cases, signing is delayed and it can be caused by many different factors. Although AMO tries to sign add-ons in a quick manner, there is no guarantee that it is always the case. I'd suggest you get in touch with the AMO admins (amo-admins AT mozilla DOT com). Thanks!

**Comment by mtatarau90** [comment]
Thanks!

**Comment by willdurand** [comment]
We are going to update the message to explain why this happens, sometimes, see: https://github.com/mozilla/sign-addon/issues/880
