### ISSUE TITLE
Connect to 

### ISSUE THREAD

**Issue by zoutepopcorn** [mozilla/web-ext#2322]
### Is this a feature request or a bug?
Request

### What is the current behavior?
I am unable to connect to the chrome or browser extension API from localhost. 

``` This script should only be loaded in a browser extension. at Object.eval ```

### What is the expected or desired behavior?
I would like to debug by running my option page from another url than chrome-extension://. **It would be so very nice to connect from http://localhost:xxxx**. Now I have to build my every change I make, it will take 6 / 8 seconds. An option is to use esbuild, but its not working with Vuetify.

**Comment by Rob--W** [comment]
The error that you've printed has nothing to do with web-ext (this repository), but comes from the polyfill (https://github.com/mozilla/webextension-polyfill).

In any case, you cannot use extension APIs at localhost, so it wouldn't make sense to load from localhost.

The default behavior of `web-ext` is to reload the full extension when the sources have been updated. A side effect of doing a full reload is that extension pages are closed.

If you'd like to edit the HTML/CSS/JS and see the changes by simply reloading the page, then you could disable auto-reloading by passing the `--no-reload` option to `web-ext run`, and manually reload the page on demand in the browser.

**Comment by zoutepopcorn** [comment]
Thanks for your reply. 

I would like to find an option to be able to connect to the extension API in a way. 

It will help if you will build something in Vue / React. Last thing I tried is tried to cennect with an iframe, but getting some CORS errors and I am not able to disable security.
Maybe there is some other hacky way :|
