### ISSUE TITLE
Breaks under yarn >=3.0.0

### ISSUE THREAD

**Issue by leaumar** [mozilla/web-ext#2332]
### Is this a feature request or a bug?
Bug: crashes with a runtime error under a recent update of a popular package manager.

### What is the current behavior?
[This commit](https://gitlab.com/Marnes/copy-selected-links/-/commit/f8cdd27208309d578ed8ef3c197186446ce54f58) broke web-ext in my 6 addon projects. Updating yarn from 2.x to 3.0.0 and later causes the following error whenever invoking web-ext in any way (build, lint, run):
```
PS D:\Projects\copy-selected-links> yarn start
➤ YN0000: executing [start]: web-ext run
(node:7852) UnhandledPromiseRejectionWarning: TypeError: (0 , g.Parser) is not a function
    at R.cleanupProcessEnvConfigs (D:\Projects\copy-selected-links\.yarn\cache\web-ext-npm-6.5.0-1111bd61bd-fca1741464.zip\node_modules\web-ext\dist\web-ext.js:1:62943)
    at R.execute (D:\Projects\copy-selected-links\.yarn\cache\web-ext-npm-6.5.0-1111bd61bd-fca1741464.zip\node_modules\web-ext\dist\web-ext.js:1:63533)
    at Object.main (D:\Projects\copy-selected-links\.yarn\cache\web-ext-npm-6.5.0-1111bd61bd-fca1741464.zip\node_modules\web-ext\dist\web-ext.js:1:72644)
    at Object.<anonymous> (D:\Projects\copy-selected-links\.yarn\cache\web-ext-npm-6.5.0-1111bd61bd-fca1741464.zip\node_modules\web-ext\bin\web-ext:7:8)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.external_module_.Module._load (D:\Projects\copy-selected-links\.pnp.cjs:24162:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
```

Rverting back to 2.4.3 solves the error.

Sole exception to this is `yarn web-ext --version`, which just works.

The folks over at yarn are adamant that issues like this are not on their table. 😕 I hope it will be received better here.

### What is the expected or desired behavior?
Web-ext commands like `run` don't instantly fail with an error.

### Version information (for bug reports)

* **Firefox version**: n/a
* **Your OS and version**: Win10
* Paste the output of these commands:

````
node --version && npm --version && web-ext --version
````
14.18.1
6.14.15
6.4.0

Thanks

**Comment by leaumar** [comment]
Ironically, there are other issues like eslint and ts-eslint with their recent updates (v8 and 5) requiring yarn >=3 now 😅 It's crazy how fickle the nodejs ecosystem is.

**Comment by leaumar** [comment]
I just tried messing around with program.js and then debugging the faulty line during `npm test` to see if I could change anything about the imports or some such. The result is just weird behavior overall, not at all the usually predictable behavior I'm used to. It smells like hacks and the whole `require/import`... issue.

The only breadcrumb I can find in yargs itself is the dissimilarity between `./yargs` and the other exports:
```
    ".": [
      {
        "import": "./index.mjs",
        "require": "./index.cjs"
      },
      "./index.cjs"
    ],
    "./helpers": {
      "import": "./helpers/helpers.mjs",
      "require": "./helpers/index.js"
    },
    "./yargs": [
      {
        "require": "./yargs"
      },
      "./yargs"
    ]
```

The rubber duck in me that isn't into nodejs dependencies and resolution hacks asks if the missing `"import"` on `./yargs` could at all be related here, having to work through whatever magic yarn/pnp wraps around it. It couldn't be that simple, could it?

**Comment by leaumar** [comment]
Changing `import { Parser as yargsParser } from 'yargs/yargs';` to `import { Parser as yargsParser } from 'yargs/helpers';` doesn't seem to break anything. I got the idea from [this comment](https://github.com/yargs/yargs/blob/main/yargs#L1). Given the thing I noticed previously about the declarations in their package.json, I wanna try and see if it'll work this way under yarn. Hopefully I can just build this dependency locally and swap it in yarn somehow.

**Comment by leaumar** [comment]
Jesus christ, that fixes it...

All I did was open the web-ext dependency zip in the yarn cache, edit web-ext.js to replace the one occurence of "yargs/yargs" to "yargs/helpers", and then re-ran the webext command in my repository, getting a successful run instead of the `g.Parser is not a function`.

![image](https://user-images.githubusercontent.com/3950300/142481363-346a02c5-f14b-4223-a657-208ca2f378d8.png)
![image](https://user-images.githubusercontent.com/3950300/142481427-607f00d3-dd1e-4526-b52c-86efb7fb5ec8.png)
![image](https://user-images.githubusercontent.com/3950300/142481463-fa9d176d-28c3-46f3-87f1-363feece251e.png)

**Comment by rpl** [comment]
:heart: @leaumar as someone that also got to investigate quite some "surprising issues with npm dependencies and co." over the last few years, I can't thank you enough for going deep into the yarn "rabbit hole" and identified a more than reasonable fix for the issue you were facing.
