### ISSUE TITLE
Switch to next-generation circleci images 

### ISSUE THREAD

**Issue by Rob--W** [mozilla/web-ext#2371]
We use CircleCI images with the `circleci/` prefix in [our .circleci/config.yml](https://github.com/mozilla/web-ext/blob/1b0494a53f6671e13d0f64ecce6ccd658e40e7b3/.circleci/config.yml), but these are apparently deprecated.

We should look into switching to the replacement, `cimg/`.

- https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034
- https://circleci.com/docs/2.0/circleci-images/

**Comment by rpl** [comment]
Fixed in #2384
