### ISSUE TITLE
Create a web-ext cli installer module for alpine linux 

### ISSUE THREAD

**Issue by pcbuildpluscoding** [mozilla/web-ext#2380]
Is this a feature request or a bug?
Feature request

What is the current behavior?
Have not tried to install web-ext on alpine linux
But would be a good idea to complement the apk firefox package
Googled "install mozilla web-ext cli on Alpine linux" but nothing showed up

What is the expected or desired behavior?
Mozilla web-ext cli installed on alpine linux

node --version && npm --version && web-ext --version

v16.14.0
8.3.1
6.5.0

**Comment by Rob--W** [comment]
We cannot publish packages for every distribution. `web-ext` can be installed via `npm install -g web-ext`, and you can use that.
