### ISSUE TITLE
/permissions: Invalid permissions "*://developer.mozilla.org" at 0.

### ISSUE THREAD

**Issue by BoldBigflank** [mozilla/web-ext#2388]
### Is this a feature request or a bug?
Bug

### What is the current behavior?
When I copy https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions and make my permissions match, like so:

```
"permissions": [
  "*://developer.mozilla.org/*",
  "webRequest"
]
```

When I do `web-ext lint` I get the following warning:
```
MANIFEST_PERMISSIONS   /permissions: Invalid permissions "*://developer.mozilla.org" at 0.
```

### What is the expected or desired behavior?
I would expect by following the manual I would have valid permissions generated.

### Version information (for bug reports)
* web-ext version 6.8.0
* WSL

````
node --version && npm --version && web-ext --version
v16.4.2
7.21.0
6.8.0
````

**Comment by Rob--W** [comment]
Could you share the manifest.json file of the extension that you're trying to validate?

The only way to trigger this error that I can think of is if manifest_version is set to 3 instead of 2.

**Comment by rpl** [comment]
Closing as incomplete. Feel free to ping us if there are additional information that we can use to properly investigate the issue.
