### ISSUE TITLE
The config file at web-ext-config.js specified an unknown option: "ignoreFiles"

### ISSUE THREAD

**Issue by benjick** [mozilla/web-ext#2392]
### Is this a feature request or a bug?
Bug 🐛

### What is the current behavior?
With this `web-ext-config.js`:
```
const config = {
  lint: {
    ignoreFiles: ["browser-profiles", "lib/"],
  },
};

module.exports = config;
```
running `yarn web-ext lint` (version 6.8.0) I get the following error:

```
Applying config files: ./package.json, ./web-ext-config.js

s: The config file at /Users/xxxx/web-ext-config.js specified an unknown option: "ignoreFiles"
```

### What is the expected or desired behavior?
It should be a valid option

### Version information (for bug reports)

* **Firefox version**: N/A
* **Your OS and version**: macOS 12.3
* Paste the output of these commands:

````
node --version && npm --version && yarn web-ext --version
v16.13.1
8.1.2
yarn run v1.22.18
$ /Users/max/dev/bgg-extension/node_modules/.bin/web-ext --version
6.8.0
````

**Comment by benjick** [comment]
It works if I set ignoreFiles as a global config

**Comment by rpl** [comment]
> It works if I set ignoreFiles as a global config

yep, [ignoreFiles is actually defined as a global config](https://github.com/mozilla/web-ext/blob/666886f40a967b515d43cf38fc9aec67ad744d89/src/program.js#L446-L457) and so it has to be in the global part of the config file.
