### ISSUE TITLE
Native messaging : Failed to execute command "/home/<user>/path/to/script.sh"  NativeMessaging.jsm:113

### ISSUE THREAD

**Issue by Afizullah** [mozilla/web-ext#2393]
### Is this a feature request or a bug?
A bug

### What is the current behavior?
Trying to launch a native app from browser by clicking on a html button via the native messaging mechanism

Testing the extension using "web-ext run", when i click on the button, the browser command give me the following error 

"Failed to execute command "/home/<user>/path/to/script.sh""  NativeMessaging.jsm:113

I declared the json file in ~/.mozilla/native-messaging-hosts/lanceur.json
which content is the following 

{
  "name": "lanceur",
  "description": "description",
  "path": "/home/<user>/path/to/script.sh",
  "type": "stdio",
  "allowed_extensions": ["lanceur-app@mail.com"]
}

### What is the expected or desired behavior?
The script is supposed to execute and the browser receives a "successful response" from the native host.
The windows equivalent with declaration in the registry actually works, is there something else i have to do in Linux ?

### Version information (for bug reports)

* **Firefox version**: 99.0 (64 bits)
* **Your OS and version**: Ubuntu 20.04
* Paste the output of these commands:

````
node --version && npm --version && web-ext --version
node v17.8.0
npm 8.5.5
web-ext 6.8.0

````
Thanks in advance !

**Comment by Rob--W** [comment]
This is unlikely to be an issue with web-ext.

Have you tried the troubleshooting steps that are documented at https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_messaging#troubleshooting ?
