### ISSUE TITLE
vulnerabilities reported by npm audit

### ISSUE THREAD

**Issue by foolioo** [mozilla/web-ext#2396]
### Is this a feature request or a bug?

security

### What is the current behavior?

`npm audit` for the version 6.8.0 (latest) is reporting for vulnerabilities

```shell
$ jq '.dependencies' package.json
{
  "web-ext": "6.8.0"
}

$ npm audit
...
5 vulnerabilities (1 moderate, 4 high)
...
```

### What is the expected or desired behavior?

`npm audit` should not report any vulnerabilities

### Version information (for bug reports)

```shell
$ node --version && npm --version && npx web-ext --version
v16.15.0
8.10.0
6.8.0
```

**Comment by rpl** [comment]
That's unfortunately due to the adbkit, I'm closing this as a duplicate of #2389 which is also related to the advisories that the adbkit dependency introduces in the tree of dependencies.
