### ISSUE TITLE
Upstream or expose profile creation + extension installed

### ISSUE THREAD

**Issue by fregante** [mozilla/web-ext#2439]
`firefox-profile` offers a flag to [install an extension](https://github.com/saadtazi/firefox-profile-js#command-line-interface) in the profile but it doesn't work:

- https://github.com/saadtazi/firefox-profile-js/issues/125

`web-ext` uses this module but then it takes care of installing the extension manually:

https://github.com/mozilla/web-ext/blob/416b12895109331170a5b4f3af64e83918f2488b/src/firefox/index.js#L474-L541

Would it be possible to upstream this ability or at least to expose it so that `web-ext` can be used while testing without having it run Firefox directly? This is useful for testing setups, which are currently are mess for Firefox because there's no easy way to install extensions programmatically.

[This is the best solution](https://github.com/puppeteer/puppeteer/issues/5532#issuecomment-706239839) I found:

1. Use `web-ext run` to open Firefox with the extension
2. Point puppeteer to its dev server

Puppeteer offers its own way to run Firefox and, if I could just use `web-ext` to create the profile, I'd just need to specify a single flag [like I do for Chrome](https://github.com/fregante/webext-dynamic-content-scripts/blob/1816d8a316b0d592df4502511e5bb1b7f6b302ee/jest-puppeteer.config.cjs#L7)

**Comment by fregante** [comment]
I just remembered that Firefox requires a live RDP call to install the extension, which means this isn't really practical either.

https://github.com/mozilla/web-ext/blob/416b12895109331170a5b4f3af64e83918f2488b/src/firefox/remote.js#L133-L151

Can anyone in Mozilla make the process of testing web extensions less painful? With Chrome I just need a single command line option and Firefox should allow the same thing.

**Comment by fregante** [comment]
Closing in favor of https://github.com/mozilla/web-ext/issues/1927

**Comment by christian-bromann** [comment]
@fregante can we maybe re-open this? I've build [this package](https://www.npmjs.com/package/@wdio/firefox-profile-service) and am interested in offering the ability to easily load an extension from an xpi file or fs path before the browser starts. It would be awesome if this package could simplify the creation of Firefox profiles.

**Comment by fregante** [comment]
Interest in this has already been expressed in https://github.com/mozilla/web-ext/issues/1927#issuecomment-1398265347

It's best to continue there
