### ISSUE TITLE
Remove `bunyan`

### ISSUE THREAD

**Issue by avi12** [mozilla/web-ext#2456]
### Is this a feature request or a bug?
In-between

### What is the current behavior?

`web-ext` depends on
https://github.com/mozilla/web-ext/blob/0d9f5e1835100e9365bcfe2148abe679aae831ef/package.json#L61
which depends on [moment@2.19.3](https://github.com/trentm/node-bunyan/blob/0ff1ae29cc9e028c6c11cd6b60e3b90217b66a10/package.json#L39), that has a [security vulnerability](https://github.com/avi12/skillshare-player-control/security/dependabot/17) that affects my Chrome extensions

### What is the expected or desired behavior?
Please switch to a different package other than [bunyan](https://www.npmjs.com/package/bunyan), as it seems to no longer be maintained (the last update was 2 years ago)

**Comment by willdurand** [comment]
That makes sense. I think we adopted [Pino](https://github.com/pinojs/pino) in our other projects. Pino used to be a drop-in replacement for bunyan a long time ago but it has evolved a lot since then. That might still be a straightforward replacement, though.

**Comment by fregante** [comment]
Are you open to a PR? Dependency-wise the project is huge and quite behind:

- https://npmgraph.js.org/?q=web-ext
- https://github.com/mozilla/web-ext/pulls


I worked on this before and I can do a little more cleaning again:

- https://github.com/mozilla/addons-linter/issues/3601

**Comment by willdurand** [comment]
sure thing

**Comment by fregante** [comment]
Sounds good! I can send a PR after most of the dependabot PRs are merged, there are a lot of low-hanging fruits there that would cause conflict with a Bunyan replacement PR

**Comment by fregante** [comment]
Good to see that those PRs were merged last week! I sent a PR for Pino:

- https://github.com/mozilla/web-ext/pull/3214

Also there the `open` PRs failed but for unrelated reasons. It just needs a rebase:

- https://github.com/mozilla/web-ext/pull/3075


You can see how big v9 was: https://packagephobia.com/result?p=open@10.0.0
