### ISSUE TITLE
Run with flatpak version

### ISSUE THREAD

**Issue by aniketfuryrocks** [mozilla/web-ext#2465]
Unable to `web-ext` run with `flatpak` version of firefox on `fedora 36`.

```bash
❯ web-ext run -f "flatpak run org.mozilla.firefox"
Applying config file: ./package.json
Running web extension from /mnt/Projects/Products/joinblob/extension

Error: not found: flatpak run org.mozilla.firefox
    at F (/home/aniket/.config/yarn/global/node_modules/fx-runner/node_modules/which/which.js:63:19)
    at E (/home/aniket/.config/yarn/global/node_modules/fx-runner/node_modules/which/which.js:72:29)
    at /home/aniket/.config/yarn/global/node_modules/fx-runner/node_modules/which/which.js:81:16
    at /home/aniket/.config/yarn/global/node_modules/fx-runner/node_modules/isexe/index.js:44:5
    at /home/aniket/.config/yarn/global/node_modules/fx-runner/node_modules/isexe/access.js:8:5
    at FSReqCallback.oncomplete (node:fs:201:23)
```

**Comment by willdurand** [comment]
I suppose `-f` expects a path to an executable without arguments. Maybe pass `"flatpak -- run org.mozilla.firefox"` to explicitly delimit the args?

**Comment by willdurand** [comment]
Forget my comment above, I think we'll need a bit more integration than that.. @rpl told me we could access the actual binary by using a different FS path, which would be a good step but then we need to give FF access to some folders like the temporary profile and the extension sources.

From a quick look at the docs, I think we could add proper `flatpak` integration in `web-ext`. We could pass the correct command when running `web-ext run` and add some flatpak options like [`--filesystem`](https://docs.flatpak.org/en/latest/sandbox-permissions.html#filesystem-access) to allow the temporary profile and extension sources to be "visible" by Firefox running in the flatpak container.

**Comment by willdurand** [comment]
@aniketfuryrocks hey, if you can, I'd be extra cool if you could try out the Flatpak integration by building and running `web-ext` locally. Thanks!
