### ISSUE TITLE
web-ext run failed

### ISSUE THREAD

**Issue by ddwolf** [mozilla/web-ext#2481]
### Is this a feature request or a bug?
It's a Bug

### What is the current behavior?

using create-web-ext to create a new extension, then go into that directory and run `web-ext run`, it shows these:
> file:///usr/local/lib/node_modules/web-ext/bin/web-ext.js:13
> await webExt.main(absolutePackageDir);
> ^^^^^
> 
> SyntaxError: Unexpected reserved word
>     at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
>     at async link (internal/modules/esm/module_job.js:42:21)

### What is the expected or desired behavior?
It's supposed to run smoothly

### Version information (for bug reports)

* **Firefox version**: 103.0
* **Your OS and version**: ubuntu22.04
* Paste the output of these commands:

````
node --version && npm --version && web-ext --version
````
> v12.22.9
> 8.5.1
> file:///usr/local/lib/node_modules/web-ext/bin/web-ext.js:13
> await webExt.main(absolutePackageDir);
> ^^^^^
> 
> SyntaxError: Unexpected reserved word
>     at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
>     at async link (internal/modules/esm/module_job.js:42:21)

**Comment by willdurand** [comment]
> node --version && npm --version && web-ext --version
> v12.22.9
> [...]

web-ext requires Node 14.

**Comment by rpl** [comment]
As @willdurand also mentioned in https://github.com/mozilla/web-ext/issues/2481#issuecomment-1215732731

web-ext >= v7.0.0 requires nodejs >= 14 (see release notes at https://github.com/mozilla/web-ext/releases/tag/7.0.0)

**Comment by minfrin** [comment]
Workaround on the Raspberry Pi:

```
npm install --global web-ext@6.8.0
```
