### ISSUE TITLE
use `pipeline` directly, without `promisify` once we support node16 minimum

### ISSUE THREAD

**Issue by eviljeff** [mozilla/web-ext#2483]
The node stream api doesn't have promise support until [node 15](https://nodejs.org/api/stream.html#streams-promises-api), so it needs to be wrapped in `promisify` under node 14.  Once we up our minimum node to 16 we can stop doing that.

**Comment by eviljeff** [comment]
I tried to fix this - it seemed like an easy fix now we're only >=16.0 node - but our flow type definitions in 0.182.0 are lacking.  The stream promises api was only added to flow in 0.204.0 so we're blocked on merging https://github.com/mozilla/web-ext/pull/2759

**Comment by willdurand** [comment]
> I tried to fix this - it seemed like an easy fix now we're only >=16.0 node - but our flow type definitions in 0.182.0 are lacking. The stream promises api was only added to flow in 0.204.0 so we're blocked on merging #2759

@eviljeff we removed flow 😅
