### ISSUE TITLE
Allow a new add-on or a new version submission to continue with an existing upload

### ISSUE THREAD

**Issue by eviljeff** [mozilla/web-ext#2492]
With the submission api the validation is effectively split up into two stages - upload validation, including the linter, scanners, etc, and then the addon/version validation, which is mainly (but not exclusively) about requiring certain metadata for listed add-ons.  So it's more than possible to submit an xpi upload which passes validation and returns an upload uuid, which is then rejected with a 400 response because the additional metadata submitted is either incorrect or deficient (one example of many possible: the category name is misspelt).  Currently to fix this you execute the command again - with the same content, which is then built into an xpi; then submitted to AMO; validated, scanned, etc; and a new upload uuid is returned; which you have to wait for - when the POST/PUT to `/addons/addon/` could occur with the existing upload instantaneously.

Ideally the default would be to resume the submission with the same upload if the add-on contents haven't changed.  (Details of how this would work technically tbd)

**Comment by ioanarusiczki** [comment]
@eviljeff @willdurand 

Is qa needed here?

**Comment by eviljeff** [comment]
I don't know if there's a general plan to test all the changes before the next release but this is a significant change so could be tested separately.  

As it's not in a release you'll have to clone the repo and checkout master (`git clone https://github.com/mozilla/web-ext`); then `npm install`; `npm run build`; `npm link` to set up `web-ext`.

To use the submission api it'd something like:
`web-ext sign --use-submission-api --api-key=<your key> --api-secret=<your secret> --amo-base-url=https://addons-dev.allizom.org/api/v5/ -s=xpi/ --channel=listed --amo-metadata=metadata.json` if your add-on manifest and files were in `/xpi`

STR:
- run the `web-ext` command but without all the necessary metadata specified in metadata.json (or incorrect, or the arg omitted entirely).  E.g. category name spelt incorrectly; license not specified under version, etc.
- observe the xpi is uploaded to `/api/v5/addons/upload/`; validated; then submitted to `/api/v5/addons/addon`
- AMO will return a 400 error about the missing metadata which `web-ext` will expose.
- add/fix the missing metadata in metadata.json
- repeat the same command
- observe that there is no new upload and delay for validation - it's submitted straight to `/api/v5/addons/addon`

That's the general case.   The exceptions are that if the manifest or any of the files that are built into the add-on (in `xpi/` in the example command above) are changed* a new upload should be made by `web-ext`; also if the channel is changed.

*some of the edge cases picked up during the PR review were empty files or directories being added

**Comment by willdurand** [comment]
> As it's not in a release you'll have to clone the repo and checkout master (`git clone https://github.com/mozilla/web-ext`); then `npm install`; `npm run build`; `npm link` to set up `web-ext`.

Not sure `npm link` is necessary here (the 2 other commands are)

> To use the submission api it'd something like: `web-ext sign --use-submission-api --api-key=<your key> --api-secret=<your secret> --amo-base-url=https://addons-dev.allizom.org/api/v5/ -s=xpi/ --channel=listed --amo-metadata=metadata.json` if your add-on manifest and files were in `/xpi`

You could use the locally built web-ext binary by running: `./bin/web-ext.js`

**Comment by ioanarusiczki** [comment]
@willdurand @eviljeff 

I managed something, git clone then went to the webext folder and ran the commands npm install, npm run build , npm link (did that too) -> I get a web-ext version like : `master-a3893be89bf92ad5fb7eacb9dc6eb434adc75728`

Then I tried on -dev a test with old singing api but ran into errors, right now uploads are not working because of -> https://mozilla-hub.atlassian.net/browse/SVCSE-1212

I tried an upload with AMO stage for an unlisted version using the old signing endpoint -> was successful 

I'll wait for a fix on -dev and then continue.

**Comment by eviljeff** [comment]
> I tried an upload with AMO stage for an unlisted version using the old signing endpoint -> was successful

AMO Stage will work too with the add-on submission API - it doesn't rely on new APIs or recent patches.

**Comment by ioanarusiczki** [comment]
@eviljeff @willdurand 

I tend to believe what I've noticed yesterday is all expected.

Please let me know if there's anything else I should test for this issue.

**Comment by ioanarusiczki** [comment]
@eviljeff 

> an add-on is submitted with metadata missing, so an upload is sent and validated, but an error is raised 

If metadata is incorrect the error is raised but after I correct the metadata and I run the command again,  the upload is repeated, basically the entire process

From what you said [above](https://github.com/mozilla/web-ext/issues/2492#issuecomment-1564755160), it shoud jump the upload step ?

![all process](https://github.com/mozilla/web-ext/assets/33448286/9cf428c8-bcc9-4c0f-9fdb-2c0da0f3e0d7)


> a file/directory is added/changed 

Do I hit an error at the first attempt and after correcting it + changing information in manifest.json or adding a new .js file) should repeat the process from the beginning in this case?

**Comment by ioanarusiczki** [comment]
@eviljeff 

With metadata.json outside the folder:
- when 400 is hit and errors are corrected in metadata.json , command repeated -> there's no new upload 
- when 400 is hit because of incorrect metadata then metadata is corrected but also files inside the folder of the extension are changed, added or deleted or the submission channel is changed -> a new upload is made
