### ISSUE TITLE
web-ext/util/logger does not have a default export (example doesn't work)

### ISSUE THREAD

**Issue by kewisch** [mozilla/web-ext#2508]
Hello Add-ons Friends :)

### Is this a feature request or a bug?
A bug 

### What is the current behavior?
```
import webExtLogger from "web-ext/util/logger";
       ^^^^^^^^^^^^
SyntaxError: The requested module 'web-ext/util/logger' does not provide an export named 'default'

webExtLogger.consoleStream.makeVerbose();
```

### What is the expected or desired behavior?
Either docs in the readme need to be adjusted to use the `consoleStream` export directly, or there needs to be a default export that makes the example in the docs work.

### Version information (for bug reports)

* Running off github actions with a linux runner and using web-ext 7.2.0

**Comment by aklinker1** [comment]
A workaround

```ts
import * as webExtLogger from "web-ext/utils/logger";
```

**Comment by willdurand** [comment]
> A workaround
> 
> ```ts
> import * as webExtLogger from "web-ext/utils/logger";
> ```

This is how it should be used indeed, the README needs to be adjusted :)
