### ISSUE TITLE
Use Node 18 in Circle CI

### ISSUE THREAD

**Issue by willdurand** [mozilla/web-ext#2617]
We should use Node 18 instead of Node 17 here: https://github.com/mozilla/web-ext/blob/6356fa9b4cbfa7b2b87e8a03d3e2e3b42988b531/.circleci/config.yml#L30

**Comment by Rob--W** [comment]
In #2616 tests have been updated to support Node 19. As the tests are already green, it might make sense to already merge the Node 19 support branch and run the Node 18 tests alongside it.

Along with dropping 17 off the build matrix, let's also confirm whether this is still needed:
https://github.com/mozilla/web-ext/blob/6356fa9b4cbfa7b2b87e8a03d3e2e3b42988b531/.circleci/config.yml#L283-L285
