### ISSUE TITLE
"dev-addons" link broken

### ISSUE THREAD

**Issue by Heikrana** [mozilla/web-ext#2631]
### Is this a feature request or a bug?
Bug

### What is the current behavior?
Broken Link

The link for **ask a question on dev-addons** in the section [Get Involved](https://github.com/mozilla/web-ext/#get-involved) in the project's README.md is broken. It gives 404 Not Found error with the message, "*The requested URL /listinfo/dev-addons was not found on this server.*".

**Comment by Rob--W** [comment]
We should update it to one of the links at https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/Contact_us

**Comment by Heikrana** [comment]
Yes, [Add-ons Discourse forum](https://discourse.mozilla.org/c/add-ons/35) seems fine, but the whole [Contact Us](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/Contact_us) page can also be linked.
