### ISSUE TITLE
Exclude node_modules from the built .xpi file

### ISSUE THREAD

**Issue by sjakthol** [mozilla/web-ext#269]
STR:
* Create simple web extension
* Run `npm install eslint` (or install some other stuff)
* Run `web-ext build`

Actual results: The resulting .xpi is huge (couple MB) and node_modules is the biggest contributor to that size.

Expected results: The .xpi is tiny and doesn't contain any unneeded files.

In issue #85, web-ext started to ignore some files but node_modules was not among them. I think it can be safely excluded from the .xpi since AFAIK Firefox won't be able to find the modules from there anyway.

If #131 and #176 get fixed soonish, I think we could leverage that to specify excludes. Otherwise, I'd add node_modules to the hardcoded list of excluded dirs while that feature is being implemented.

**Comment by kumar303** [comment]
Ignoring `node_modules` by default is a good idea. The [FileFilter](https://github.com/mozilla/web-ext/blob/master/src/cmd/build.js#L99-L103)'s default rules should ignore this directory. It should be easy to fix this up, thanks for the report.

Mentor: @kumar303
