### ISSUE TITLE
Use (new) API submission by default

### ISSUE THREAD

**Issue by willdurand** [mozilla/web-ext#2702]
We'd like to use the new-ish API submission by default, and keep the current one (considered "legacy") behind a flag, which we'll remove in v9 (which is the major after the current major).

**Comment by willdurand** [comment]
cc @eviljeff

**Comment by eviljeff** [comment]
https://github.com/mozilla/web-ext/issues/2503 - for any outstanding blockers to making it the default.

**Comment by willdurand** [comment]
In fact, we are not going to make the submission API the default with a way to keep using the old API via sign-addon. We are going to make the submission API the only signing API in v8. Users who want to use the "old" API (sign-addon) should continue to use v7.
