### ISSUE TITLE
Allow to skip "wait for approval" when submitting a new version

### ISSUE THREAD

**Issue by willdurand** [mozilla/web-ext#2704]
When we sign a new version of an extension, `web-ext` waits for approval in order to download the signed XPI (it waits for some time, then it gives up). For a end user, it is probably a sensible behavior but `web-ext` is also used in CI.

In this case, it'd be interesting to expose a new CLI flag to disable this waiting loop and only store the metadata we get from the submission call itself. Ideally, the metadata should be enough to retrieve the signed XPI at a later point in time. Maybe we could even print a link that will _eventually_ point to an actual XPI (once this is signed).

**Comment by willdurand** [comment]
> Maybe we could even print a link that will _eventually_ point to an actual XPI (once this is signed).

The data we get back from the submission API should have an `edit_url`, which is a link to the version in DevHub. That sounds like a good URL to print for later use.

**Comment by ioanarusiczki** [comment]
@willdurand Let me know if I could test this, what's the CLI flag and if it's available on web-ext 7.8.0

**Comment by willdurand** [comment]
@ioanarusiczki the CLI flag is `--approval-timeout` and it will only work with the unreleased version of web-ext (master branch), which you need to build yourself... If you pass `approval-timeout=0`, then we shouldn't wait and download the signed version, and a message should indicate that the developer can go to DevHub to get the signed file.

**Comment by ioanarusiczki** [comment]
@willdurand 

I tried listed/unlisted versions for [an addon](https://addons-dev.allizom.org/en-US/firefox/addon/38a04afb6f9f4ed39123/)

With `web-ext sign --api-key="user:a user" --api-secret="is secret" --amo-base-url=https://addons-dev.allizom.org/api/v5/ --channel=listed --amo-metadata=metadata.json --approval-timeout=0`

The approval is skipped 

![approval skipped](https://github.com/mozilla/web-ext/assets/33448286/2d342283-6128-4e3f-8dd9-d9d3b391bfef)

The url takes the developer to the dev hub's version page https://addons-dev.allizom.org/en-US/developers/addon/38a04afb6f9f4ed39123/versions/1703422 where it can download the xpi. 

If I tried `--approval-timeout=1000` or a different value than 0 the version is uploaded but I receive an error at the approval step, it's `WebExtError: Approval: timeout.`

**Comment by willdurand** [comment]
> If I tried `--approval-timeout=1000` or a different value than 0 the version is uploaded but I receive an error at the approval step, it's `WebExtError: Approval: timeout.`

I think this is a bug then. I am not sure why `1000` wouldn't work...
