### ISSUE TITLE
Remove `sign-addon` dependency

### ISSUE THREAD

**Issue by willdurand** [mozilla/web-ext#2737]
Once we make the submission API the default, we can remove `sign-addon` and the old signing code.

**Comment by lsim** [comment]
Any thoughts on when this task might get released? It's tripping up our CI audit.

**Comment by ioanarusiczki** [comment]
@willdurand 

I uploaded using web-ext 7.8.0 listed and unlisted versions

on AMO Dev: https://addons-dev.allizom.org/en-US/developers/addon/38a04afb6f9f4ed39123/versions
on AMO Stage: https://addons.allizom.org/en-US/developers/addon/web-ext-submission-on-amode2/versions

During the process I don't think I've noticed changes. I did have errors after the upload when I did not add metadata for listed versions in metadata.json, but I'm sure that's expected to happen.

When I'm at the signing step, I exit it with Ctrl+C , this would be the last step of the web-ext submission:

![signstep](https://github.com/mozilla/web-ext/assets/33448286/6a8d9b35-a64a-46df-84e5-a614c01ab942)

**Comment by willdurand** [comment]
I guess we're good then?

**Comment by ioanarusiczki** [comment]
@willdurand Yes, I really wish I had more time to explore but there's too many issues on the other repos. 

Marking this verified.
