### ISSUE TITLE
SyntaxError: Unexpected reserved word

### ISSUE THREAD

**Issue by dominic-g** [mozilla/web-ext#2742]
### What is the current behavior? error the app does not run

The app does not run any commands on the terminal after install, I keep getting the error
`file:///usr/local/lib/node_modules/web-ext/bin/web-ext.js:13
await webExt.main(absolutePackageDir);
SyntaxError: Unexpected reserved word`
### What is the expected or desired behavior?
For the app to run normally
### Version information (for bug reports)
not sure i cannot even run `web-ext -v`
- **Firefox version**: 
- **Your OS and version**:
- Paste the output of these commands:

```
node --version && npm --version && web-ext --version
```
`v12.22.9             
8.5.1                                                     
file:///usr/local/lib/node_modules/web-ext/bin/web-ext.js:13         
await webExt.main(absolutePackageDir);                                      
^^^^^
                                                    
SyntaxError: Unexpected reserved word                                   
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)`

**Comment by willdurand** [comment]
We no longer support Node 12, please use Node 16+.

**Comment by dominic-g** [comment]
Yes that was the issue upgrading node to 16 works like a charm
