### ISSUE TITLE
Environment variables not working with non-global options

### ISSUE THREAD

**Issue by prometh07** [mozilla/web-ext#276]
[Command reference](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/web-ext_command_reference#web-ext_sign) mentions the ability of using env vars for settings such as api-secret or api-key. However, the tool doesn't parse them.

**Comment by kumar303** [comment]
Thanks for filing (I thought there was already an open bug but I can't find it). I think it's confusing behavior and will likely be fixed in yargs directly -- https://github.com/yargs/yargs/issues/486 . Until then, your workaround looks good.
