### ISSUE TITLE
Discover an open remote debugger port

### ISSUE THREAD

**Issue by kumar303** [mozilla/web-ext#283]
In the patch for https://github.com/mozilla/web-ext/issues/93, the remote debugger port selection was improved. It will fail if the port is already in use. We should go further and make it select a different open port if one is already in use.

**Comment by kumar303** [comment]
There has been some architectural work done to prepare for this patch. As of now, the change should be simple. I can mentor anyone willing to try a patch for this. The work can be done in the [defaultRemotePortFinder()](https://github.com/mozilla/web-ext/blob/fa27fb0784e57a19a445139943c7ea3337c09139/src/firefox/index.js#L36-L40) function. Instead of throwing an error, a new port number should be chosen and tried in a loop until an open port is found.

**Comment by Krizzu** [comment]
Hey @kumar303. This looks fairly simple, so I can try my best to do it.

**Comment by kumar303** [comment]
> This looks fairly simple, so I can try my best to do it.

Great! Just let me know how I can help

> How to determinate when it is open and free to use? 

As you pointed out, the `ECONNREFUSED` error is probably enough to indicate that the port is free to use. Actually, the code is already in place to handle this situation. The only thing you'd need to implement is [where the error is thrown](https://github.com/mozilla/web-ext/blob/fa27fb0784e57a19a445139943c7ea3337c09139/src/firefox/index.js#L39). Instead of throwing an error, it needs to retry the promise in a loop.

**Comment by Krizzu** [comment]
Hey @kumar303 
I think I rushed myself saying that looks easy. :-1: 
So I was thinking, if I should implement a function that will retry the promise and wait for it until it's rejected. Am I on the right way?

**Comment by kumar303** [comment]
Heh, yeah, retry loops are never easy but this is a small piece of code and there are some other examples to follow. Take a look at how we [attempt connecting to Firefox in a retry loop](https://github.com/mozilla/web-ext/blob/96748e35ae5502d600b0255565b08f1c68e95355/src/cmd/run.js#L112-L140). You could do something similar to this.

**Comment by Krizzu** [comment]
hey @kumar303 
Thanks for that. I come up with this: 

```
  let retriesCount = 20; 
  function portConnectionRetry(){
    if(retriesCount == 0) throw 'ERROR' //change here
    return new Promise((resolve, reject) => {
        connectToFirefox(portToTry)
        .then((client) => {
          log.debug(`Remote Firefox port ${portToTry} is in use. Trying next one`);
          client.disconnect();
          portToTry++;
          throw new WebExtError(
            `Cannot listen on port ${portToTry} because it's in use\nTrying next one`
          );
        })
        .catch(onlyErrorsWithCode('ECONNREFUSED', () => {
          resolve(portToTry)
        }))
        .catch((err) => {
          reject(err)
        })
    })
    .then((port) => {
      console.log('returning Port', portToTry)
      return portToTry;
    })
    .catch(() => {
      retriesCount--;
      portConnectionRetry()
    })
  }
  return portConnectionRetry();
}
```
Would You mind having a look? Thanks.

**Comment by kumar303** [comment]
Hi. This is definitely on the right track. I have a few line by line comments but it would be easier if you made a pull request -- then I could comment directly on each line.

**Comment by kumar303** [comment]
fixed in https://github.com/mozilla/web-ext/pull/472
