### ISSUE TITLE
Warn web-ext v7 users about upcoming changes to the `sign` command

### ISSUE THREAD

**Issue by willdurand** [mozilla/web-ext#2877]
We want to fully get rid of [sign-addon](https://github.com/mozilla/sign-addon/) in v8, which means not only having the new submission API code be the default but also not having a fallback with sign-addon. Users who want to use sign-addon for some reason will have to stay on v7.

Therefore, we need to warn users of web-ext v7 about the upcoming changes.

**Comment by ioanarusiczki** [comment]
@willdurand 

I get a warning when I used the old signing API 

from cmd : `web-ext sign --api-key="user:user" --api-secret="secret" --api-url-prefix=https://addons.allizom.org/api/v4`


IMPORTANT: web-ext v8 will introduce a new AMO submission API for signing and you might need to take actions when upgrading from v7 to v8. You can test this upcoming change now by specifying `--use-submission-api` to the `sign` command. If you want to keep using the API you are using now (via "sign-addon"), you must stay on v7.
Building web extension from C:\Users\ioana.rusiczki\OneDrive - Cognizant\Desktop\webext2\test7
Validating add-on [.........................................................................................................................................................................................................................]
Validation results: https://addons.allizom.org/en-US/developers/upload/af4c0634729743eeaa504980fb7094a5
Signing add-on [............................................................................................................................................................................................................................]
Downloading signed files: 100%
Downloaded:
    .\web-ext-artifacts\ebb694d4b05a44a9b7f5-3.0.xpi
Extension ID: webextdev8@test
SUCCESS
