### ISSUE TITLE
Secure folder causes error during web-ext run

### ISSUE THREAD

**Issue by slavaleleka** [mozilla/web-ext#2903]
### Is this a feature request or a bug?

Bug

### What is the current behavior?

afte I run the command
```
web-ext run -t firefox-android --adb-device XXX --firefox-apk org.mozilla.fenix
```
the message is logged: `No Firefox packages were found on the selected Android device`

### What is the expected or desired behavior?

org.mozilla.fenix should be found

### Version information (for bug reports)

- **Firefox version**: 120 nightly
- **Your OS and version**: Windows 11

```
node --version: 18.18.0
npm --version: 9.8.1
web-ext --version: 7.8.0
```

**Comment by Rob--W** [comment]
PR 2904 was closed, why?

Note that a similar PR was opened before for a different reason in https://github.com/mozilla/web-ext/pull/2857

**Comment by slavaleleka** [comment]
@Rob--W after I opened my PR, I found this another one https://github.com/mozilla/web-ext/pull/2857, so I decided to close mine
