### ISSUE TITLE
Deprecated dependencies

### ISSUE THREAD

**Issue by odebroqueville** [mozilla/web-ext#3005]
### Is this a feature request or a bug?

I guess this is more of a request than a bug, but I don't know how serious this issue might be, namely security wise!

### What is the current behavior?

This screenshot says it all:

<img width="923" alt="Screenshot 2024-01-04 at 13 15 37" src="https://github.com/mozilla/web-ext/assets/4818315/dc133d54-b007-441f-b1c2-3b94b4ab6114">

### What is the expected or desired behavior?

I guess it would be preferable not to use deprecated or outdated dependencies.

### Version information (for bug reports)

- **Firefox version**: Firefox Developer Edition 122.0b5 (64-bit)
- **Your OS and version**: macOS Sonoma 14.2.1
- Paste the output of these commands:

```
node --version && npm --version && web-ext --version
```
v21.5.0
10.2.4
7.9.0

**Comment by wagnerand** [comment]
Duplicate of #2130.
