### ISSUE TITLE
Nested config settings can overwrite each other

### ISSUE THREAD

**Issue by dotproto** [mozilla/web-ext#3104]
### Is this a feature request or a bug?

Bug

### What is the current behavior?

1. Add the following configuration to a WebExtension project.
    ```js
    module.exports = {
      "lint": {
        "firefoxPreview": ['mv3'],
      },
      "run": {
        "firefoxPreview": ['']
      }
    };
    ```
2. CD into that project's directory and run `web-ext lint --firefox-preview`.
3. Observe that the following message is logged to the console. This is expected.
    ```text
    Manifest Version 3 is now officially supported and "--firefox-preview=mv3" is no longer needed. In addition, the "mv3" value will be removed in the future.
    ```
4. Run `web-ext lint`.
5. Observe that the message from step 3 is not logged to the console.

### What is the expected or desired behavior?

Command-specific settings declared in a configuration file should not interfere with each other. 

### Version information (for bug reports)

- **Firefox version**: 126.0a1
- **Your OS and version**: macOS 14.4.1 
- Paste the output of these commands: 

```
node --version && npm --version && web-ext --version
```

```
v21.6.2
10.2.4
master-e2bee027dee8e1a56dd49fd567edddc7ad75220c
```

This is a manually built version of web-ext that is very close to 8.0.0.

**Comment by willdurand** [comment]
We removed `--firefox-preview` entirely.

**Comment by ioanarusiczki** [comment]
Ah to add , with `web-ext lint` ran for an extension , it looks good, should be as expected.

![as expexted](https://github.com/mozilla/web-ext/assets/33448286/cdf01bc5-693c-48a6-bd60-6e12e39e0b38)
