### ISSUE TITLE
What to do about audit warnings?

### ISSUE THREAD

**Issue by GabenGar** [mozilla/web-ext#3106]
### Is this a feature request or a bug?
Neither.

### What is the current behavior?
`npm audit` returns `8 moderate severity vulnerabilities` but all the fixes downgrade `web-ext` to `7.2.0`. Those don't sound like vulnerabilities which can be ignored either, especially since `web-ext` is highly likely to be used with `webpack` which brings at least few hundred dependencies along baseline.

### What is the expected or desired behavior?
Fixing audit problems without downgrading `web-ext`.

### Version information (for bug reports)
- v20.9.0
- 8.7.0
- 7.11.0

**Comment by willdurand** [comment]
v8 is nearly done, and that should address some if not all the audit warnings.

**Comment by willdurand** [comment]
see https://github.com/mozilla/web-ext/issues/2678 (also we released v8: https://github.com/mozilla/web-ext/releases/tag/8.0.0)
