### ISSUE TITLE
`--id` flag seems to be unused in HEAD (8.0.0 pre-release)

### ISSUE THREAD

**Issue by dotproto** [mozilla/web-ext#3124]
During the drafting process for the web-ext 8.0.0 release's documentation update, @rebloor [noted that](https://github.com/mozilla/extension-workshop/pull/1842#discussion_r1590492343_) that the "`--id` [seems to have] no purpose in version 8." Upon reviewing the source and running through a couple test cases, I did not see a way to effectively use the `--id` flag in the [current master branch](https://github.com/mozilla/web-ext/commit/83e4f2e45f3dc2d6b634386b15a0d92860fcdca7).

I suggest that we remove the `--id` flag before we formally release version 8.0.0.

<details><summary>

#### Case 1: Using`--id` when submitting a new add-on without an `id` in manifest.json

</summary>

[2024-05-06-test1.zip](https://github.com/mozilla/web-ext/files/15229222/2024-05-06-test1.zip)

```
$ web-ext sign --id "2024-05-06-test1@webext.test"
Building web extension from /Users/current-user/2024-05-06-test1/src

UsageError: Cannot set custom ID 2024-05-06-test1@webext.test - The add-on ID must be specified in the manifest.json file.
```
</details>

<details><summary>

#### Case 2: Using`--id` when signing an add-on with an `id` in manifest.json

</summary>

[2024-05-06-test2.zip](https://github.com/mozilla/web-ext/files/15229223/2024-05-06-test2.zip)

```
$ web-ext sign --id "2024-05-06-test2@webext.test"
Building web extension from /Users/current-user/2024-05-06-test2/src

UsageError: Cannot set custom ID 2024-05-06-test2@webext.test because manifest.json already defines ID ${manifestId}
```

</details>

**Comment by dotproto** [comment]
@willdurand, it looks like you may have been the last person to touch some related code in #2737. Am I missing anything that would necessitate keeping the `--id` flag?

**Comment by Brawlence** [comment]
＜humour＞ So, [as per our lord and saviour XKCD](https://xkcd.com/1172/), it seems that THIS particular change had fucked up my workflow in particular. ＜/humour＞
 
I have [an extension](https://github.com/Brawlence/SIR), for which I use Gitlab's CI/CD to invoke `web-ext sign` on pushes to `master` branch.

The command verbatim is 
```
"web-ext sign --source-dir=./Extension/ --api-key=$WEB_EXT_API_KEY --api-key=$WEB_EXT_API_SECRET --id=\"{3846b265-95c4-4371-9853-86df1b8cbaaa}\""
```
It [had been successful](https://gitlab.com/Brawlence/SIR/-/jobs/6169391747#L49) in submitting the version updates last year.

Today the same command [fails](https://gitlab.com/Brawlence/SIR/-/jobs/9193339437#L68).

---
If I remove the `--id=\"{3846b265-95c4-4371-9853-86df1b8cbaaa}\""` part it [predictably fails](https://gitlab.com/Brawlence/SIR/-/jobs/9213323102#L49) with the notion `"No extension ID specified (it will be auto-generated the first time)"`.

But this is not the first time. 
The extension already has its ID. 

I'm just not putting it into the `manifest.json` cause I submit same those exact files to Google ExtStore!
