### ISSUE TITLE
Documentation is broken

### ISSUE THREAD

**Issue by andywillis** [mozilla/web-ext#3148]
### Is this a feature request or a bug?

Bug

### What is the current behavior?

[Links to documentation](https://github.com/mozilla/web-ext?tab=readme-ov-file#documentation) on https://extensionworkshop.com/ from the README get the following error.

```
<Error>
  <Code>NoSuchKey</Code>
  <Message>The specified key does not exist.</Message>
  <Details>
    No such object: extensionworkshop-prod-bucket/documentation/develop/web-ext-command-reference
  </Details>
</Error>
```
### What is the expected or desired behavior?

Working documentation links

**Comment by garnetred** [comment]
@willdurand I was looking through the documentation recently and noticed this issue as well. I was hoping to submit a fix, but I wanted to check to see if you're working on this before doing so.

**Comment by garnetred** [comment]
I went ahead and created a new issue and a [pull request](https://github.com/mozilla/web-ext/pull/3153) for it.
