### ISSUE TITLE
sign will not update "Summary" and "Homepage" after the first run

### ISSUE THREAD

**Issue by ildella** [mozilla/web-ext#3151]
### Is this a feature request or a bug?
It might be both... 

### What is the current behavior?
When I first run "web-ext sign --channel=unlisted" a new addon is created, eg at `https://addons.mozilla.org/en-US/developers/addon/frankiegpt`

Here the Summary value is taken from the manifest.json `description` field. 
At each following sign for a new version, the Summary stay the same, despite the description field changes in manifest.json

### What is the expected or desired behavior?
I Would expect description value to be copied and shown as the Summary at each new sign/upload.  
Same behavior for the manifest.json `homepage_url` property.

### Version information (for bug reports)

```
node --version && npm --version && web-ext --version
v22.2.0
10.8.0
8.0.0
```

**Comment by willdurand** [comment]
I chatted with @eviljeff and that is kinda expected. AMO won't overwrite the summary, etc. from what can be found in the `manifest.json` file. It's only using the values from the manifest when no other value is provided and only when the add-on is created for the first time (i.e. for the very first version).

To update the values, you should use the metadata JSON file: https://extensionworkshop.com/documentation/develop/web-ext-command-reference/#web-ext-sign
