### ISSUE TITLE
Some modules are missing from `dependencies`

### ISSUE THREAD

**Issue by NekR** [mozilla/web-ext#318]
See this: https://github.com/mozilla/sign-addon/issues/111
You have the same problem, modules like `when`, `which` and few other are missing from `dependencies` so had to install them manually.

**Comment by kumar303** [comment]
I added more info in https://github.com/mozilla/sign-addon/issues/111#issuecomment-228779508 ; your npm is out of date which is causing an installation bug. You will need a newer npm, as stated in the install instructions for web-ext: https://github.com/mozilla/web-ext#installation-from-npm Specifically, npm 3.x or higher is required.
