### ISSUE TITLE
Allow programatically signing from an xpi file

### ISSUE THREAD

**Issue by kewisch** [mozilla/web-ext#3241]
### Is this a feature request or a bug?
Feature request

### What is the current behavior?

Programmatically, the only way to sign is using `webExt.cmd.sign`, which also does a build. https://github.com/mozilla/sign-addon is deprecated, likely because it was included in utils/submit-addon.js. There doesn't seem to be a way to trigger a submission for an existing xpi.

### What is the expected or desired behavior?

If we add utils/submit-addon to exports, I'd be able to use it directly. I'm open to other ideas.

**Comment by kewisch** [comment]
I realized I can just `import { signAddon as signAddonV5 } from "../node_modules/web-ext/lib/util/submit-addon.js";` which seems to be getting me what I want, but if you are ok adding a named shortcut I can spin up a PR.

**Comment by Rob--W** [comment]
We're in favor of allowing zip files to be signed. A more generic issue was filed at #3242, to offer a CLI option to do the same.

I'm inclined to only accept zip files and not xpi files to avoid accidentally submitting a signed file again, but I am willing to consider xpi files if there is a compelling use case.

> I realized I can just `import { signAddon as signAddonV5 } from "../node_modules/web-ext/lib/util/submit-addon.js";` which seems to be getting me what I want, but if you are ok adding a named shortcut I can spin up a PR.

Patches are welcome!

**Comment by kewisch** [comment]
> I'm inclined to only accept zip files and not xpi files to avoid accidentally submitting a signed file again, but I am willing to consider xpi files if there is a compelling use case.
Might be worth rather checking for an existing signature, or failing on the server side if a signed file is uploaded. zip vs xpi is really just a file extension, so I don't think it makes a difference.

I'll send a PR soon
