### ISSUE TITLE
Build to zip files by default

### ISSUE THREAD

**Issue by kumar303** [mozilla/web-ext#325]
Since [AMO supports zip files](https://github.com/mozilla/addons-server/issues/2727) as well as Firefox (as temporary installs) and Chrome, we might as well build to zip as the default rather than `.xpi`.

**Comment by kumar303** [comment]
When this lands, the MDN docs should get updated because they mention XPI all over the place

**Comment by tofumatt** [comment]
Cool, any chance you know the relevant pages? I'll gladly go through and update 'em.

**Comment by kumar303** [comment]
They are mentioned in a couple places, just search for "xpi" in https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Getting_started_with_web-ext and https://developer.mozilla.org/en-US/Add-ons/WebExtensions/web-ext_command_reference

**Comment by tofumatt** [comment]
Updated the docs.

**Comment by kumar303** [comment]
Looks great, thanks. I'll remove the docs label
