### ISSUE TITLE
Add a logger

### ISSUE THREAD

**Issue by kumar303** [mozilla/web-ext#33]
We need a logger for all web-ext commands, one that can be configured for verbose logging.

**Comment by muffinresearch** [comment]
Having been using bunyan on addons-linter I quite like it and would recommend it. It's very easy to use and has configurable levels. Also has a binary for nicer formatting of the messages which is useful sometimes.

**Comment by kumar303** [comment]
Note to self: it would be nice if `web-ext` dumped a verbose error log in the case of an unexpected exception.

**Comment by kumar303** [comment]
> it would be nice if web-ext dumped a verbose error log in the case of an unexpected exception.

We could use `bunyan.RingBuffer` for this
