### ISSUE TITLE
Can not install add-on because it appears corrupt

### ISSUE THREAD

**Issue by dotnetCarpenter** [mozilla/web-ext#3307]
### Is this a feature request or a bug?
Bug
### What is the current behaviour?
Can not install add-on because Firefox says it appears corrupt.

Produced zip with `web-ext build --overwrite-dest`:
[filtrer_sport-2024.11.20.zip](https://github.com/user-attachments/files/17833037/filtrer_sport-2024.11.20.zip)

Repo: https://github.com/dotnetCarpenter/filtrer-sport/

`npm run lint` reports no error.
```
web-ext lint -a web-ext-artifacts/
Validation Summary:

errors          0              
notices         0              
warnings        0 
```

### What is the expected or desired behaviour?
That the linter reports an error or that the add-on will install.

### Version information (for bug reports)
web-ext: 8.3.0
node: v20.18.0
npm: 10.9.0

- **Firefox version**: Mozilla Firefox 128.3.1esr
- **Your OS and version**: Distributor ID:	Kali
Description:	Kali GNU/Linux Rolling
Release:	2024.4
Codename:	kali-rolling

Might be related: #847, #1164

**Comment by dotnetCarpenter** [comment]
My add-on works fine with `web-ext run`. It's only the build process that does not produce the correct result.

**Comment by willdurand** [comment]
did you submit your add-on to AMO to get it signed?

**Comment by dotnetCarpenter** [comment]
@willdurand  I didn't submit it yet. I thought to test it out locally first and perhaps make some improvements before publishing. I found https://extensionworkshop.com/documentation/develop/temporary-installation-in-firefox/ but it was not obvious on https://extensionworkshop.com/. In other words - difficult to find.

Thanks for pointing me in the right direction.

**Comment by Utopiah** [comment]
Unfortunately `about:debugging` isn't available on mobile. Any hint at how to install an unsigned extension in that context?
