### ISSUE TITLE
`web-ext build` generates `.tgz` file instead of `.zip` file

### ISSUE THREAD

**Issue by DavidC0rtes** [mozilla/web-ext#3316]
### Is this a feature request or a bug?
bug
### What is the current behavior?
Whenever running `web-ext build` on my extension's root directory, the command generates a .tgz file instead of .zip file.

1. `web-ext build --verbose`

### What is the expected or desired behavior?
According to https://extensionworkshop.com/documentation/publish/package-your-extension/  the generated file should be a zip file
### Version information (for bug reports)

- **Firefox version**: 132.0.2
- **Your OS and version**: arch linux 6.11.9
- Paste the output of these commands:

```
node --version && npm --version && web-ext --version
```
v20.11.1
9.11.0 <- I'm using pnpm instead of npm
8.3.0

**Comment by Rob--W** [comment]
`web-ext build` can only generate zip files (or xpi files if you customize the output name - [source](https://github.com/mozilla/web-ext/blob/08b020229121f4f278c58bb47e6ec9a36b64c1ce/src/cmd/build.js#L104)). If you're getting a tgz file, then it was not generated by `web-ext`. If you still have reason to believe that `web-ext` generated the output, can you run `web-ext build --verbose` and share the log output?

**Comment by DavidC0rtes** [comment]
@Rob--W I found the problem, my `package.json` script was conflicting with a reserved script (`pnpm pack`).
```json5
"scripts": {
    "pack": "web-ext build --verbose --overwrite-dest",
  }
```
Doing `pnpm run pack` solved the issue, just running web-ext directly from `node_modules` also works as expected.
