### ISSUE TITLE
`npm run lint` should not use file caching

### ISSUE THREAD

**Issue by kumar303** [mozilla/web-ext#339]
The day to day development command, `npm start`, needs to use file caching for linting so that the watch-retest loop is fast. The `npm run lint` command uses the same caching -- we should prevent it from using any caching at all. This direct linting command should allow you to circumvent caching. 

Currently, the only way to escape caching is to `rm -fr node_modules/grunt-newer/.cache/*`. Sometimes the cache gets outdated in odd scenarios.

**Comment by kumar303** [comment]
I can mentor this

**Comment by shubheksha** [comment]
@kumar303, I would like to work on this!

**Comment by kumar303** [comment]
@shubheksha great! Let me know if you have questions about how to get started. This file has some tips: https://github.com/mozilla/web-ext/blob/master/CONTRIBUTING.md

The file caching is done by [newer:eslint](https://github.com/mozilla/web-ext/blob/master/Gruntfile.js#L56). The fix for `npm run lint` is to make it execute `eslint` instead of `newer:eslint`. However, we still want the [test](https://github.com/mozilla/web-ext/blob/master/Gruntfile.js#L38) command to execute `newer:eslint`.

**Comment by shubheksha** [comment]
@kumar303, from what I understood, there will be two separate linting tasks -- one will use `eslint` and another will use `newer:eslint` & be used with in the test command array. Am I going in the right direction?

**Comment by kumar303** [comment]
Yeah, I think that's right. You may be able to simply replace [this nested command](https://github.com/mozilla/web-ext/blob/master/Gruntfile.js#L38) with `newer:eslint`, i.e. without having to create a separate grunt task for it. You'll have to play around with it and see what works. When testing it locally, check your `node_modules/grunt-newer/.cache/` folder to see if it's using the cache or not.

**Comment by shubheksha** [comment]
I tried installing web-ext from source multiple times, but I am running into the errors as stated in the screen shot repeatedly.
![image](https://cloud.githubusercontent.com/assets/7693422/17649668/3a9ea7f0-6258-11e6-8d03-d2225f3a057d.png)

I tried [this](http://stackoverflow.com/questions/21168141/cannot-install-packages-using-node-package-manager-in-ubuntu) solution as well as creating a sym link for node & nodejs, but nothing worked. What can be the issue?

**Comment by pdehaan** [comment]
@shubheksha What version of node+npm are you using (`$ node --version && npm --version`). It looks like it may be failing on `const` keyword, but I believe that **web-ext** requires Node 4+ (per https://github.com/mozilla/web-ext#installation-from-source).

The other weird part is that your screenshot says:

> _"Error: Cannot find module `fs.realpath`"_

... But according to [the Node.js `fs.realpath()` docs](https://nodejs.org/api/fs.html#fs_fs_realpath_path_options_callback), that API has been around since Node v0.1.31.

**Comment by shubheksha** [comment]
@pdehaan, I realised that the versions were messed up. I fixed that, but still there is an issue with the `_baseMerge` module; it isn't found hence the `npm run build

**Comment by shubheksha** [comment]
@pdehaan, I realised that the versions were messed up. I fixed that, but still there is an issue with the _baseMerge module; it isn't found hence the `npm run build` fails. I've attached the debug log & the screenshot for reference. 
![image](https://cloud.githubusercontent.com/assets/7693422/17660308/3437abb6-62f6-11e6-8d45-8f442f0a5cad.png)


[log.txt](https://github.com/mozilla/web-ext/files/417790/log.txt)

**Comment by kumar303** [comment]
Thanks for the verbose logging but I can't see anything obvious that's wrong here. I tried using your exact Node and npm versions and I was able to install and build without any errors. The log shows that it's having trouble executing grunt but I'm not sure why. In case you had switched Node versions, I would recommend completely re-installing `web-ext` just to be sure it's installed okay. Re-installing can be done like this:
````
cd /path/to/source/web-ext
rm -fr node_modules
npm install
````

**Comment by pdehaan** [comment]
The curious thing about the screenshot is the error message of:

> _"Cannot find module './_baseMerge'"_

I can't find any references to `_baseMerge` via `git grep` or `grep -irn` in our code. As far as I can tell, it's coming from the lodash module.

**Comment by shubheksha** [comment]
I've no clue what the problem was, but after reinstalling twice, it worked!

**Comment by kumar303** [comment]
ah, ok, great! Yes, when bouncing between different Node and NPM versions, it's possible to get trapped with a non-functioning `node_modules` directory. Let me know if you run into any other snags and thanks again for working on this patch.

**Comment by shubheksha** [comment]
I had one doubt - when running `npm run lint`, should the `node_modules/grunt-newer/.cache/` be deleted automatically so that it isn't used? I ran `npm start` & 'npm test

**Comment by shubheksha** [comment]
I had one doubt - when running npm run lint, should the node_modules/grunt-newer/.cache/ be deleted automatically so that it isn't used? I ran npm start & `npm test` & I am able to see the `.cache` directory, but I am confused as to what's it expected behaviour after making the required changes in order to resolve the issue.

**Comment by kumar303** [comment]
When running `npm run lint`, the `grunt-newer/.cache/` directory shouldn't exist at all (it should not be explicitly deleted though). More importantly, the `npm run lint` task should just never invoke the [newer:eslint](https://github.com/mozilla/web-ext/blob/master/Gruntfile.js#L56) task. It should only invoke `eslint`.

**Comment by shubheksha** [comment]
I changed the [newer:eslint](https://github.com/mozilla/web-ext/blob/master/Gruntfile.js#L56) to `eslint` & [lint](https://github.com/mozilla/web-ext/blob/master/Gruntfile.js#L38) to `newer:eslint`, but the `.cache` still exists while running `npm run lint`.

**Comment by kumar303** [comment]
Try manually deleting `.cache` before running `lint`. If it doesn't get created again then that's what you want.
