### ISSUE TITLE
Support using a proxy to access the signing API

### ISSUE THREAD

**Issue by kumar303** [mozilla/web-ext#345]
We need to expose an option like `sign --api-proxy http://yourproxy:6000` for those who need to use a proxy. This requires https://github.com/mozilla/sign-addon/issues/49

**Comment by kumar303** [comment]
It seems to be a common need. See also: https://github.com/mozilla-jetpack/jpm/issues/446

**Comment by kumar303** [comment]
I'm nominating this as a good first bug because the hard work has already been done in mozilla/sign-addon#49

The tasks required are:
* Add a new command line option like `--api-proxy`
* Pass the proxy parameter to [signAddon()](https://github.com/mozilla/web-ext/blob/2c06dbd892feb02bd69a0345bee2b4d2d98233b1/src/cmd/sign.js#L97-L107)
* Write a test to make sure the new parameter is passed

**Comment by berraknil** [comment]
Hi @kumar303  I would like to work on this if possible?

**Comment by kumar303** [comment]
Hi! That would be great. Let me know if you have any questions about the task description, as outlined above.

**Comment by berraknil** [comment]
Hi again @kumar303 sorry but I messed something up while trying to open a new pull request for the changes I did for this fix and it somehow merged it with my previous pull request, I don't know  how to cancel or delete that, since it has nothing to do  with the first pull request. Sorry for the inconvenience :/

**Comment by berraknil** [comment]
Reverted changes back to the way they are so it looks good for now, sorry again for the mess up.

**Comment by kumar303** [comment]
No problem. The easiest way to work on two features at once is to keep each one in an [isolated topic branch](https://git-scm.com/book/en/v2/Git-Branching-Branching-Workflows) (note that we only use a `master` branch on web-ext, not a `develop` branch).

**Comment by kumar303** [comment]
I documented this new option: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/web-ext_command_reference?document_saved=true#--api-proxy
