### ISSUE TITLE
errors during installation web-ext on Windows

### ISSUE THREAD

**Issue by oxidian24** [mozilla/web-ext#348]
I am using Windows XP, I followed the steps described here:
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Getting_started_with_web-ext

npm install --global npm

C:\Documents and Settings\Administrator\Data aplikací\npm\npm -> C:\Documents and Settings\Administrator\Data aplikací\npm\node_modules\npm\bin\npm-cli.js
npm@3.10.3 C:\Documents and Settings\Administrator\Data aplikací\npm\node_modules\npm

U:\addons\test3>npm install --global web-ext
npm **WARN optional dep failed**, continuing fsevents@1.0.12

> spawn-sync@1.0.15 postinstall C:\Documents and Settings\Administrator\Data aplikací\npm\node_modules\web-ext\node_modules\fx-runner\node_modules\spawn-sync
> node postinstall

> dtrace-provider@0.6.0 install C:\Documents and Settings\Administrator\Data aplikací\npm\node_modules\web-ext\node_modules\bunyan\node_modules\dtrace-provider
> node scripts/install.js

C:\Documents and Settings\Administrator\Data aplikací\npm\web-ext -> C:\Documents and Settings\Administrator\Data aplikací\npm\node_modules\web-ext\bin\web-ext
web-ext@1.1.0 C:\Documents and Settings\Administrator\Data aplikací\npm\node_modules\web-ext
├── es6-error@3.0.0
├── es6-promisify@4.1.0 (es6-promise@3.2.1)
├── debounce@1.0.0 (date-now@1.0.1)
├── tmp@0.0.28 (os-tmpdir@1.0.1)
├── minimatch@3.0.2 (brace-expansion@1.1.5)
├── stream-to-promise@2.1.1 (stream-to-array@2.3.0, any-promise@1.3.0)
├── mz@2.4.0 (object-assign@4.1.0, thenify-all@1.6.0, any-promise@1.3.0)
├── source-map-support@0.4.0 (source-map@0.1.32)
├── zip-dir@1.0.2 (async@1.5.2, jszip@2.6.0)
├── yargs@4.7.1 (decamelize@1.2.0, y18n@3.2.1, camelcase@3.0.0, set-blocking@1.0
.0, require-main-filename@1.0.1, window-size@0.2.0, lodash.assign@4.0.9, yargs-p
arser@2.4.0, os-locale@1.4.0, string-width@1.0.1, cliui@3.2.0, pkg-conf@1.1.3, r
ead-pkg-up@1.0.1)
├── node-firefox-connect@1.2.0 (es6-promise@2.3.0, firefox-client@0.3.0)
├── bunyan@1.8.1 (safe-json-stringify@1.0.3, mv@2.1.1, dtrace-provider@0.6.0, mo
ment@2.14.1)
├── fx-runner@1.0.3 (winreg@0.0.12, commander@2.9.0, fs-promise@0.3.1, which@1.2
.4, when@3.7.7, spawn-sync@1.0.15, lodash@3.10.1)
├── sign-addon@0.0.4 (deepcopy@0.6.3, when@3.7.7, request@2.72.0, jsonwebtoken@7
.0.1)
├── firefox-profile@0.4.0 (ini@1.3.4, jetpack-id@1.0.0, async@1.5.2, adm-zip@0.4
.7, node-uuid@1.4.7, minimist@1.2.0, xml2js@0.4.17, lazystream@1.0.0, archiver@1
.0.0, fs-extra@0.30.0, lodash@4.12.0)
├── watchpack@1.1.0 (graceful-fs@4.1.4, chokidar@1.6.0, async@2.0.0-rc.4)
└── babel-polyfill@6.9.1 (regenerator-runtime@0.9.5, babel-runtime@6.9.2, core-j
s@2.4.0)

U:\addons\test3>web-ext
Error: **Cannot find module 'any-promise'**
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Documents and Settings\Administrator\Data aplikací\npm\node_modules\web-ext\node_modules\sign-addon\dist\sign-addon.js:227:19)
    at __webpack_require__ (C:\Documents and Settings\Administrator\Data aplikací\npm\node_modules\web-ext\node_modules\sign-addon\dist\sign-addon.js:22:30)
    at Object.<anonymous> (C:\Documents and Settings\Administrator\Data aplikací\npm\node_modules\web-ext\node_modules\sign-addon\dist\sign-addon.js:163:16)
    at __webpack_require__ (C:\Documents and Settings\Administrator\Data aplikací\npm\node_modules\web-ext\node_modules\sign-addon\dist\sign-addon.js:22:30)
    at Object.<anonymous> (C:\Documents and Settings\Administrator\Data aplikací\npm\node_modules\web-ext\node_modules\sign-addon\dist\sign-addon.js:57:12)
    at __webpack_require__ (C:\Documents and Settings\Administrator\Data aplikací\npm\node_modules\web-ext\node_modules\sign-addon\dist\sign-addon.js:22:30)

I try to run it but it prints error Cannot find module 'any-promise'. I did not find any log so if you know where it should be place, tell me.

**Comment by kumar303** [comment]
Hmm, this is an error that seems to only happen with npm less than version 3 (but I see that you have 3.10.3). Is it possible that you installed `web-ext` once already before upgrading npm? To be sure, you could try this:
````
npm uninstall --global web-ext
npm install --global web-ext
````
Also, what version of node are you using?

**Comment by oxidian24** [comment]
I have npm 2.15.8 where can I get new version? I have installed npm from nodejs according tutorial from Mozilla. I used only the reference from Mozilla so if I installed old version then somebody should update the links.

**Comment by kumar303** [comment]
The instructions are correct (I think). This command will upgrade your npm, did it not?

    npm install --global npm

You can check the version like this:

    npm --version

I suggested to re-install web-ext because if you had installed it before upgrading your npm then you would still have trouble. It won't hurt to try it:
````
npm uninstall --global web-ext
npm install --global web-ext
````

**Comment by oxidian24** [comment]
This is exactly what I did.
npm -v
2.15.8
So the command failed to update the npm. I did these steps yesterday, so I need not to repeat them. The basic problem is that the command 
npm install --global npm
fails to update npm to current version.

**Comment by kumar303** [comment]
OK, I see. I don't have Windows to test on but I think you just need to adjust your PATH so that it picks up the new npm version. This seems like a solution: http://stackoverflow.com/a/26908900

**Comment by kumar303** [comment]
I updated the readme for this! https://github.com/mozilla/web-ext/commit/4fb7431cbb7b2ec7f8dd163c78ff596b84f3eb92

**Comment by oxidian24** [comment]
I don't have these path as described in the solution. My path
P:\my\path\nodejs
includes:
- node_modules <DIR>
- node.exe
- npm
+ man pages
P:\my\path\nodejs\node_modules\npm
includes:
- bin <DIR>
- lib <DIR>
- node_modules <DIR>
- scripts
and some files like package.json etc
P:\my\path\nodejs\node_modules\npm\bin
includes:
- node-gyp-bin <DIR>
- npm-cli.js
- read-package-json.js
- npm.cmd
- npm

So in my case, there is no directory like npm.cmd

I was warned not to use local installation, because global installation is recommened. So you say, I should change PATH? My PATH contains these item (separated to lines for easy reading):
C:\Documents and Settings\Administrator\Data aplikací\npm
C:\Documents and Settings\Administrator\Data aplikací\npm\node_modules\jpm
C:\Documents and Settings\Administrator\Data aplikací\npm\node_modules\jpm\node_modules\.bin

Yet under is etc <DIR>, jpm.cmd <batch file>, npm.cmd <batch file> etc.
and one more directory:
C:\Documents and Settings\Administrator\Data aplikací\npm\node_modules\npm
also contains lib and bin directories, node_modules and a lot of files and directories.

I think that the directory P:\my\path\nodejs\node_modules\npm is the path from where the original version installed, because it is under nodejs and I know the npm installation is inside the nodejs installation. A lot of folders, quite complicated.

**Comment by kumar303** [comment]
I'm not sure what you should do. Maybe try running Microsoft's npm upgrade tool? https://github.com/felixrieseberg/npm-windows-upgrade

**Comment by oxidian24** [comment]
I cannot use Powershell, this program is not installed on my computer and the tool uses it. But I found solution.

It explains this link (please remove the link to stackoverslow from docs, and supply this one):
https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows
I said, there are more directories on my comupter with npm, so I decided to test from the directory itself. As I am lazy guy so I created shortcut (delegate/simlink or whatever you call it at English) for cmd shell first in the directory
C:\Documents and Settings\Administrator\Data aplikací\npm
as this is the directory for global installation, which I am using. Then I change working path of the the delagate/shortcut/simlink (I just delete the %windir% value from "run in" field... And then I start the cmd from current directory which is once again
C:\Documents and Settings\Administrator\Data aplikací\npm
then I type npm -v
and it prints 3.10.3 so it is clear here is the current version.

No I rename the old version from
P:\my\path\nodejs\node_modules\npm
to P:\my\path\nodejs\node_modules\npm.old
and then I rename
P:\my\path\nodejs\npm.cmd.old
P:\my\path\nodejs\npm.old
and then I again type in cmd console:
cd \
npm -v
and it prints:
3.10.3
so now it works and I can remove the directories which I have renamed.

They described it in the troubleshooting guide but I thought these should be directories. And they are files, not directories. So it is better to make sure like this because now I knew what I am doing.

**Comment by kumar303** [comment]
ok, I'll fix the link. Glad you got it working!

**Comment by oxidian24** [comment]
Yet a note: installation of web-ext seemed OK, but one warning on the very end:

npm WARN optional Skipping failed optional dependency /web-ext/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12

web-ext seems to be working, version 1.1.0 installed (I will try how it works later)

**Comment by kumar303** [comment]
Those skipped modules were just for optimizations (I think) so you should be okay. One thing to try is `web-ext run` which auto-reloads your extension. This might be impacted by a missing `fsevents` but hopefully not.
