### ISSUE TITLE
Document the non-CLI version (JS API for web-ext)

### ISSUE THREAD

**Issue by pdehaan** [mozilla/web-ext#381]
Is there a way to do a `require("web-ext")` and build + sign web extensions using Node.js instead of using this via Terminal?

**Comment by kumar303** [comment]
Yeah, sure. It needs to be documented though. You'd use it like this (in ES6):
````javascript
import build from 'web-ext/cmd/build';
import signAddon from 'sign-addon';

build({sourceDir: '.', artifactsDir: '/tmp'})
  .then((buildResult) => {
    console.log(buildResult);
    return signAddon({
      apiKey: '...', apiSecret: '...',
      xpiPath: buildResult.extensionPath,
    });
  })
  .then((signingResult) => {
    console.log(signingResult);
  })
  .catch((error) => {
    throw error;
  });
````
Or in ES5:
````javascript
var build = require('web-ext/cmd/build').default
var signAddon = require('sign-addon').default;

build({sourceDir: '.'}).then(function(buildResult) {
  console.log(buildResult);
  return signAddon({apiKey: '...', apiSecret: '...'});
});
````
The [sign-addon](https://github.com/mozilla/sign-addon/) module which already has documentation for programmatic use.

**Comment by kumar303** [comment]
I'm nominating this as a good first bug because it just involves taking the following code up above, testing them manually, and adding them to a new section [in the docs](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Getting_started_with_web-ext).

**Comment by berraknil** [comment]
I'd like to work on this next, if no one else is?

**Comment by kumar303** [comment]
@berraknil yes, for sure! Thank you. Let me know if you have any questions.

**Comment by kewisch** [comment]
@berraknil how are things going? We haven't heard from you in a while. Are you still interested in working on this issue?

**Comment by wagnerand** [comment]
If anyone wants to work on this issue, feel free to do so.

**Comment by Revanth47** [comment]
Can I take up this issue if no one else is?

**Comment by wagnerand** [comment]
@Revanth47 go for it!

**Comment by kumar303** [comment]
@Revanth47 yes, thank you! I would suggest by starting it as a patch to [README.md](https://github.com/mozilla/web-ext/blob/master/README.md), then we can move it to the [MDN documentation](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Getting_started_with_web-ext) later after some peer review.

**Comment by wagnerand** [comment]
Mentor: @kumar303

**Comment by erikvold** [comment]
@kumar303 your example no longer works, mind updating it?

**Comment by erikvold** [comment]
I get this error `SyntaxError: Unexpected token import` using node version 7.6.0, isn't this because the module needs to be babeled? @kumar303

**Comment by erikvold** [comment]
I think this issue needs to be renamed to "Provide a js api".

**Comment by kumar303** [comment]
Until this gets documented, I added a link to an example in https://github.com/mozilla/web-ext/issues/683#issuecomment-285180904

**Comment by wagnerand** [comment]
@Revanth47 are you still working on this?

**Comment by iaptsiauri** [comment]
Hi, I would like to work one this one :) if it is still possible

**Comment by kumar303** [comment]
@iaptsiauri yes, thank you. See https://github.com/mozilla/web-ext/issues/683#issuecomment-285180904 for how it works and let me know if you have questions.

**Comment by Rahmeen14** [comment]
Hi! I would like to work on this as my first issue.

**Comment by kumar303** [comment]
Hi @Rahmeen14, that would be really helpful! All you have to do is add this PR description to the README https://github.com/mozilla/web-ext/pull/1028

**Comment by Balaji2198** [comment]
@kumar303  I would like to take this up. 
May I know after which line number of ReadMe I have to add the description?

**Comment by kumar303** [comment]
Hi. Thanks. You can add it after the installation section.

**Comment by Balaji2198** [comment]
@kumar303 I think @Rahmeen14 Just sent a PR for this. Is that Fix this issue? 
I would also ready to take other Good First Bugs. Let me know if there any.
