### ISSUE TITLE
Running web-ext lint throws: ENFILE: file table overflow

### ISSUE THREAD

**Issue by pdehaan** [mozilla/web-ext#396]
Using Mac OS X 10.11.6
Node 6.3.0
npm 3.10.3

---

I'm using a locally installed version of **web-ext@1.3.0** (latest), and I seem to be getting errors when trying to run `$ web-ext lint`:

```sh
$ ./node_modules/.bin/web-ext --version # 1.3.0
$ npm info web-ext version # 1.3.0
```

1. Tried running `$ web-ext lint` and using default `--source-dir`:
    ```sh
$ ./node_modules/.bin/web-ext lint

Error: ENFILE: file table overflow, open '/Users/pdehaan/dev/github/mozilla/blok/node_modules/es5-ext/test/object/validate-array-like-object.js'
    at Error (native)
```

1. Tried running `$ web-ext lint .` and specifying the current working directory as source dir:
    ```sh
$ ./node_modules/.bin/web-ext lint .

Error: ENFILE: file table overflow, open '/Users/pdehaan/dev/github/mozilla/blok/node_modules/es5-ext/test/object/validate-array-like.js'
    at Error (native)
```

1. Tried running `$ web-ext lint --source-dir=.` and explicitly setting `--source-dir`:
    ```sh
$ ./node_modules/.bin/web-ext lint --source-dir=.

Error: ENFILE: file table overflow, open '/Users/pdehaan/dev/github/mozilla/blok/node_modules/es5-ext/test/object/copy.js'
    at Error (native)
```

1. Tried running `$ web-ext lint ./web-ext-artifacts/blok-0.1.7.zip` and passing a name of a file to lint:
    ```sh
$ ./node_modules/.bin/web-ext lint ./web-ext-artifacts/blok-0.1.7.zip

Error: ENFILE: file table overflow, open '/Users/pdehaan/dev/github/mozilla/blok/node_modules/es5-ext/test/object/valid-callable.js'
    at Error (native)
```

    This is how I'd generally use `addons-linter` directly:
    ```sh
$ ./node_modules/.bin/addons-linter ./web-ext-artifacts/blok-0.1.7.zip --pretty

{
    "count": 0,
    "summary": {
        "errors": 0,
        "notices": 0,
        "warnings": 0
    },
    "metadata": {
        "id": "blok@mozilla.org",
        "manifestVersion": 2,
        "name": "Blok",
        "type": 1,
        "version": "0.1.7",
        "emptyFiles": [],
        "jsLibs": {}
    },
    "errors": [],
    "notices": [],
    "warnings": []
}
```

1. Tried running `$ web-ext lint ./web-ext-artifacts/blok-0.1.6-fx.xpi` with a signed XPI:
    ```sh
$ ./node_modules/.bin/web-ext lint ./web-ext-artifacts/blok-0.1.6-fx.xpi

Error: ENFILE: file table overflow, open '/Users/pdehaan/dev/github/mozilla/blok/node_modules/es5-ext/test/object/validate-array-like-object.js'
    at Error (native)
```

1. Tried running `$ npm run lint` (where my "lint" task is `"web-ext lint"`):
    ```sh
$ npm run lint

> blok@1.0.0 lint /Users/pdehaan/dev/github/mozilla/blok
> web-ext lint

Error: ENFILE: file table overflow, open '/Users/pdehaan/dev/github/mozilla/blok/node_modules/es5-ext/string/raw/shim.js'
    at Error (native)

npm ERR! Darwin 15.6.0
```

    ```sh
$ npm run
Lifecycle scripts included in blok:
  ...

available via `npm run-script`:
  lint
    web-ext lint
```

**Comment by kumar303** [comment]
How many files (roughly) are in your source directory? Sounds like you're hitting some kind of limit. You may need to adjust [ulimit settings](http://unix.stackexchange.com/questions/108174/how-to-persist-ulimit-settings-in-osx-mavericks).

**Comment by pdehaan** [comment]
@kumar303 The repo is pretty small: https://github.com/mozilla/blok
I'll take a look at tweaking ulimit settings when I get into the office.

**Comment by kumar303** [comment]
Hmmm. I cloned the repo and I see 8 XPI files in the artifacts dir. I suspect that the linter is parsing each one of those as nested extensions. This is something I hadn't thought about. We probably need to tell the linter to ignore the artifacts directory.

**Comment by kumar303** [comment]
Also, btw, the `lint` command does not accept an argument -- that has no effect. Specifying an argument should probably be an error to avoid confusion.

**Comment by kumar303** [comment]
Actually, it's the `node_modules` directory causing the "file table overflow" problem. I can reproduce it in your repo after `npm install`. We need to tell the linter to ignore that. I filed https://github.com/mozilla/web-ext/issues/397

**Comment by pdehaan** [comment]
> Also, btw, the `web-ext lint` command does not accept an argument -- that has no effect. Specifying an argument should probably be an error to avoid confusion.

Ah cool, thanks. I was thinking maybe it would be the same as running `addons-linter` if I specified an argument, so I'd be able to lint specific archives.

But after deleting my /node_modules/ and /web-ext-artifacts/ directories and installing `web-ext` globally, it works and gives me the following [for Blok]:

```sh
$ web-ext lint

Validation Summary:

errors          0
notices         0
warnings        0
```

**Comment by pdehaan** [comment]
Thanks everybody, this now seems to work with **web-ext@1.4.0**!

```sh
$ ./node_modules/.bin/web-ext lint --self-hosted -s=src
Validation Summary:

errors          0
notices         0
warnings        0
```
