### ISSUE TITLE
Ignore unnecessary directories when linting

### ISSUE THREAD

**Issue by kumar303** [mozilla/web-ext#397]
When running `web-ext lint` in a source directory, the linter should ignore the artifacts directory and node_modules directory. Otherwise, it may begin parsing too many files which could lead to errors or unwanted linting results. Maybe there are other non-source directories we should ignore. We can probably re-use the filter rules from [FileFilter](https://github.com/mozilla/web-ext/blob/master/src/cmd/build.js#L96).

See https://github.com/mozilla/web-ext/issues/396

**Comment by pdehaan** [comment]
Is there a way to specify what file(s) get added/excluded from the web extension using `web-ext` (similar to the .jpmignore file)?
Or is that basically the same issue/request as https://github.com/mozilla/web-ext/issues/176?

We have https://github.com/mozilla/blok/issues/69 to audit the files in our generated ZIP/XPI, but I wasn't sure how to exclude things like our /docs/, /web-ext-artifacts/, /tests/, and /coverage/ folders which aren't needed in our web extension.

**Comment by kumar303** [comment]
We only have default ignore rules in place right now, which includes `*.xpi` and `node_modules`. It only applies to the `build` command currently. We should probably add options to the build command to customize it or, yes, a standard ignore file.
