### ISSUE TITLE
Signing an extension ignores artifacts directory

### ISSUE THREAD

**Issue by dev-rke** [mozilla/web-ext#429]
When signing an extension the global parameter "--artifacts-dir=..." is ignored.
See
```
build({sourceDir, artifactsDir: tmpDir.path()}
```
https://github.com/mozilla/web-ext/blob/master/src/cmd/sign.js#L34

I assume the global option should be respected, as described in the docs:
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/web-ext_command_reference#--artifacts-dir_-a

I would like to build my extension, sign it and publish it in a distribution folder, this is currently not possible.

**Comment by kumar303** [comment]
Could you give me an example of how you ran the command? I just tried this and it worked as expected:
````
web-ext sign --artifacts-dir web-ext-artifacts2 --verbose --api-key ... --api-secret ...
````
The signed XPI was downloaded to `web-ext-artifacts2/no_id_extension-1.7-fx+an.xpi`

**Comment by kumar303** [comment]
Also, what version of `web-ext` are you using?

**Comment by dev-rke** [comment]
Hi Kumar,

thanks for your support.
web-ext version is 1.4.0, latest stable release.
Why do you leave out the equal sign for parameters? Are they optional?
Docs say we need them, see e.g.
```
$ web-ext run --source-dir=/another/path/to/source
```
from https://developer.mozilla.org/en-US/Add-ons/WebExtensions/web-ext_command_reference#Setting_option_environment_variables

I also used the ```--artifacts-dir``` parameter as last parameter, maybe this is source of my issue?
Another point, i used the --id parameter to create an update for an existing extension.

**Comment by kumar303** [comment]
The equal signs are optional, yes. Can you provide an example of the full `web-ext sign` command line you used? Just be sure to redact your api key/secret. Putting the `--artifacts-dir` option at the end shouldn't matter.

**Comment by dev-rke** [comment]
Copied from my shell history:
```
$ web-ext sign --api-key=... --api-secret=... --id=... --artifacts-dir=dist
```
It always created a file in /tmp/...

In my first try signing an extension that i didn't understood what the sign process does, i did not realize that it uploads it to AMO. I thought signing is a local process. Now i know better, maybe it should be pointed out a bit more in the docs. ;-)

So my extension was initially uploaded, but with too much data (temporary data in my development folder), so i revoked the uploaded version in the AMO manager.
But then i cannot upload the same extension version again. In the first try i uploaded 0.2.0, revoked 0.2.0, uploaded 0.2.0 again, but it won't get recognized by AMO again. So i needed to update the version information in my manifest to 0.2.1, then everything was uploaded correct.
But the produced xpi still won't be placed in my dist folder, it always was generated in /tmp/, which also the source code indicates (see my first post in this issue).

**Comment by kumar303** [comment]
Thanks for providing the full command. I replicated this command but it works as expected for me; the signed XPI gets saved to `./dist`.

Can you attach a text file of `web-ext sign --verbose` that I could look at?

I'm not sure what could be different. What OS are you on?  What version of the OS? What version of NodeJS are you using?

Here are some other responses:

>  i did not realize that it uploads it to AMO

I don't think it's such an important detail. It creates an unlisted add-on which is invisible to other AMO users. The point is that the command produces a signed XPI.

> So i needed to update the version information in my manifest to 0.2.1

Yes, version numbers need to be unique for each signed XPI you create. If you are signing XPIs continuously for testing, consider using an [unbranded build](https://wiki.mozilla.org/Addons/Extension_Signing#Unbranded_Builds) instead. Otherwise, you can add a random string to end of the version number and it will cause it to be unique each time.

> it always was generated in /tmp/, which also the source code indicates (see my first post in this issue).

The [code you linked to](https://github.com/mozilla/web-ext/blob/master/src/cmd/sign.js#L34) is just an implementation detail. The `sign` command begins by generating an XPI in the tmp folder which it then uploads to AMO. When it retrieves the signed XPI from AMO, it places it in the `--artifacts-dir` and deletes the tmp directory for the unsigned XPI.

**Comment by dev-rke** [comment]
OS + Node:
```
$ uname -a
Linux dev-rke 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
$ node --version
v4.4.7
```

Verbose output follows soon, i am not sure if i will release a new version this night.
Maybe i just did something wrong due to my hassle with the deleted release and did not understand what happens there. ;-)

Thanks for clearifying the issues i had in my first approach.
I didn't read the full node module, just saw there is a tmp folder which is used to build the extension.

**Comment by dev-rke** [comment]
Ok, i just tried to sign a new release, here is the output.
In my first try i forgot to specify the --verbose parameter (*doh*), in the second try the extension already exists on remote endpoint.

```
$ web-ext sign --artifacts-dir dist --api-key ... --api-secret ...
Building web extension from /home/dev-rke/simple-lorem-ipsum
Your web extension is ready: /tmp/tmp-web-ext-152570RWgIRfLacPE/simple_lorem_ipsum-0.2.2.zip
Validating add-on [............................................................]
Validation results: https://addons.mozilla.org/en-US/developers/upload/1ed784de99b64b889fc8cafeba6333a0
Your add-on has been submitted for review. It passed validation but could not be automatically signed because this is a listed add-on.
FAIL

$ web-ext sign --verbose --artifacts-dir dist --api-key ... --api-secret ...
Version: 1.4.0
[util/temp-dir.js][debug] Created temporary directory: /tmp/tmp-web-ext-152706NYoxovl0kDm
[util/manifest.js][debug] Validating manifest at /home/dev-rke/simple-lorem-ipsum/manifest.json
[cmd/build.js][info] Building web extension from /home/dev-rke/simple-lorem-ipsum
[cmd/build.js][debug] Using manifest id=jid0-aU64eWN4jFT0bhC8D6ESFb9yWHw@jetpack
[cmd/sign.js][debug] No ID file found at: /home/dev-rke/simple-lorem-ipsum/.web-extension-id
[cmd/build.js][debug] FileFilter: ignoring file /home/dev-rke/simple-lorem-ipsum/.editorconfig
[cmd/build.js][debug] FileFilter: ignoring file /home/dev-rke/simple-lorem-ipsum/.eslintrc.json
[cmd/build.js][debug] FileFilter: ignoring file /home/dev-rke/simple-lorem-ipsum/.git
[cmd/build.js][debug] FileFilter: ignoring file /home/dev-rke/simple-lorem-ipsum/.gitignore
[cmd/build.js][debug] FileFilter: ignoring file /home/dev-rke/simple-lorem-ipsum/.idea
[cmd/build.js][info] Your web extension is ready: /tmp/tmp-web-ext-152706NYoxovl0kDm/simple_lorem_ipsum-0.2.2.zip
[sign-addon] [API] PUT request:
 { url: 'https://addons.mozilla.org/api/v3/addons/jid0-aU64eWN4jFT0bhC8D6ESFb9yWHw%40jetpack/versions/0.2.2/',
  formData: 
   { upload: 
      ReadStream {
        _readableState: [Object],
        readable: true,
        domain: null,
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        path: '/tmp/tmp-web-ext-152706NYoxovl0kDm/simple_lorem_ipsum-0.2.2.zip',
        fd: null,
        flags: 'r',
        mode: 438,
        start: undefined,
        end: undefined,
        autoClose: true,
        pos: undefined } },
  headers: { Authorization: '<REDACTED>', Accept: 'application/json' } }
[sign-addon] [API] PUT response:
 Status: 409
 { headers: 
   { allow: 'GET, POST, PUT, HEAD, OPTIONS',
     'content-security-policy': 'script-src \'self\' https://addons.mozilla.org https://www.paypalobjects.com https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/ https://ssl.google-analytics.com https://addons.cdn.mozilla.net; default-src \'self\'; img-src \'self\' data: blob: https://www.paypal.com https://ssl.google-analytics.com https://addons.cdn.mozilla.net https://static.addons.mozilla.net https://sentry.prod.mozaws.net; media-src https://videos.cdn.mozilla.net; style-src \'self\' \'unsafe-inline\' https://addons.cdn.mozilla.net; frame-src \'self\' https://ic.paypal.com https://paypal.com https://www.google.com/recaptcha/ https://www.paypal.com; object-src \'none\'; connect-src \'self\' https://sentry.prod.mozaws.net; font-src \'self\' https://addons.cdn.mozilla.net; report-uri /__cspreport__',
     'content-type': 'application/json',
     date: 'Thu, 11 Aug 2016 23:46:03 GMT',
     etag: '"b3ab0c222b3c382f385a6e5f11080ee2"',
     server: 'nginx',
     'set-cookie': '<REDACTED>',
     'strict-transport-security': 'max-age=31536000',
     vary: 'X-Mobile, User-Agent',
     'x-content-type-options': 'nosniff',
     'x-frame-options': 'DENY',
     'x-xss-protection': '1; mode=block',
     'content-length': '35',
     connection: 'Close' },
  response: { error: 'Version already exists.' } }
Server response: Version already exists. (status: 409)
[cmd/sign.js][info] FAIL
[util/temp-dir.js][debug] Removing temporary directory: /tmp/tmp-web-ext-152706NYoxovl0kDm
```

I hope it helps debugging. :-)

**Comment by kumar303** [comment]
Thanks for attaching all the output. I think the confusion here is because your add-on is listed so `web-ext` cannot automatically download a signed version. You will need to wait for a reviewer to approve your new version (you'll get an email about it). I'm closing the issue because the temp file that you pointed it out is expected behavior. This file is used internally by `web-ext`; it is posted to the AMO API. Thanks for taking the time to file a bug report.

**Comment by dev-rke** [comment]
Ok, i can only sign non-listed extensions?
Can I sign my extension and it will be reviewed later?
Hi Kumar,

Can you please provide a link with some more information?

I still do not understand why you think this is the expected behavior. I expect a file in my dist folder.

Thank you very much, have a nice weekend.

**Comment by kumar303** [comment]
> Ok, i can only sign non-listed extensions?

Yes, you can only sign non-listed extensions with the `web-ext` tool. Extensions that are listed on AMO will be automatically signed after they pass review.

> Can I sign my extension and it will be reviewed later?

You would have to make an entirely new add-on (with a unique ID) to do this.

> Can you please provide a link with some more information?

Here is some general information about submitting add-ons to AMO: https://developer.mozilla.org/en-US/Add-ons/Distribution#Submitting_to_AMO

If you are listing your add-on on AMO then you do not need to use `web-ext` to sign the add-on. All you do is submit the version through the AMO website and wait for a review. Once your add-on is approved, it will be signed automatically. Does that make sense? In other words, you only need to use `web-ext sign` if you are distributing your add-on outside of AMO, like on your own website.

**Comment by dev-rke** [comment]
Thanks for clarification.
I want to provide my already in AMO listed addon also in my git repository, e.g. so that other users can download the file without linking to AMO.
How can i do this automatically?
Did i understand you correct, that i would need to define a new unique ID and to provide the XPI as different extension?

**Comment by kumar303** [comment]
You have two options:

1) You can switch your add-on on AMO from listed to unlisted. You should read this to understand all the implications: https://developer.mozilla.org/en-US/Add-ons/Distribution#Switching_between_Listed_and_Unlisted.

2) And, yes, you can change the ID to a new unique ID and submit your add-on via `web-ext sign` and a new unlisted add-on will be created on your AMO dashboard.

**Comment by dev-rke** [comment]
Thank you very much!
