### ISSUE TITLE
Add import linting

### ISSUE THREAD

**Issue by kumar303** [mozilla/web-ext#442]
We can steal the config from https://github.com/mozilla/addons-frontend/pull/945 to get proper import linting in web-ext. Flow has some nice support for this already but I think the linting rules would provide more granularity.

**Comment by kumar303** [comment]
I think that we shouldn't enable import module and name resolution because Flow does a better job at this (for one thing, Flow can handle CommonJS exports). We could use linting for how to group built-in vs local modules though.

**Comment by kumar303** [comment]
Ooh, we need to add this. I just saw a situation where a dependency wasn't required in `package.json` but it was required by another package. This meant flat installation (npm 3) passed all tests but old style installation (npm 2) did not. We should use import linting to catch issues like this instead.

**Comment by shubheksha** [comment]
Flow doesn't adequately check for missing dependencies in `package.json`.
I installed a package, saved it while installing, but after that checked out `package.json` and reset it to it's original state w/o any changes. Flow didn't issue any warnings for this case.

**Comment by rpl** [comment]
@shubheksha yeah, I don't think that Flow will always complain about missing dependency (it is not its job, probably it will complain sometimes, e.g. if the module is part of an `import type`), it is more likely to be something that can be enabled using an eslint plugin (e.g. this one seems promising: https://www.npmjs.com/package/eslint-plugin-import)

**Comment by shubheksha** [comment]
@rpl, in this case it was being imported, but still didn't complain. So using ESLint will definitely be a better option!

**Comment by shubheksha** [comment]
I'll take this one up!
