### ISSUE TITLE
web-ext sign --id does not work with the "extensionname@example.org" format

### ISSUE THREAD

**Issue by Marcelovk** [mozilla/web-ext#479]
Tried with web-ext 1.4.0, with a file without applications.gecko.id in manifest.json

`web-ext sign <addons credentials> --id=extensionname@example.org`

Results: 
new GUID generated in `.web-extension-id` and in `addons.mozilla.org`

Expected results:
a `.web-extension-id` file with extensionname@example.org, just like when using `applications.gecko.id` in `manifest.json`

**Comment by kumar303** [comment]
Huh, I can reproduce this too. Sorry about that. I made a verbose log that will be helpful when fixing this: 
[web-ext-ignored-id.txt](https://github.com/mozilla/web-ext/files/470535/web-ext-ignored-id.txt)


Thanks for the bug report.

**Comment by kumar303** [comment]
@shubheksha tracked this down to a problem in the API itself, d'oh https://github.com/mozilla/addons-server/issues/3801

**Comment by kumar303** [comment]
A fix for this on the API server should go live on Jan 12, 2016. I'll try to test it before then on the dev server (when it's available).

**Comment by kumar303** [comment]
@shubheksha I've lost track of our status page but I think this patch will be on the dev server by now. You can try it with `sign ... --api-url-prefix=https://addons-dev.allizom.org/api/v3`

**Comment by shubheksha** [comment]
I tested this and it's fixed in development. I get the correct id in .web-extension-id. We'll test it in production this Thursday, leaving this bug open till then.

**Comment by willdurand** [comment]
`--id` has been removed in v8.
