### ISSUE TITLE
print a development version when using a custom web-ext build

### ISSUE THREAD

**Issue by kumar303** [mozilla/web-ext#481]
For released versions of web-ext you can type this:

    web-ext --version

And you will see something like `1.4.0` or whatever the current version is.

For development, you should be able to type the same thing and see a development version based on the current commit. For example:

    master-c760a77b83cb732ea2202e00194c0b6492ba2632

This would be the auto-generated version if you had done `npm run build` from https://github.com/mozilla/web-ext/commit/c760a77b83cb732ea2202e00194c0b6492ba2632

This involves the following tasks:
* Adjust [getVersion()](https://github.com/mozilla/web-ext/blob/c760a77b83cb732ea2202e00194c0b6492ba2632/src/program.js#L118) to return a development version
* Ensure that the release build includes a real version number and the development build includes a git commit hash
* Add a test [similar to this one](https://github.com/mozilla/web-ext/blob/c760a77b83cb732ea2202e00194c0b6492ba2632/tests/test.program.js#L315) that verifies this new version feature

**Comment by harshit-knit** [comment]
Hi, I am new to JS community.
build is generated using 'npm run build'.
Help me. How will I check that build is development or release build.
Thanks in advance.

**Comment by kumar303** [comment]
Hi @harshit-knit . Good question. I think we can introduce the [NODE_ENV](http://stackoverflow.com/questions/16978256/what-is-node-env-in-express) variable which is commonly used.

In normal day to day operation, `NODE_ENV` would not be set. If the variable is not set, the version should be derived from master. Example: `master-c760a77b83cb732ea2202e00194c0b6492ba2632`

When we release to production we do so from TravisCI according to our [deploy configuration](https://github.com/mozilla/web-ext/blob/23e59df941f68b2ac77f3b3e8a7e246d3e8f5e5e/.travis.yml#L24-L32). Thus, my thought is to change [this line](https://github.com/mozilla/web-ext/blob/23e59df941f68b2ac77f3b3e8a7e246d3e8f5e5e/.travis.yml#L12) from:

    - COVERAGE=y npm test

to

    - COVERAGE=y NODE_ENV=production npm test

This will ensure that when the github tag gets built by TravisCI, the version will be a [semver](http://semver.org/) release version derived from `package.json`. In all other cases the version will be derived from the current github master commit.
