### ISSUE TITLE
Require spaces around infix operators (for web-ext code)

### ISSUE THREAD

**Issue by kumar303** [mozilla/web-ext#482]
The majority of web-ext code uses spaces around infix operators but this is not enforced. Let's enforce it by adding this rule to `.eslintrc`:
````
"space-infix-ops": "error"
````

This will require fixing up some code after you add the rule, mostly around default parameter assignment.

To test the rule, do: `npm run lint`

**Comment by pdehaan** [comment]
See #483

Autofixed via `$ ./node_modules/.bin/eslint {tasks,tests,src,*.js} --fix`
