### ISSUE TITLE
Release directly to GitHub from TravisCI

### ISSUE THREAD

**Issue by kumar303** [mozilla/web-ext#506]
When you push a git tag upstream, [TravisCI](https://travis-ci.org/) automatically [deploys](https://github.com/mozilla/web-ext/blob/cb50f9faa6655e8d3a3b0d7f14f1ab762b6765f4/.travis.yml#L24-L32) the tag to NPM. We should add an [additional section](https://docs.travis-ci.com/user/deployment/releases/) that publishes a release on GitHub itself.

It will not be possible to fully test this code change. The work involved would be to read the TravisCI docs (linked above) and add the new section to our YAML file as well as update the release process [documentation](https://github.com/mozilla/web-ext/blob/master/CONTRIBUTING.md#creating-a-release).

**Comment by nmartinez23** [comment]
Hi Kumar, nice to meet you earlier on IRC. Can I start working on this issue?  If so, please let me know if there is any additional information to start working on this. I'm new to open-source contributions but I will definitely give it my best shot, thanks!

**Comment by kumar303** [comment]
Hi. Definitely feel free to work on this. The info is in the description but let me know if you get stuck or have any questions?

**Comment by nmartinez23** [comment]
Great, I'll start working on it when I get home later today.

**Comment by nmartinez23** [comment]
Hi Kumar, it took me awhile to figure out how to set up the dev environment but I think I have it now. On the YAML file, do I use the same api_key for the new section that's in the existing section? 

Also the new deploy section has a "file:" key but the existing section does not. Should I include the "file:" and if so what would go there? Thanks

**Comment by kumar303** [comment]
This is great news that your dev environment is set up! I took a closer look at this and I realized it requires setting up an [oauth account on GitHub](https://developer.github.com/v3/oauth/) which is only something an owner of the repo can do (a Mozilla admin). Sorry, I didn't notice this detail before. I'm removing the 'good first bug' label but since your dev environment is set up, it has not been time wasted! Here are some [others](https://github.com/mozilla/web-ext/labels/good%20first%20bug) you could look at.

**Comment by nmartinez23** [comment]
No problem, sounds good. I will start looking at the other issues now.
