### ISSUE TITLE
web-ext build with a non-existent path to artifacts directory results in an error

### ISSUE THREAD

**Issue by shubheksha** [mozilla/web-ext#510]
When running the following command:

```
web-ext build -a "/non-existant-directory"
```

You get this error:

```
build: Error code: EACCES
```

Instead, you should get this error:

```
build: --artifacts-dir /non-existant-directory is not a directory
```

**Comment by kumar303** [comment]
Thanks for filing! I updated the description so that it clearly states 1) the command to reproduce the bug, 2) what happens, and 3) what we expect to happen.

**Comment by pdehaan** [comment]
Should it throw an error, or just automatically create the specified artifact directory for you?

**Comment by kumar303** [comment]
Let's start by throwing an error. We can file a bug later to automatically create it (which might fail if the user doesn't have permission to create directories).
