### ISSUE TITLE
Run the node security platform tool in continuous integration

### ISSUE THREAD

**Issue by kumar303** [mozilla/web-ext#513]
It would be helpful to run the [nsp](https://github.com/nodesecurity/nsp) command as part of our [continuous integration check](https://github.com/mozilla/web-ext/blob/master/.travis.yml) so that we can be sure we're never shipping any known vulnerabilities in `web-ext`.

This should be as simple as adding `npm check` to our `.travis.yml`.

So far so good:
````
$ nsp check
(+) No known vulnerabilities found
````

**Comment by pdehaan** [comment]
nsp is awesome!

**PROTIP:** Remember that nsp also supports a config file, .nsprc, where you can specify exceptions or advisories that you want to ignore. You can see an example over in **fxa-content-server** at https://github.com/mozilla/fxa-content-server/blob/master/.nsprc. It's super useful when a vulnerable module is very deeply nested.

You can find more info on exceptions in the docs at https://github.com/nodesecurity/nsp#exceptions

**Comment by Standard8** [comment]
You could also use [greenkeeper.io](https://greenkeeper.io/) to automatically create PRs when your dependencies are updated.

**Comment by kumar303** [comment]
We do use greenkeeper. It's fantastic.
