### ISSUE TITLE
A jpm watchpost equivalent is needed

### ISSUE THREAD

**Issue by the8472** [mozilla/web-ext#518]
The advantage of using watchpost + the extension autoinstaller addon is that it works remotely and does not require a new firefox session. It would be great if web-ext could support that too.

**Comment by kumar303** [comment]
We implemented watchpost in web-ext a little differently: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Getting_started_with_web-ext#Automatic_extension_reloading

If you run into any bugs with it, please open issues!

**Comment by the8472** [comment]
watchpost is able to push to a remote firefox instance. how do i get `web-ext run` to do that for me?

**Comment by kumar303** [comment]
That's exactly what it does. It reloads your add-on inside the browser any time you make a change to the code (no need to restart the browser). Were you looking for a different feature?

**Comment by the8472** [comment]
*Remote* meaning on a different host. something like `jpm watchpost --post-url http://192.168.0.17:18888/`

And as I also mentioned 

> and does not require a new firefox session

I don't see a way of pointing web-ext run to an already running session either.

**Comment by kumar303** [comment]
Hmm. What is the use case for this? Can't you just do [run --firefox-binary](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/web-ext_command_reference#web-ext_run) to start it in whatever version of Firefox you want?

Under the hood web-ext connects to the remote debugger so we could expose an option to set the IP and port but I'd like to see a use case for it first.

**Comment by the8472** [comment]
> but I'd like to see a use case for it first.

firefox runs in a different VM than the development environment

> Can't you just do run --firefox-binary to start it in whatever version of Firefox you want?

That would mean I can't use the already-open session.

**Comment by andymckay** [comment]
Would this allow web-ext to be run against Android as well?

**Comment by kumar303** [comment]
> @the8472 firefox runs in a different VM than the development environment

Aha, that makes sense! Can you file a new issue requesting an option like `web-ext run --remote-firefox=X.X.X.X:YYYY` ? I think that will solve it for you.

> @andymckay Would this allow web-ext to be run against Android as well?

Not immediately because I don't think Android supports the remote debugger commands we use yet (`installTemporaryAddon` and `addon.reload()`). It would be a stepping stone for sure though. We should probably start on Android support for those commands so that it makes it into a train soon.

**Comment by andymckay** [comment]
Fair enough, yeah lets file bugs to get that started for Android.

**Comment by kumar303** [comment]
> yeah lets file bugs to get that started for Android.

Done. https://bugzilla.mozilla.org/show_bug.cgi?id=1305143
