### ISSUE TITLE
Format the output properly for a failing functional test

### ISSUE THREAD

**Issue by shubheksha** [mozilla/web-ext#522]
### Is this a bug or feature request?
It can be considered as an enhancement.

### What is the current behavior?
Currently, when a functional test fails the output printed to the console is:
![image](https://cloud.githubusercontent.com/assets/7693422/18811122/aa0b6bb4-82c4-11e6-9c31-6e21aae0040c.png)

(If this is a bug, please include the exact steps to reproduce the problem, including the
`web-ext` commands you ran. Do not include sensitive information like API secrets.
Upload a text log created with the `--verbose` flag if possible.
Upload a .zip file of your web extension source if necessary.)

### What is the expected or desired behavior?
Even though the output contains all the info required to debug, it can be formatted in a better way to make it more readable.

### Version information

(Please fill this in for bug reports.)

* Output of `web-ext --version`:
* Output of `node --version`:
* Output of `npm --version`:
* Firefox version:
* Your OS and version:

**Comment by kumar303** [comment]
Good idea! As a first step, we could convert the new line character to actual new lines.
