### ISSUE TITLE
Clean up the changelog if statements in the continuous integration script

### ISSUE THREAD

**Issue by kumar303** [mozilla/web-ext#526]
### Is this a bug or feature request?

just some code cleanup

### What is the current behavior?

Every time we run tests in continuous integration, the [.travis.yml](https://github.com/mozilla/web-ext/blob/master/.travis.yml) script commands will be executed in all specified NodeJS versions. We recently removed NodeJS versions less than 4 so we can now clean up any if statements that checked for versions less than 4.

Example:

    if [[ ${TRAVIS_NODE_VERSION:0:1} -ge "4" ]]; then
      ...
    fi

### What is the expected or desired behavior?

The behavior should remain the same. When making the change in a pull request, the test run will tell us if any behavior has been broken by the change.

**Comment by rackstar17** [comment]
Hi @kumar303 , can you review the PR for this .
Thanks.

**Comment by kumar303** [comment]
fixed in https://github.com/mozilla/web-ext/pull/529
