### ISSUE TITLE
Support local commit verification for Windows users

### ISSUE THREAD

**Issue by kumar303** [mozilla/web-ext#551]
After https://github.com/mozilla/web-ext/issues/515, Windows users will have to commit like `git commit --no-verify` since the pre-commit hook we added does not support Windows. Let's make it support Windows!

**Comment by berraknil** [comment]
I would like to work on this, especially since I'm a primarily Windows user/future contributor. I'm just a bit lost on how to test this functionality without actually trying to commit some changes to the repo. Any pointers? Thanks.

**Comment by kumar303** [comment]
Great! Thanks for your interest and welcome.

You should be able to test this easily by [creating a local work branch](https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging) and making test commits with messages that stray from the [required formatting](https://github.com/mozilla/web-ext/blob/master/CONTRIBUTING.md#writing-commit-messages).

Unfortunately, I won't be able to provide much guidance since I don't have a Windows machine set up and I don't have much knowledge of Windows. If, instead, you'd like to start with some easier issues to get familiar with the project, have a look at these [good first bugs](https://github.com/mozilla/web-ext/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+bug%22).

It would be great to make contributing easier for Windows users though. Here's what the commit message verification looks like on Mac/Linux. We'd want the same for Windows:
````
$ git commit -a
⧗   input: this message is formatted incorrectly
✖   message may not be empty [subject-empty]
✖   type may not be empty [type-empty]
✖   type must be one of ["chore", "docs", "feat", "fix", "perf", "refactor", "style", "test"] [type-enum]
⚠   body must have leading blank line [body-leading-blank]
⚠   footer must have leading blank line [footer-leading-blank]
✖   found 3 problems, 2 warnings

Your unsaved commit message:

this message is formatted incorrectly
# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
# On branch scratch
# Changes to be committed:
#	modified:   README.md
#

--------------------------------------------------------------------
Your commit was not saved because the message was formatted incorrectly.
See the error log above.
--------------------------------------------------------------------

For formatting instructions, see:
https://github.com/mozilla/web-ext/blob/master/CONTRIBUTING.md#writing-commit-messages

To bypass this check and commit anyway, use:
git commit --no-verify ...
````

**Comment by kumar303** [comment]
We accomplished this with [git-hooks](https://github.com/tarmolov/git-hooks-js) and a [commit-msg script](https://github.com/mozilla/web-ext/blob/master/.githooks/commit-msg/check-for-changelog-lint). If you hunt around, maybe you can find a Windows compatible replacement to `git-hooks`?

**Comment by berraknil** [comment]
Thanks for all the great info, I'm looking into all of it now. Also checked the good first bugs yesterday and thinking about how to approach a few as well. I'm a Windows dev mostly so this will be handy for me to fix as well, will keep you updated after I start with the local work branch testing!

**Comment by kumar303** [comment]
Yeah, I'm not sure if this will be easy or hard to fix. A quick search landed me on [this](http://stackoverflow.com/questions/18277429/executing-git-hooks-on-windows) which claims Git for Windows has its own bash-like port so that sounds promising.

Just to be clear, you shouldn't have any trouble working on the other good first bugs on Windows. When you commit to your local branch, use `git commit --no-verify` and that will bypass the verification script.

**Comment by berraknil** [comment]
Yes there is a Git Bash and actually Ubuntu Bash on Windows now as well but it has to be installed separately I think, I'm using it but not sure if it's insider preview only or comes installed by default after the anniversary edition update. Regardless, I will look into this and try to resolve it sooner or later, also looking into the Travis CI on the good first bugs list! 👍
