### ISSUE TITLE
How to generate xpi if signing is not an option

### ISSUE THREAD

**Issue by Hypnosphi** [mozilla/web-ext#574]
My webExt is intended for corporate usage and contains confidential data, so we can't show its code to Mozilla. How do I generate a valid xpi in this case? Renaming .zip to .xpi works, but the addon doesn't seem to autoupdate (appplication.gecko.id is present in manifest.json). updates.json is served on the same intranet host as the ext itself. Is there a chance that autoupdating works only with signed extensions?

I use unbranded build 49.0.1 for testing

**Comment by Hypnosphi** [comment]
Nevermind, it's because of internal certificate. I had already set extensions.install.requireBuiltInCerts to false, but not extensions.update.requireBuiltInCerts

**Comment by kumar303** [comment]
It is possible to sign an add-on and mark it unlisted. This means that no one will manually review the code and no one will be able to download it from Mozilla's servers. However, the add-on source would still be in Mozilla's database and we currently do not offer NDA negotiations to protect who can access that source.
