### ISSUE TITLE
web-ext run - problem with winreg

### ISSUE THREAD

**Issue by onazaro** [mozilla/web-ext#576]
### Is this a bug or feature request?
Bug

### What is the current behavior?
Try to run an extension:
`web-ext run`

Get an error:

`C:\Program Files\nodejs\node_modules\web-ext\node_modules\winreg\lib\registry.js:374`
`      cb(null, result);`
`      ^`
`TypeError: Cannot read property 'value' of null`
`    at C:\Program Files\nodejs\node_modules\web-ext\node_modules\fx-runner\lib\utils.js:92:46`
`    at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\web-ext\node_modules\winreg\lib\registry.js:374:7)`
`    at emitTwo (events.js:87:13)`
`    at ChildProcess.emit (events.js:172:7)`
`    at maybeClose (internal/child_process.js:829:16)`
`    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)`

I keep doing [Getting started with web-ext](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Getting_started_with_web-ext). Cloned webextensions-examples.
When I try to run any example I get this error message.

 
### What is the expected or desired behavior?
Run an extension.

### Version information

* Output of `web-ext --version`: 1.5.0
* Output of `node --version`: v4.6.0
* Output of `npm --version`: 3.10.8
* Firefox version: 47.0.1
* Your OS and version: Windows XP SP3 32

**Comment by kumar303** [comment]
Eesh, I think Win32 is uncharted territory. Anyway, I might have a patch to fix this in https://github.com/mozilla-jetpack/node-fx-runner/pull/27

Thanks for the bug report.

**Comment by onazaro** [comment]
Thanks, now it works.

I edited lib/utils.js manually.  Not sure how to use git in this case.

Also, edited lines numbers in my local lib/utils.js are slightly different: start with 92 instead of 94.

**Comment by kumar303** [comment]
great! Thanks for testing that

**Comment by kumar303** [comment]
This should be fixed on master now. You would need to pull changes, run `npm install`, and rebuild `web-ext` to see the change.
