### ISSUE TITLE
Call stack Error when `npm uninstall --global web-ext` on Win32

### ISSUE THREAD

**Issue by onazaro** [mozilla/web-ext#581]
### Is this a bug or feature request?
Bug 

### What is the current behavior?
Try `npm uninstall --global web-ext`

Get error message "Maximum call stack size exceeded"

npm-debug.log is in attach renamed to npm-debug.txt

### What is the expected or desired behavior?

Uninstall with no errors

### Version information

(Please fill this in for bug reports.)

* Output of `web-ext --version`: 1.5.0
* Output of `node --version`: v4.6.0
* Output of `npm --version`:  3.10.8
* Firefox version: 47.0.1
* Your OS and version: Windows XP SP3 32

[npm-debug.txt](https://github.com/mozilla/web-ext/files/531834/npm-debug.txt)

[Uploading npm-debug.txt…]()

**Comment by kumar303** [comment]
This looks like an [npm](https://github.com/npm/npm/issues) bug rather than a `web-ext` bug. However, I would recommend trying to upgrade your version of `npm` since it's pretty old. Maybe it's fixed in something newer. 

Thanks for the report but I'm closing since it's not `web-ext` related.

**Comment by kumar303** [comment]
What I meant to say was try upgrading your version of NodeJS since it's pretty old.

**Comment by onazaro** [comment]
Maybe it was some NTFS bug/feature.
I've been trying to erase remaining files manually, and got an error of too long path (256 chars or something) because of very deep directory tree.

Anyway I give up on Win32 as I can't develop on it because of Flaw.
