### ISSUE TITLE
Fail `Running "flowbin:start" (flowbin) task`

### ISSUE THREAD

**Issue by onazaro** [mozilla/web-ext#583]
### Is this a bug or feature request?
Bug

### What is the current behavior?

Following #582.

Installed Node.js v6.8.1.

Try `npm start`

Stuck on `Running "flowbin:start" (flowbin) task` stage for very long time.
Swarming `node /web-ext/node_modules/grunt-flowbin/node_modules/flow-bin/vendor/flow start` processes.
Suck all available memory.

End up with
`Error: /home/pal/web-ext/node_modules/grunt-flowbin/node_modules/flow-bin/vendor/flow exited 1; result: events.js:160`
`throw er; // Unhandled 'error' event`

[npm-debug.log.zip](https://github.com/mozilla/web-ext/files/532148/npm-debug.log.zip)

### Version information

(Please fill this in for bug reports.)

* Output of `web-ext --version`: 1.5.0
* Output of `node --version`: 6.8.1
* Output of `npm --version`: 3.10.8
* Firefox version: n\a
* Your OS and version: Ubuntu 16.04 64-bit

**Comment by kumar303** [comment]
What kind of disk do you have? Is it a network mount? Or is it some kind of shared file system connected through a virtual machine?

**Comment by onazaro** [comment]
Nothing of that kind, just a simple standalone laptop with Ubuntu.
(The other is standalone desktop witn Win XP)

**Comment by onazaro** [comment]
Forgot to mention.
`npm test` gives the same issue.

**Comment by onazaro** [comment]
Sorry, this issue happens to be my mistake.
Close it.
See https://github.com/mozilla/web-ext/issues/582#issuecomment-254185330
Bad hack - bad luck.
