### ISSUE TITLE
web-ext run: only show the last reload time

### ISSUE THREAD

**Issue by kumar303** [mozilla/web-ext#617]
### Is this a bug or feature request?

feature
### What is the current behavior?

In `web-ext run`, you see a log message each time the extension is automatically reloaded.
### What is the expected or desired behavior?

You should only see the last time the extension was reloaded. It's not important to clutter the console repeatedly with each reload.

For example, this is what it currently looks like when you make a lot of changes to an extension:

```
$ web-ext run -s example-extension/
Running web extension from /Users/kumar/dev/web-ext-workshop/example-extension
Running Firefox with profile at /var/folders/h7/rttdqkks7fl_txp9_rr4j4840000gn/T/de60a72b-20aa-4218-8cc5-75981d9c677f
Use --verbose or open Tools > Web Developer > Browser Console to see logging
Installed /Users/kumar/dev/web-ext-workshop/example-extension as a temporary add-on
The extension will reload if any source file changes
14:17:21 GMT+0100 (BST): Reloaded extension: 1757806243269f9c45e4996230fed971c42e689f@temporary-addon
14:17:30 GMT+0100 (BST): Reloaded extension: 1757806243269f9c45e4996230fed971c42e689f@temporary-addon
14:19:02 GMT+0100 (BST): Reloaded extension: 1757806243269f9c45e4996230fed971c42e689f@temporary-addon
14:19:45 GMT+0100 (BST): Reloaded extension: 1757806243269f9c45e4996230fed971c42e689f@temporary-addon
14:20:37 GMT+0100 (BST): Reloaded extension: 1757806243269f9c45e4996230fed971c42e689f@temporary-addon
14:20:52 GMT+0100 (BST): Reloaded extension: 1757806243269f9c45e4996230fed971c42e689f@temporary-addon
14:24:15 GMT+0100 (BST): Reloaded extension: 1757806243269f9c45e4996230fed971c42e689f@temporary-addon
14:24:18 GMT+0100 (BST): Reloaded extension: 1757806243269f9c45e4996230fed971c42e689f@temporary-addon
14:24:26 GMT+0100 (BST): Reloaded extension: 1757806243269f9c45e4996230fed971c42e689f@temporary-addon
14:25:01 GMT+0100 (BST): Reloaded extension: 1757806243269f9c45e4996230fed971c42e689f@temporary-addon
14:25:45 GMT+0100 (BST): Reloaded extension: 1757806243269f9c45e4996230fed971c42e689f@temporary-addon
14:25:54 GMT+0100 (BST): Reloaded extension: 1757806243269f9c45e4996230fed971c42e689f@temporary-addon
```

This is what it should look like:

```
$ web-ext run -s example-extension/
Running web extension from /Users/kumar/dev/web-ext-workshop/example-extension
Running Firefox with profile at /var/folders/h7/rttdqkks7fl_txp9_rr4j4840000gn/T/de60a72b-20aa-4218-8cc5-75981d9c677f
Use --verbose or open Tools > Web Developer > Browser Console to see logging
Installed /Users/kumar/dev/web-ext-workshop/example-extension as a temporary add-on
The extension will reload if any source file changes
Last extension reload: 14:25:54 GMT+0100 (BST)
```

(This new output also removes the extension ID because that's not important.)

Some tips:
- This will need to use shell escaping to rewrite the current log line ([example](https://github.com/mozilla/sign-addon/blob/master/src/amo-client.js#L264-L265))
- If the last line does not start with 'Last extension reload' then it should not be rewritten
- In verbose mode, it should continue to just log a new line with the time and extension ID.

**Comment by jvillalobos** [comment]
Please refer to https://wiki.mozilla.org/Add-ons/Contribute/AMO/Code if this is your first contribution.

If you want to work on this issue and need more information on how or where to fix it, please comment here and we will be happy to provide more details.

Mentor: @kumar303

**Comment by 11812r** [comment]
Hi, I'd like to work on this issue. (I'm new to OSS, probably need help with git also :|)
At first glance I thought changing https://github.com/mozilla/web-ext/blob/9e5f7af49cd1c302d86079b6f3e8474050f8c827/src/firefox/remote.js#L178
```
log.info(`${(new Date()).toTimeString()}: Reloaded extension: ${addon.id}`);
```
to the new format should do it. Then I read the tips.
@kumar303 could you provide some more details.

**Comment by kumar303** [comment]
Hi Shan, welcome to open source! You are looking at the correct line indeed. You can use shell escaping to rewrite the terminal buffer in place. Take a look at the second answer to this question which shows how to do it: http://stackoverflow.com/questions/6157497/node-js-printing-to-console-without-a-trailing-newline The example is:

    process.stdout.write("Downloading " + data.length + " bytes\r");

Take note of the `\r` escape sequence. This will move the cursor to the beginning of the line.

**Comment by Shan11812** [comment]
Hey @kumar303,
Thanks for the explanations!
I tried to read the last printed line on console, but I couldn't find any way to do that! 
Replacing and writing new line is fine, but evaluating whether it starts with 'Last extension reload' is not possible.

**Comment by kumar303** [comment]
I'd love to get this feature. Do you still have time to create the new pull request from your old one?

Here's a screenshot of my current web-ext session, hah

![screenshot 2016-12-24 00 01 54](https://cloud.githubusercontent.com/assets/55398/21465521/481fb9ac-c96c-11e6-9f1c-7b6bc374d9b1.png)

**Comment by aniketkudale** [comment]
Yes, this should be quick, will do it.
