### ISSUE TITLE
Add a command to show the documentation

### ISSUE THREAD

**Issue by kumar303** [mozilla/web-ext#636]
### Is this a bug or feature request?

feature

### What is the expected or desired behavior?

Just like `jpm docs` (which is ironically undocumented) we should add a command that opens the [web-ext documentation](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Getting_started_with_web-ext).

When you execute `web-ext docs` it should open the docs [like this](https://github.com/mozilla-jetpack/jpm/blob/master/bin/jpm#L57-L63).

**Comment by eviljeff** [comment]
Please refer to https://wiki.mozilla.org/Add-ons/Contribute/AMO/Code if this is your first contribution.

If you want to work on this issue and need more information on how or where to fix it, please comment here and we will be happy to provide more details.

Mentor: @kumar303

**Comment by niharikak101** [comment]
Hi there! May I work on this issue?

**Comment by rpl** [comment]
Hi @niharikak101, that's great, thanks!

Let us know if you need any additional info or if you run into any trouble before submitting a pull request,
we are happy to help!

**Comment by niharikak101** [comment]
@rpl Thank you! I will let you know if I run into any issues. Thank you!

**Comment by kewisch** [comment]
@niharikak101 how are you making progress? If there is anything we can help with let us know!

**Comment by niharikak101** [comment]
@kewisch I have two more days of term left, and am currently in the middle of submissions and exams. Haven't got a chance to take time out and really focus on it, and I apologise for that. I'll finish my last submission on the 16th and get right to it. Extremely sorry about the delay! :)

**Comment by kewisch** [comment]
@niharikak101 no problem at all, just wanted to hear back from you to see if we could help you in any way. Looking forward to hearing from you after the 16th!

**Comment by niharikak101** [comment]
@kewisch will keep you posted! Thank you :)

**Comment by wagnerand** [comment]
@niharikak101 a friendly reminder, could you please let us know whether you are still working on this?

**Comment by niharikak101** [comment]
@wagnerand struggling a bit with the unit test, to be honest. Don't want to give up just yet, but would hate to hold you back.

**Comment by wagnerand** [comment]
No worries at all, we're here to help!

You can ask here and your mentor @kumar303 could assist you.

**Comment by Revanth47** [comment]
Can I work on this issue?

**Comment by kewisch** [comment]
Hi @Revanth47, Niharika is actually working on this issue, maybe we can interest you in another issue instead? You can find our other good first bugs at https://waffle.io/mozilla/addons?label=good%20first%20bug

@niharikak101 how are things going? Have you had a chance to work with kumar regardin the unit test? Let us know if you are stuck!

**Comment by niharikak101** [comment]
Hey @kewisch making more sense slowly. Is there somehow I can connect directly with @kumar303 without flooding the comment section?

**Comment by kumar303** [comment]
Hi @niharikak101 , thanks for keeping in touch! You can send me (username kumar) a private message on [irc.mozilla.org](https://wiki.mozilla.org/IRC) or feel free to email me as well: kumar.mcmillan@gmail.com

**Comment by erick2014** [comment]
I want to contribute to the project :) is there something with I can help u with guys?

**Comment by eviljeff** [comment]
Hi @erick2014 https://wiki.mozilla.org/Add-ons/Contribute/AMO/Code is a good place to start.

**Comment by kumar303** [comment]
@niharikak101 hi! Thanks again for your work on this. We just released it in [1.9.0](https://github.com/mozilla/web-ext/releases/tag/1.9.0) so the next step is to add documentation about this command in the [reference](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/web-ext_command_reference#Commands). Could you try adding a new section for it? You should be able to copy/paste an existing command reference and edit it.

**Comment by niharikak101** [comment]
@kumar303 of course :) should I make changes directly to the MDN reference?

**Comment by kumar303** [comment]
Yes, edit the MDN reference directly but don't worry about it being perfect. I can always help fix it up.

**Comment by niharikak101** [comment]
@kumar303 done :)
Does it look okay?

**Comment by kumar303** [comment]
@niharikak101 thanks, that looks great. I just fixed it up with a clickable link to the docs.

**Comment by niharikak101** [comment]
@kumar303 thank you :)
Happy I could help!
