### ISSUE TITLE
Add lint rule to prefer constants over variables

### ISSUE THREAD

**Issue by kumar303** [mozilla/web-ext#640]
### Is this a bug or feature request?

feature

### What is the current behavior?

When contributors submit pull requests, @kumar303 always tells them to use `const` instead of `let` when they are not modifying the variable.

### What is the expected or desired behavior?

We should let the robots tell them this instead! Let's add this rule and fix up the code:
````diff
diff --git a/.eslintrc b/.eslintrc
index 24680cd..66c4e3c 100644
--- a/.eslintrc
+++ b/.eslintrc
@@ -100,6 +100,7 @@
       "allowMultiplePropertiesPerLine": true
     }],
     "one-var": [2, "never"],
+    "prefer-const": 2,
     "prefer-template": 2,
     "quote-props": [1, "consistent-as-needed"],
     "quotes": [2, "single", "avoid-escape"],````

**Comment by pragyes31** [comment]
Hi,

I will work on this issue.

Thanks,
Rahul

**Comment by kumar303** [comment]
great, thanks! Let me know if you run into any trouble before submitting a pull request.

**Comment by shubheksha** [comment]
@kumar303, wouldn't this require changing the variables which aren't being reassigned anywhere to const? Eslint will keep complaining otherwise as is evident in #661

**Comment by kumar303** [comment]
@shubheksha yes, exactly. @aniketkudale, sorry for the late reply. I just now had a chance to look at your patch and I pointed out some additional changes needed.

**Comment by kewisch** [comment]
@pragyes31 are you still working on this bug? I'd love to hear back from you!

**Comment by pragyes31** [comment]
@kewisch I am. Will submit the PR probably by this weekend.
