### ISSUE TITLE
Build command should not overwrite existing extension

### ISSUE THREAD

**Issue by kumar303** [mozilla/web-ext#68]
The build command currently clobbers an existing extension at the destination path. We should probably not do that and maybe provide an option to allow it.

**Comment by eviljeff** [comment]
Requirements: You should know javascript.

**Comment by atsay** [comment]
@kumar303 Will you add a few basic steps to get started?

**Comment by eviljeff** [comment]
@kumar303 can you expand on where a contributor would need to start to fix this issue.

**Comment by kumar303** [comment]
The build command starts writing the destination file in [createWriteStream](https://github.com/mozilla/web-ext/blob/master/src/cmd/build.js#L37). If `extensionPath` exists, you could throw an error (to reject the promise) but only log the error and continue if run like `build --overwrite-dest` (or something).

**Comment by onazaro** [comment]
Can I work on this as my first patch?

**Comment by kumar303** [comment]
@onazaro yes for sure! Glad to hear that your environment is set up now, sorry for all the hassle.

**Comment by onazaro** [comment]
In fact, the environment is not set up yet.
Experiments with it take a lot of time waiting, so I'm trying to get familiar with the code in the meantime.

Should I use `fs.access()` to test if extensionPath exists, or is there more clever way?

As to setup, I now stuck  with "flowbin:start" sucking all my memory + 9 Gb of swap, and ending up with Unhandled error.
I will now try latest Node.js istead of stable one, as you propose.

**Comment by kumar303** [comment]
> Should I use fs.access() to test if extensionPath exists, or is there more clever way?

You will need to use `fs.stat()` but there are a few annoying error cases you'll need to handle. Here is an example: https://github.com/mozilla/web-ext/blob/master/src/util/is-directory.js#L17-L23

**Comment by onazaro** [comment]
@kumar303, where is the right plase to consult with you about setting up development environment?
I badly need your advice concerning #583.
Maybe, comment out  the "flowbin:check" part temporarily in some way?
Just to make `npm start` and `npm-test` work at least partially, as I need it to build and test the code I change (if I understand it right).

**Comment by onazaro** [comment]
@kumar303 How do I submit the changes I make?

**Comment by kumar303** [comment]
Yep, you're heading in the right direction. Next, you need to create a pull request: https://help.github.com/articles/creating-a-pull-request/

Let me know if you get stuck but the help on the github site (and elsewhere on the web) is really good. It should provide all the information you need.

**Comment by kumar303** [comment]
Thanks again for your time on this @onazaro but I closed the open pull request due to inactivity. I'd like to make this patch available for any new contributor to work on so that we can get it landed.

**Comment by subhdeep** [comment]
Can i work on this?

**Comment by wagnerand** [comment]
@subhdeep Yes, absolutely. Please submit a pull request.

**Comment by wagnerand** [comment]
@kumar303 You get another mentor badge for this one :)

**Comment by subhdeep** [comment]
It will be helpful If you help me on how should I proceed with the problem.

On Wed, Feb 22, 2017, 12:04 AM Andreas Wagner <notifications@github.com>
wrote:

@subhdeep <https://github.com/subhdeep> Yes, absolutely. Please submit a
pull request.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/mozilla/web-ext/issues/68#issuecomment-281434968>, or mute
the thread

**Comment by onazaro** [comment]
@subhdeep You can use my code if you like.
@kumar303 So sorry I had no time to complete this.

**Comment by rpl** [comment]
Hi @subhdeep,
Welcome on web-ext!

For the change that will fix this issue we need two things:
- we need to test if the output file already existst and fail if it does, this is going to
  require changes to the sources that define the command 'web-ext build' 
  (src/cmd/build.js), in particular to the `defaultPackageCreator` async function.
- we need to define a new '--overwrite-dest' option for the 'web-ext build'
  command, which have to be used in the build command implementation to
  explicitly allow to overwrite the file (the options are defined in 'src/program.js')
  
Some times ago @onazaro has created a prototype of the above changes which doesn't seem to be too far from the goal here: https://github.com/mozilla/web-ext/issues/587, the change was not ready to land yet, but 
you can definitely use that PR to get a better picture of the changes that you need to plan and the review comments that this kind of change already received before
(which can provide other useful insights)
  
Here are some of the things that you will need (e.g. to setup, to know or learn) to complete this change:
- setup a nodejs development environment (web-ext currently officially support any nodejs version >= 4)
- clone the project sources and test that your nodejs environment is able to completely run the tests without any failures (which basically means all the following steps complete without unexpected errors: "git clone YOUR_WEB_EXT_CLOSED_REPO_URL; cd web-ext; npm install; npm run test")
- use of JavaScript ES6/ES7 syntaxes and features (you will notice that this project is written is ES6 JavaScript code, that is converted into ES5 code using babel, to be able to run the latest JavaScript language features on all the past JavaScript VMs versions that do not support that features yet, e.g. we use Promise and async functions to make the asynchronous code to looks like synchronous code, on this article https://ponyfoo.com/articles/understanding-javascript-async-await you can learn more about this two features)
- writing JavaScript code which is "type annotated" using flow (https://flowtype.org, which helps to spot some classes of mistakes using a statical analysis of the "flow annotated" sources).
- writing JavaScript tests based on mocha (the test framework/runner), chai (a test assertions library) and sinon (a library used to create test mocks/stubs/spies)

You can find more informations related to how to contribute code to web-ext in our CONTRIBUTING.md file: https://github.com/mozilla/web-ext/blob/master/CONTRIBUTING.md

Once you are sure that your nodejs environment is working correctly, you can proceed to create your new development branch and start to work on your changes (e.g. based on the above description of the goals and the @onazaro's PR #587), and to create the pull request (more info on the github PRs creation on https://help.github.com/articles/creating-a-pull-request/) when you feel that the change is ready for a review (or if you need help on specific issues with your changes, e.g. flow errors and failures running the tests).

Hope that the above informations are helpful to get you started, but feel free to ping us if you get stuck or if something is not working correctly or it is not completely clear and you need help to figure it out.

In the meantime: Happy web-ext Hacking!

**Comment by wagnerand** [comment]
@subhdeep are you still working on this?

**Comment by harikishen** [comment]
@wagnerand I would like to work on this.

**Comment by kumar303** [comment]
@harikishen that's great! Let me know if you have any questions.

**Comment by harikishen** [comment]
I've followed the steps and done some work on this issue but get these errors https://pastebin.mozilla.org/9022473 @kumar303

**Comment by rpl** [comment]
@kumar303 I looked at the errors in the above pastebin link, we (@harikishen and I) chatted a bit about it over IRC and @harikishen is now working on it in #954.

**Comment by kumar303** [comment]
@harikishen thanks again for adding this feature! It has been released in [1.10.0](https://github.com/mozilla/web-ext/releases/tag/1.10.0). Are you able to finalize this issue by documenting the new option on the [build command reference page](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/web-ext_command_reference#web-ext_build)? Let me know if you have questions about how to do so.

**Comment by kumar303** [comment]
This is now documented: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/web-ext_command_reference#Commands
