### ISSUE TITLE
web-ext run: open the Browser Console

### ISSUE THREAD

**Issue by kumar303** [mozilla/web-ext#686]
### Is this a bug or feature request?

feature

### What is the current behavior?

If you want to develop your extension with the Browser Console open, you have to do this:

- Type: `web-ext run --firefox=nightly`
- Remember that you wanted the Browser Console open
- Manually type ctrl-shift-J when Firefox starts up to open the Browser Console

### What is the expected or desired behavior?

It would be nice to just do `web-ext run --firefox=nightly --jsconsole`

This should be pretty simple because Firefox already has ` --jsconsole` option we can pass to it.

There are actually a bunch of other options like this that we should expose but that could be done in a separate bug.

**Comment by aniketkudale** [comment]
@kumar303  Can I take this?

**Comment by kumar303** [comment]
@aniketkudale yes, for sure! Thank you.

**Comment by aniketkudale** [comment]
Hi @kumar303, thanks. I've already started working on it, added `jsconsole` description/definition in `program.command('run', { })` in `src/program.js`. I hope I am right? Now how can I pass jsconsole parameter to firexfox?

**Comment by kumar303** [comment]
Sounds like you're on the right path. You can configure the Firefox arguments with the [binaryArgs parameter](https://github.com/mozilla/web-ext/blob/master/src/firefox/index.js#L139). You'd need to change [this line](https://github.com/mozilla/web-ext/blob/master/src/cmd/run.js#L327) to :

    firefoxApp.run(profile, {firefoxBinary: firefox, binaryArgs: ['-jsconsole']})

**Comment by aniketkudale** [comment]
@kumar303 Is description ok?

```
'jsconsole': {
    describe: 'Open web browser console',
    demand: false,
    type: 'string',
}
```
Also for test, do I just need to add `--jsconsole` in `const argv` array?
```
const argv = [
  'run', '--verbose', '--no-reload',
  '--source-dir', srcDir,
  '--firefox', fakeFirefoxPath,
  '--jsconsole'
];
```

**Comment by kumar303** [comment]
Seems fine. It will be easier to review once you post a pull request. As for the test, check out how the `run` command is [already tested](https://github.com/mozilla/web-ext/blob/master/tests/unit/test-cmd/test.run.js). You will see that `argv` is actually an object (not an array) so you would pass options like `{jsconsole: true}`

**Comment by kumar303** [comment]
For example, [noReload: true](https://github.com/mozilla/web-ext/blob/master/tests/unit/test-cmd/test.run.js#L38) in the test is the equivalent of `web-ext run --no-reload`.

**Comment by aniketkudale** [comment]
Thanks @kumar303 for the reply, I'll update the test case and will post a PR.

**Comment by kumar303** [comment]
Hi @aniketkudale , we just released the `--browser-console` option! Thanks again. If you have some time, could you edit the [run command reference page](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/web-ext_command_reference#web-ext_run) to document this new option?

**Comment by aniketkudale** [comment]
Yes, Sure! Thanks @kumar303, This needs to be added under '`webext run` section, right'?

**Comment by kumar303** [comment]
Yes, you can edit this section and copy the format for other options: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/web-ext_command_reference#web-ext_run Be sure to also include documentation for the environment variable.

**Comment by kumar303** [comment]
Thanks @aniketkudale ! I made some minor tweaks but the docs look great.

**Comment by aniketkudale** [comment]
No worries @kumar303 thanks.
