### ISSUE TITLE
Make sure all named function parameters have Flow types

### ISSUE THREAD

**Issue by kumar303** [mozilla/web-ext#696]
### Is this a bug or feature request?

code quality enhancement

### What is the current behavior?

The code base still has a lot of untyped object parameters. They look something like this:
````javascript
function doTheThing({
  paramOne,
  paramTwo,
}: Object = {}) {
  ...
}
````

### What is the expected or desired behavior?

If you use a wrong parameter value when calling a function like this, Flow should tell you but it won't because `Object` is a loose type that allows any value.

We should change all instances of this to use typed objects like:

````javascript
type doTheThingParams = {
  paramOne: string,
  paramTwo: number,
}

function doTheThing({
  paramOne,
  paramTwo,
}: doTheThingParams = {}) {
  ...
}
````

**Comment by shubheksha** [comment]
Isn't there an ESLint rule for checking this?

**Comment by kumar303** [comment]
I don't know of one, maybe! We could incorporate @rpl's https://github.com/rpl/flow-coverage-report/ to find out about problems like this too.

**Comment by kumar303** [comment]
For turning on Flow coverage: https://github.com/mozilla/web-ext/issues/697
