### ISSUE TITLE
Make changelog linting more effective

### ISSUE THREAD

**Issue by kumar303** [mozilla/web-ext#701]
### Is this a bug or feature request?

code quality enhancement

### What is the current behavior?

When you develop locally or create a PR, you have to follow the [commit message format](https://github.com/mozilla/web-ext/blob/master/CONTRIBUTING.md#writing-commit-messages). If you make a mistake, you'll get a failure locally. If you push a bad commit to your branch, you'll see failures forever unless you rewrite the commit history.

### What is the expected or desired behavior?

This isn't very effective because ultimately a maintainer will squash and merge the PR to master, choosing a new commit message anyway. There is no linting for this message! As a maintainer myself, I also like to spend time on this final squashed message since it will go into the auto-generated changelog.

We should come up with a more effective linting strategy.

The first action items: 
* remove the local pre-commit hooks
* remove the TravisCI test for changelog linting

Next, we need a new linting approach. Ideas:
* create a bot that watches for new PRs and pings @kumar303 or @rpl in IRC if a title needs fixing. PR titles are used by git to create the squashed commit message.
* create a webextension for maintainers that warns if the text box has an improperly formmated message when doing a squash-on-merge.

**Comment by kumar303** [comment]
@rpl maybe we don't need a bot at all. Another idea: make the CI test look for [TRAVIS_PULL_REQUEST](https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables), check its title (using the github api?), and run it through the changelog linter.

**Comment by rpl** [comment]
@kumar303 :+1: yeah, even better, I like it! 

we can use the above environment var and request the JSON description of the pull request, e.g. for #677 from the API URL https://api.github.com/repos/mozilla/web-ext/pulls/677 we get:

```
{
  ...
  "title": "Update grunt-webpack to the latest version 🚀",
  ...
}

**Comment by kumar303** [comment]
One thing to keep in mind about pull requests like the Greenkeeper ones is that if there is *only one commit* in the pull request, GitHub will use the lone commit message as the title for the merge commit. In other words, the title for the `grunt-webpack` upgrade is technically not formatted right but GitHub sets the merge commit to this which is formatted correctly:

    chore(package): update grunt-webpack to version 2.0.0-beta.4 (#677)

**Comment by kumar303** [comment]
I actually requested to bring the title in line with the format (https://github.com/greenkeeperio/greenkeeper/issues/343) because it's not uncommon to pile on multiple commits to fix breakage from an upgrade.
