### ISSUE TITLE
Trigger an extension reload from the CLI with keyboard input

### ISSUE THREAD

**Issue by kumar303** [mozilla/web-ext#705]
### Is this a bug or feature request?

feature request

### What is the current behavior?

When using `web-ext run`, the extension will be automatically reloaded when you edit the source. 

### What is the expected or desired behavior?

It would be nice to trigger a reload manually from the CLI. You can make a new blank line in one of your files and save it but that's a hacky workaround. 

I found myself needing such a feature because I had erased some logs and I wanted to reload my background script to see the startup logging again. I don't know if people would need it much but it should be easy to implement. We could just listen for `Enter` or `R` or whatever key and do the reload.

**Comment by saintsebastian** [comment]
I would like to work on this, seems very useful

**Comment by kumar303** [comment]
Hi @saintsebastian , that's great. I was working on an extension today that could have benefited from this feature. 

I think we could simply intercept the letter 'R' to trigger a reload. It could show a prompt like 'Press R to reload the extension' and it could maybe use [this technique](http://stackoverflow.com/questions/5006821/nodejs-how-to-read-keystrokes-from-stdin) for reading the 'R' character (I haven't tried this though, maybe there is a library for it?).

**Comment by kumar303** [comment]
@saintsebastian hey! I just pushed this out in 1.9.0 https://github.com/mozilla/web-ext/releases/tag/1.9.0 Thanks again. Could you add a new section in the docs about it right under the [Automatic extension reloading](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Getting_started_with_web-ext#Automatic_extension_reloading) section?

**Comment by saintsebastian** [comment]
@kumar303 It is surprisingly hard to phrase for such a small function :) Feel free to fix my version.

**Comment by kumar303** [comment]
ah, yeah, that's a tough one. I made a minor edit to make it a bit more clear. Thanks.
