### ISSUE TITLE
web-ext lint logs error if async/await is used

### ISSUE THREAD

**Issue by asamuzaK** [mozilla/web-ext#740]
### Is this a bug or feature request?
bug

### What is the current behavior?
1. save attached file
2. run `web-ext lint`
3. in Validation Summary, JS SYNTAX ERROR is logged.

(If this is a bug, please include the exact steps to reproduce the problem, including the
`web-ext` commands you ran. Do not include sensitive information like API secrets.
Upload a text log created with the `--verbose` flag if possible.
Upload a .zip file of your web extension source if necessary.)

### What is the expected or desired behavior?
No validation error.

### Version information (for bug reports)

* **Firefox version**:
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:52.0) Gecko/20100101 Firefox/52.0

* **Your OS and version**:
Windows_NT 10.0

* Paste the output of these commands:
````
web-ext --version
1.6.0

node --version
v7.3.0

npm --version
3.10.5
````
[webExtTest.zip](https://github.com/mozilla/web-ext/files/688981/webExtTest.zip)

**Comment by kumar303** [comment]
Hi @asamuzaK , thanks for the bug report and the reproducible code. However, this is a bug in [addons-linter](https://github.com/mozilla/addons-linter). Can you file it there instead?

**Comment by asamuzaK** [comment]
Filed [Logs error if async/await is used in JavaScript · Issue #1091 · mozilla/addons-linter](https://github.com/mozilla/addons-linter/issues/1091)

**Comment by tofumatt** [comment]
FYI This has been fixed in the linter and version `[0.15.15](https://github.com/mozilla/addons-linter/releases/tag/0.15.15)` is being published to npm, so once it appears in the greenkeeper queue merging will fix this issue in `web-ext` as well.

**Comment by asamuzaK** [comment]
Thanks!

**Comment by kumar303** [comment]
@asamuzaK I pulled in the new linter via https://github.com/mozilla/web-ext/commit/3a15819374ec49b653b8fcde863f7964118dde67 Can you update your master of `web-ext`, rebuild, and make sure it's fixed? I'm going to leave this bug open until we confirm it.

**Comment by asamuzaK** [comment]
Unfortunately, when I build from the source and ran `web-ext lint`, module error occurred on my local PC (Win10).

```
>web-ext lint
module.js:472
    throw err;
    ^


Error: Cannot find module '../dist/web-ext'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Kazz\Documents\GitHub\web-ext\bin\web-ext:5:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

There was no error if I test on addons-linter.
```
>addons-linter .
Validation Summary:

errors          0
notices         0
warnings        0
```

**Comment by kumar303** [comment]
Hmm, weird. There is some Windows bustage that is getting fixed right now: https://github.com/mozilla/web-ext/pull/751

I tried it out and I can confirm that it's working:

````
$ web-ext --version
Detatched: 7d20a3c862105fa45363e79323b99b0ba1b0ceff-7d20a3c862105fa45363e79323b99b0ba1b0ceff
zenith:webExtTest kumar$ web-ext lint
Validation Summary:

errors          1
notices         0
warnings        0

ERRORS:

Code              Message                   Description                                                                                 File            Line   Column
JS_SYNTAX_ERROR   JavaScript syntax error   There is a JavaScript syntax error in your code; validation cannot continue on this file.   background.js   2      35
zenith:webExtTest kumar$ web-ext --version
master-3a15819374ec49b653b8fcde863f7964118dde67
zenith:webExtTest kumar$ web-ext lint
Validation Summary:

errors          0
notices         0
warnings        0
````
