### ISSUE TITLE
Make working with experiments easier

### ISSUE THREAD

**Issue by andymckay** [mozilla/web-ext#741]
### Is this a bug or feature request?

Feature

### What is the current behavior?

So you want to write an experiment. That's an old style legacy add-on:

https://webextensions-experiments.readthedocs.io/en/latest/

You then write an WebExtension that uses the experiment. But web-ext run won't work out of the box, you need to make a custom profile that has the legacy add-on installed. Then use that with --profile with your web-ext run.

Then you go back and fiddle with the legacy add-on now you have to reinstall the legacy add-on in the profile and start again.

### What is the expected or desired behavior?

Is there a way we can make this a little easier?

**Comment by kumar303** [comment]
Would https://github.com/mozilla/web-ext/issues/123 solve this?

**Comment by kumar303** [comment]
That issue number is not fake, I promise

**Comment by andymckay** [comment]
It would make it easier. The two things I think we might need to solve are: getting the experiment into the profile before we load the extension being developed and dealing with updates on the experiment.

**Comment by kumar303** [comment]
Oh, right, I see. We could maybe re-use some of the [--pre-install logic](https://github.com/mozilla/web-ext/blob/master/src/cmd/run.js#L221) to install a proxy file for the experiment (maybe). I don't think we can use the actor/reload approach though since experiements are legacy add-ons.

I guess ideally it would look like ... ?
````
web-ext run --source-dir=./my-webextension --with-experiment=./my-experiment
````

**Comment by andymckay** [comment]
That would be good. Losing auto-reload on the experiment is perfectly understandable.

@kmaglione has an idea about including the experiment and extension in the same package, so this point might be moot. Before we go further on this, we should see if thats going to happen and the impact.

**Comment by kumar303** [comment]
> Losing auto-reload on the experiment is perfectly understandable.

Since the proxy file is a symlink, most changes would be automatically recognized. However, there could be startup-y things that won't happen.

**Comment by andymckay** [comment]
With experiments now being bundled with the extension and not seperate, is this still relevant?

**Comment by kumar303** [comment]
Well, hmm. Will experiments as separate extensions be going away? @rpl had started a patch to solve this a while back but it was waiting on the Android features. If it's not worth pursuing then I'm sure he'd be happy about not having to un-rot the bitrot 🌵 https://github.com/mozilla/web-ext/pull/830

**Comment by kumar303** [comment]
It looks like there are some stability issues with bundled experiments: https://bugzilla.mozilla.org/show_bug.cgi?id=1434076

**Comment by ianb** [comment]
I believe this is working now, I'm able to use web-ext with embedded WebExperiments.

**Comment by Rob--W** [comment]
Support for embedded WebExtensions are going to be removed in Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1500265

So there is no need to keep this issue open any more.
