### ISSUE TITLE
`web-ext run` should allow for starting with debugger enabled.

### ISSUE THREAD

**Issue by sblask** [mozilla/web-ext#759]
Feature request: it would be great if `web-ext run` would have a `--debugging-enabled` flag so I don't have to go to about:debugging and click on `debug` for my add-on on every start.

**Comment by kumar303** [comment]
Yes, this would be nice, especially since auto-reloading exits the debugger (at least it used to but I can no longer find the bug).

@rpl would we need a Firefox patch for this? Maybe to use a remote actor to turn this on? If so, perhaps we should file the bugs ASAP.

**Comment by rpl** [comment]
@sblask :+1:

@kumar303 the WebExtensions Addon Debugger should survive auto-reloading (the old one didn't, but when I worked on the new one I took care of this scenario)

Nevertheless I totally agree that it would be helpful if we could "auto-open" the tool on the installed addon without the need to start it manually, I'm pretty sure that we need a patch for it, as an example we could define an additional `{openAddonDebugger: true}` parameter on the [addons RDP actor `installTemporaryAddon` method](https://dxr.mozilla.org/mozilla-central/source/devtools/server/actors/addons.js#19), which will open the addon debugger as soon as the addon has been installed.

**Comment by kumar303** [comment]
@rpl yeah, I like `installTemporaryAddon(path, {openAddonDebugger: true})` -- can you file a bug so it can get into triage?

**Comment by rpl** [comment]
@kumar303 sure thing :+1:

**Comment by rpl** [comment]
@kumar303 Filed on bugzilla as [Bug 1332299 - Optionally open the Addon Debugger automatically after an addon is installed using the RDP method addonsActor.installTemporaryAddons](https://bugzilla.mozilla.org/1332299).

**Comment by yangwen2** [comment]
bump on this. Is web-ext still a focus given Mozilla's recent strategy pivot?

**Comment by rpl** [comment]
> bump on this. Is web-ext still a focus given Mozilla's recent strategy pivot?

This tool is actively maintained :slightly_smiling_face: 
The priority of this particular issue is still ‘enhancement’ and not currently being worked on.

A reasonable path forward for this issue would be interest from a contributor to work on it
(we didn't mark it as a good first bug because implementing it will likely require a more experienced contributor).

**Comment by curtisbelt** [comment]
> Feature request: it would be great if web-ext run would have a --debugging-enabled flag so I don't have to go to about:debugging and click on debug for my add-on on every start.

Here's a solution that is working very well for me.

I take the URL found when opening via `about:debugging -> click on inspect` and make this the starting page for web-ext via `--start-url`. This page should have developer tools open automatically. While I'm at it, I also use `--pref` to make sure that the **Console** tab is selected by default (the default tab is **Inspector**.

```sh
web-ext run \
  --target=firefox-desktop \
  --pref=devtools.toolbox.selectedTool=webconsole \
  --start-url "about:devtools-toolbox?id=EXTENSION_ID_HERE&type=extension"
```

Flags found here:
https://github.com/mozilla/web-ext/blob/19fdd3a57638b178cc8e9555e4d891107e7c416d/src/program.js#L643-L658

**Comment by willdurand** [comment]
Looks like this issue has been fixed by https://github.com/mozilla/web-ext/pull/2488
