### ISSUE TITLE
Protect config files from declaring invalid keys

### ISSUE THREAD

**Issue by kumar303** [mozilla/web-ext#772]
This is part of implementing https://github.com/mozilla/web-ext/issues/176

Let's say you have a config with a typo in it:
````js
module.exports = {
  sourceDirectory: './src',
};
````
This should raise an error like "sourceDirectory is not a valid config key."

This would also naturally raise an error for non-camel cased options, like:
````js
module.exports = {
  'source-dir': './src',
};
````
-> "source-dir is not a valid config key."

**Comment by shubheksha** [comment]
@kumar303, for this patch, I think we discussed the approach a little while back. We'll have to keep track of all the options and see if we can find the key in the config in, say, an array. Does that sound right? I think I suggested hard coding the options into the array but that'll become chaotic quickly as and when we add new options.
