### ISSUE TITLE
Environment variables get applied as options to any command

### ISSUE THREAD

**Issue by wagnerand** [mozilla/web-ext#793]
### Is this a bug or feature request?

This is a bug.

### What is the current behavior?

I have set `WEB_EXT_API_KEY` and `WEB_EXT_API_SECRET` in my `~/.bash_profile`.
Running `web-ext build` for any webextension project fails with the following error:
`Unknown arguments: apiSecret, apiKey`
When I remove the two environment variables, `web-ext` works fine.

### What is the expected or desired behavior?

`web-ext build` (and other commands) should ignore environment variables they don't need.

### Version information (for bug reports)

* **Firefox version**: irrelevant
* **Your OS and version**: MacOS 1.12.3
* Paste the output of these commands:

````
node --version && npm --version && web-ext --version
````

v7.5.0
4.1.2
1.6.0

**Comment by kumar303** [comment]
oof, good catch. I'm pretty sure this has existed ever since https://github.com/mozilla/web-ext/pull/226 but no one else noticed. It's because those env variables are only recognized by the `sign` command. For other commands, our parser thinks they are env vars for unknown options.

**Comment by eight04** [comment]
This make environment variable totally unusable... and it seems that web-ext use yargs to parse env variable (https://github.com/mozilla/web-ext/blob/master/src/program.js#L88). Should we move this to yargs or any other ideas to fix this?

**Comment by kumar303** [comment]
Oops, I should have filed an upstream bug originally. Here it is: https://github.com/yargs/yargs/issues/873

**Comment by stephenmathieson** [comment]
Any updates here? I just killed over an hour trying to figure this out.

----

Hack I'm using to work-around this for now:

```bash
APIKEY="$WEB_EXT_API_KEY"
APISECRET="$WEB_EXT_API_SECRET"
unset WEB_EXT_API_KEY
unset WEB_EXT_API_SECRET

# Zip the Firefox extension.
npx web-ext build --config-discovery=false

# Zip+sign (XPI) the Firefox extension.
npx web-ext sign \
  --api-key=$APIKEY \
  --api-secret=$APISECRET \
  --config-discovery=false
```

**Comment by Rob--W** [comment]
No updates yet. I have planned a patch to upgrade our yargs dependency to resolve some issues ( #1307 and #1327 in particular). That might or might not fix this issue.
Regardless, you should be able to set the key and secret in the config file once #1327 is resolved.

**Comment by stephenmathieson** [comment]
I'm creating these archives on CI and _want_ to use environment variables rather than having to worry about creating a config file.

Do you have an estimate as to when the `yargs` dep will be updated?

**Comment by Rob--W** [comment]
Not soon, unfortunately. I ran in multiple issues when I tried to upgrade and have other higher pressing tasks that I need to work on.

**Comment by stephenmathieson** [comment]
OK, fair enough.

Perhaps adding something to the README and/or https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/web-ext_command_reference would suffice for now?

**Comment by kumar303** [comment]
> https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/web-ext_command_reference

This page is editable.

**Comment by Fedcomp** [comment]
wow, middle of 2019 and still not fixed

**Comment by bella-strange** [comment]
Just ran into this as well.

**Comment by doronbehar** [comment]
Yea this is very annoying. It's a shame this issue doesn't get any attention. It feels as if the developers aren't even using the environmental variables credentials feature so that's why it doesn't bother them.
