### ISSUE TITLE
Make reload desktop notifications more concise

### ISSUE THREAD

**Issue by kumar303** [mozilla/web-ext#796]
### Is this a bug or feature request?

feature

### What is the current behavior?

* change into an extension source directory
* type `web-ext run`
* edit one of the source files to create a reload error. For example: delete one of the [required fields](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/name) from your manifest.

You will see a desktop notification telling you that the extension could not be reloaded because of an error: 
<img width="347" alt="web-ext-reload" src="https://cloud.githubusercontent.com/assets/55398/22801447/6f9dc3a8-eed2-11e6-8c09-7aab3057f33e.png">

### What is the expected or desired behavior?

It's hard to glance at this and know what just happened. Can we make it more concise? Here is a suggestion (but maybe there are other things we can do):

Change the body to "unknownError: error occurred while processing ...." In other words, remove "reload response error:" from the message because that's redundant. The title of the notification already tells you that an error occurred.

### Version information (for bug reports)

* **Firefox version**:
* **Your OS and version**:
* Paste the output of these commands:

````
node --version && npm --version && web-ext --version
````
v6.9.4
3.10.10
1.8.1

**Comment by saintsebastian** [comment]
this is indeed a pretty good first bug! I hope someone will pick it up soon as an introduction to web-ext

**Comment by kumar303** [comment]
@saintsebastian If you want to grab it, then feel free :) I only added the label since it is a small change but I do think we should make this change sooner rather than later.

**Comment by francesar** [comment]
@kumar303 Hi! If no one has taken this on yet, I'd love to take a stab at it. (with some guidance since this would be my first open source bug fix)

**Comment by saintsebastian** [comment]
@francesar Hey! I think I can point you to a couple of places to look into. Notifications are created by utility function [here](https://github.com/mozilla/web-ext/blob/master/src/util/desktop-notifier.js) and they are created [here](https://github.com/mozilla/web-ext/blob/master/src/cmd/run.js#L72). Let me know if I can help you with anything else and good luck!

**Comment by StandB** [comment]
Hey, I am new to open source, and I think I fixed this issue (I'm not actually sure if I did it correctly) Is it okay if I open a pull request?

**Comment by wagnerand** [comment]
@kumar303 would you mind mentoring this?

@StandB Absolutely! Please open a PR.
