### ISSUE TITLE
Allow --start-url to accept a space separated list of URLs

### ISSUE THREAD

**Issue by kumar303** [mozilla/web-ext#797]
### Is this a bug or feature request?

feature

### What is the current behavior?

If you want to start Firefox with multiple tabs you can do so like this:
````
web-ext run --start-url mozilla.org --start-url addons.mozilla.org
````
but you can only put one URL in the environment variable:
````
WEB_EXT_START_URL=mozilla.org web-ext run
````

### What is the expected or desired behavior?

You should be able to specify multiple URLs in the environment variable too, like this:
````
WEB_EXT_START_URL="mozilla.org addons.mozilla.org" web-ext run
````
I think the only change needed for this is to switch [the --start-url type](https://github.com/mozilla/web-ext/blob/d37cb13039e2667aa3bf01c86b357a6c6d80993f/src/program.js#L366) from `string` to `array` like [the --ignore-files option](https://github.com/mozilla/web-ext/blob/d37cb13039e2667aa3bf01c86b357a6c6d80993f/src/program.js#L266).

Let's try to make it backwards compatible with multiple `--start-url` options if we can.

**Comment by wagnerand** [comment]
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started.

The mentor for this bug is: @kumar303

**Comment by gilbertginsberg** [comment]
Hi @kumar303, Steven Gilbert here. Thank you for mentoring. Might I work on this issue? This would be my first patch.

**Comment by kumar303** [comment]
Hi @gilbertginsberg, definitely! Here is some info about how to get started: https://github.com/mozilla/web-ext/blob/master/CONTRIBUTING.md Let me know if you have questions.

**Comment by gilbertginsberg** [comment]
@kumar303: I switched the [--start-url type](https://github.com/mozilla/web-ext/blob/d37cb13039e2667aa3bf01c86b357a6c6d80993f/src/program.js#L366) from `string` to `array` as you suggested, but that didn’t seem to bring about the desired behavior.  
 
For context, I created a `borderify.js` WebExtension from [Your first WebExtension](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Your_first_WebExtension) to test on. And I can confirm that the following commands behaved correctly with both `type: 'string'` and `type: 'array'`. Meaning, they both opened successfully in Firefox:

`web-ext run --start-url mozilla.org --start-url addons.mozilla.org`
`WEB_EXT_START_URL=mozilla.org web-ext run`

But the `WEB_EXT_START_URL="mozilla.org addons.mozilla.org" web-ext run` command did not behave correctly, with either `type: 'string'` or `type: 'array'`. In both cases, Firefox opened like so:

![screen shot 2017-02-26 at 9 56 33 pm](https://cloud.githubusercontent.com/assets/4500679/23378564/94ccf738-fd01-11e6-9cfa-581686c8ebd0.png)

When I made the change from `string` to `array` I made sure to test the commands after the re-build completed. 

I started going through the [yarg docs](http://yargs.js.org/docs/) for possible inspiration. Would I be going in the right direction there? Or is there another area of the codebase you might be able to point me to so I can investigate? Many thanks.

**Comment by kumar303** [comment]
Yep, you're going in the right direction. Also take a look at how [we define the --ignore-files option](https://github.com/mozilla/web-ext/blob/d37cb13039e2667aa3bf01c86b357a6c6d80993f/src/program.js#L266) and also how it [gets used](https://github.com/mozilla/web-ext/blob/d37cb13039e2667aa3bf01c86b357a6c6d80993f/src/cmd/run.js#L181).

**Comment by gilbertginsberg** [comment]
Thanks @kumar303. 

So in  `cmd/program.js` I've defined the [--start-url type](https://github.com/mozilla/web-ext/blob/d37cb13039e2667aa3bf01c86b357a6c6d80993f/src/program.js#L366) from `string` to `array`.

And in `cmd/run.js`, I mirrored `--ignore-files` and defined `startUrl` with `Array<string>` [here](https://github.com/mozilla/web-ext/blob/master/src/cmd/run.js#L180) and [here](https://github.com/mozilla/web-ext/blob/master/src/cmd/run.js#L300), and `?Array<string>` [here](https://github.com/mozilla/web-ext/blob/master/src/cmd/run.js#L311).

And in `test.run.js` I [replaced  `'www.example.com'` with `['www.example.com']`](https://github.com/mozilla/web-ext/blob/master/tests/unit/test-cmd/test.run.js#L135). 

The tests passed, but I still didn't get the expected behavior of `WEB_EXT_START_URL="mozilla.org addons.mozilla.org" web-ext run`. 

Also I've played with this [code block](https://github.com/mozilla/web-ext/blob/master/src/cmd/run.js#L367). Might that be a worthwhile place to continue investigating? 

Going forward I'll keep trying to better understand the codebase and yargs and trial-and-erroring. Hopefully with less errroring :P.  And I need to spend some time getting better acquainted with Flow's syntax, which is a bit foreign to me. I'll report back if any questions.

**Comment by kumar303** [comment]
The goal is definitely to get each URL sent as a [separate arg](https://github.com/mozilla/web-ext/blob/master/src/cmd/run.js#L370) to Firefox, like `--url mozilla.org --url addons.mozilla.org`. I'm not sure what will need adjusting to make that happen but I'd suggest using `log.debug()` statements ([example](https://github.com/mozilla/web-ext/blob/master/src/cmd/run.js#L66)) to figure out what's happening in your patch. If you run `web-ext --verbose` then you will see the debug statements.

**Comment by gilbertginsberg** [comment]
Roger that @kumar303. I'll continue the investigation.

**Comment by gilbertginsberg** [comment]
@kumar303: I've submitted PR #836 for this issue. Thank you for bringing to my attention `log.debug` and `web-ext --verbose`. They were a big help in getting me unstuck.

**Comment by kumar303** [comment]
> I think the only change needed for this is to switch the --start-url type from string to array like the --ignore-files option.

d'oh, this is not working. It looks like we're hitting a bug in yargs: https://github.com/yargs/yargs/issues/821

@gilbertginsberg let's see if we can get a fix in yargs before doing a workaround.

Because of the bug, `--ignore-files` is also broken: https://github.com/mozilla/web-ext/issues/854

**Comment by gilbertginsberg** [comment]
Ah, okay okay. Sounds good, @kumar303.

**Comment by caitmuenster** [comment]
Hey @gilbertginsberg! How's it going with this bug?

**Comment by gilbertginsberg** [comment]
Hi @caitmuenster: I submitted a PR for a workaround, but that wasn't ideal. Instead it'd be best to fix the underlying bug in yargs [yargs/yargs#821](https://github.com/yargs/yargs/issues/821), which appears is not yet resolved. So I'm keeping an eye out on that fix before proceeding.

**Comment by caitmuenster** [comment]
Sounds good. Thanks for the update!

**Comment by muffinresearch** [comment]
@kumar303 Reading the context and the upstream issue I don't think it will be possible to fix yargs to take an array via an env var since env vars can only be strings - most shells don't seem to support exporting arrays.

**Comment by wagnerand** [comment]
@kumar303 Given @muffinresearch's comment Is this issue still blocked by upstream?

**Comment by kumar303** [comment]
@muffinresearch I think it's possible because you can define the env var as a string with a space in it like this:

```
WEB_EXT_START_URL="mozilla.org addons.mozilla.org" web-ext run
```

However, since this is blocked upstream it is no longer a good first bug. I removed the labels.
