### ISSUE TITLE
Throw an error if a config file defines an option with the wrong type

### ISSUE THREAD

**Issue by kumar303** [mozilla/web-ext#798]
Every option is defined with a type. Each possible type is [documented here](http://yargs.js.org/docs/#methods-optionkey-opt). If a config file defines a value in the wrong type, let's throw an error. Otherwise, confusing and unpredictable things might happen when the command gets executed.

This is part of implementing https://github.com/mozilla/web-ext/issues/176

**Comment by shubheksha** [comment]
Can't we club this along with #814?
From what I understand, we'd need two arrays, one consisting of all valid options and another one with valid types and check each options against both these arrays.

**Comment by shubheksha** [comment]
I'm not sure if yargs option have a direct correspondence with JS data types. In the config, the user isn't asked to specify a type explicitly, so the validation needs to be done using JS data types itself. Am I missing something here?
