### ISSUE TITLE
Add --no-default-ignore-files option

### ISSUE THREAD

**Issue by kumar303** [mozilla/web-ext#799]
### Is this a bug or feature request?

feature

### What is the current behavior?

After https://github.com/mozilla/web-ext/issues/131 you can use the [--ignore-files](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/web-ext_command_reference?document_saved=true#--ignore-files_-i) option. However, there is no way to reset the default ignore rules. 

### What is the expected or desired behavior?

You should be able to clear all the defaults and specify your own rules. You may want to do this, for example, if your extension source should contain `.zip` files.

It would look something like this:
````
web-ext --no-default-ignore-files --ignore-files "**/node_modules" build
````

**Comment by ccarruitero** [comment]
I'll work on this

**Comment by kumar303** [comment]
@ccarruitero great, thanks! Let us know if you have questions.

**Comment by Rob--W** [comment]
FIxed by #846.

**Comment by bmwalters** [comment]
@Rob--W I ran into this issue recently. My extension has a `node_modules/` folder. addons-linter [allows this](https://github.com/mozilla/addons-linter/issues/1288) but `web-ext lint` fails validation on any `executeScript` calls that reference a file within this folder:

```
Code                       Message                            Description                              File             Line   Column
CONTENT_SCRIPT_NOT_FOUND   Content script file could not be   Content script file could not be found   popup/index.js   7      15    
                           found.
```

I can't find any combination of options that allows me to work around this.

**Comment by rpl** [comment]
@bmwalters have you tried with the `-i` cli option and negated pattern?
e.g. something like `web-ext lint -i !build/node_modules/packagename/dir/**`
