### ISSUE TITLE
Use web-ext to run an extension in Google Chrome

### ISSUE THREAD

**Issue by kumar303** [mozilla/web-ext#809]
### Is this a bug or feature request?

feature

### What is the current behavior?

You can use [web-ext run](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/web-ext_command_reference#web-ext_run) to launch an extension for development in Firefox. It creates a temporary profile and will automatically reload the extension when you change the source.

### What is the expected or desired behavior?

It would be great to use `web-ext` to launch the extension like this in Chrome. I'm not sure if we can support auto-reloading or temporary profiles but at the very least we could launch [chromium --load-extension=/path/to/source-dir](http://stackoverflow.com/questions/20782557/load-unpacked-chrome-extension-programatically) which does a similar temporary installation for development.

**Comment by kumar303** [comment]
If Chrome doesn't have remote debugger support for auto-reloading, here is one idea for an epic, horrendous hack:
* create a helper Chrome Extension that can listen to commands from `web-ext`
* install the helper extension along with the extension under test
* whenever the source changes, `web-ext` would tell the Chrome Extension to automatically click the 'reload' button on the `chrome://extensions/` page (Extensions may not have access to run content scripts on this page though)

**Comment by AgrimPrasad** [comment]
Hacky idea for auto-reloading which was previously implemented for Chrome: https://60devs.com/hot-reloading-for-chrome-extensions.html

**Comment by kumar303** [comment]
Wow, that's cool. Thanks for the link. I guess the downside is that one would have to modify their extension source to use this approach.

**Comment by josephfrazier** [comment]
For [OctoLinker](https://github.com/OctoLinker/browser-extension), we use [chrome-launch](https://github.com/hughsk/chrome-launch) to start an isolated instance of Chrome with the extension loaded. Here's the code, if you're interested in adapting it: https://github.com/OctoLinker/browser-extension/blob/08bd7aebe3fc43c96690c2ca0dab14398810c424/scripts/chrome-launch.js

**Comment by lutostag** [comment]
Chrome (well a symlink to chromium on my rig) does reload the extension when I run with the following...
`chrome --temp-profile --password-store=basic --load-extension=<dir> about:blank`
Have used it [for active debugging here](https://github.com/lutostag/webextension-formsave/blob/master/formsave/manifest.json#L50).

version: `Chromium 58.0.3029.110 Built on Ubuntu , running on Ubuntu 17.04`

**Comment by DamienCassou** [comment]
@josephfrazier Thanks for the link. Apparently, chrome-launch does not support Chromium, only Chrome.

**Comment by DamienCassou** [comment]
Also, `chrome-launch` passes a new directory as default value for `--user-data-dir` which is not compatible with native messages (they require a manifest file per native application in `<user-data-dir>/NativeMessagingHost`.

**Comment by Miserlou** [comment]
Status of this feature? Would be super handy!

**Comment by kumar303** [comment]
There are some changes in https://github.com/mozilla/web-ext/pull/868 that will make it easier to start working on Chrome support.

**Comment by heikir** [comment]
@kumar303 Any updates on this feature request? Is it currently high or low priority?

**Comment by kumar303** [comment]
@rpl would probably be able to say! I think we are close.

**Comment by rpl** [comment]
Fixed by #1392 \o/

**Comment by rpl** [comment]
This is already merged on master (and so if you want to try it before it is released on npm, you can built web-ext from the master branch), and it will soon be part of the upcoming web-ext 3.2.0 release.
