### ISSUE TITLE
Validate all command option values in config files

### ISSUE THREAD

**Issue by kumar303** [mozilla/web-ext#814]
This is a stepping stone towards https://github.com/mozilla/web-ext/issues/176

If the developer runs a command like:

````
web-ext build
````

but their config file has an invalid option for an unrelated command, like:
````js
{
  sign: {
    apiSekret: 'this-config-key-has-a-typo', 
  },
}
````
then it should still raise an 'invalid config option' error even though the developer did not execute the `sign` command.

**Comment by shubheksha** [comment]
This should be taken care of in #842

**Comment by saintsebastian** [comment]
@kumar303 i think this issue is solved as @shubheksha has mentioned

**Comment by kumar303** [comment]
Ah, indeed it is. Thanks.
