### ISSUE TITLE
Remove temporary profile path from `web-ext run` logging

### ISSUE THREAD

**Issue by kumar303** [mozilla/web-ext#820]
### Is this a bug or feature request?

feature

### What is the current behavior?

When you type `web-ext run` you see the path to your temporary profile logged, like this:

````
Running web extension from /Users/kumar/dev/bookmarker-ext/extension
Running Firefox with profile at /var/folders/8g/npvxp6j96sn_07b1f6b3h0qm0000gn/T/1f42722d-dd94-43c1-acdf-063e2039f80f
````

### What is the expected or desired behavior?

It should not show the temporary path to the Firefox profile since that information is not useful except when debugging. That entire line can be hidden so that it only shows this:
````
Running web extension from /Users/kumar/dev/bookmarker-ext/extension
````
However, when running `web-ext --verbose run` the temporary path to the profile should be logged.

**Comment by gilbertginsberg** [comment]
Hey @kumar303: I'd like to take this one on.
