### ISSUE TITLE
`web-ext run` does not install extension if another Firefox is open

### ISSUE THREAD

**Issue by kumar303** [mozilla/web-ext#821]
### Is this a bug or feature request?

bug

### What is the current behavior?

This is how I reproduced it. 

* I had `web-ext run -f firefoxdeveloperedition` going with one extension
* I fired off `web-ext run -f nightly` inside the [window-manipulator](https://github.com/mdn/webextensions-examples/tree/master/window-manipulator) example.
* Nightly started up but the extension was not installed and there were no obvious errors 

### What is the expected or desired behavior?

The second extension should have been installed or there should have been an error. When I stopped the first instance of `web-ext run` and retried the second one, the extension was installed as expected.

### Version information (for bug reports)

* **Firefox version**: 53.0a2 (2017-02-24) (64-bit) and 54.0a1 (2017-02-26) (64-bit)
* **Your OS and version**: Mac OS X Sierra
* Paste the output of these commands:

````
node --version && npm --version && web-ext --version
````

v6.9.4
3.10.10
master-c08360dafb3e1f3df8454e359992bef6f2171e10 (1.8.1)

Verbose log: 
[web-ext-run-window-manipulator.txt](https://github.com/mozilla/web-ext/files/802733/web-ext-run-window-manipulator.txt)

It looks like maybe there is an issue with retrying the connection to the remote debugger.

**Comment by ccarruitero** [comment]
Hi,

I was looking into this issue.
I was able to replicate the bug and I found that the second addon is installed but in the first firefox instance that is running.

Sadly, I couldn't figure out how solve the problem.

Looking into [addon's installation code](https://github.com/mozilla/web-ext/blob/master/src/firefox/remote.js#L90). I think that we are passing a wrong addonActor [here](https://github.com/mozilla/web-ext/blob/master/src/firefox/remote.js#L110), but I'm not sure how improve [this query](https://github.com/mozilla/web-ext/blob/master/src/firefox/remote.js#L94)

Another thing that I noticed is that, in logs, the debugger server for the second instance is started after the addon is installed.
So maybe we could need expose if the debugger server is ready in the [fx-runner](https://github.com/mozilla-jetpack/node-fx-runner) and wait for that [here](https://github.com/mozilla/web-ext/blob/master/src/firefox/index.js#L138) too.

I will continue in this later, but if you have any advice will be helpful.

**Comment by kumar303** [comment]
Hi @ccarruitero , thanks for digging into this! I would suggest also using `--verbose` output to see which port each instance is connecting to. If the second instance is installing the add-on before the debugger server has started, maybe it's connecting on the wrong port -- that of the first instance?

In regards to waiting for the debugger server, we already do that [here](https://github.com/mozilla/web-ext/blob/542f9ce8f556d14a43d237c13ac83c1961fff732/src/firefox/index.js#L136) but that wait strategy is only to see if it can connect to the port. Maybe it's the wrong port?

**Comment by ccarruitero** [comment]
@kumar303 thanks for your thoughts.

Yeah, It's connecting to the first instance port.
I was thinking that is because the other debugger is not ready. But maybe could be just that not are passing the correct port after run the second instance. I'm going to check that.

**Comment by ccarruitero** [comment]
Giving the port when initiate the debugger client seems to fix the error :tada: .

I opened a [PR](https://github.com/mozilla/web-ext/pull/923), but I think that is not ready.
I think the way how is [getting the port](https://github.com/mozilla/web-ext/pull/923/files#diff-5535d044b83cd9bd58881c2cd9ff0defR300) is a little hacky, so maybe can figure something better. Aside needs to add a test case.

**Comment by kumar303** [comment]
Good catch, I see what's happening now. I added some comments to the PR.

**Comment by kumar303** [comment]
@ccarruitero thanks for all your work on this. I just pushed out a new version with your patch: https://github.com/mozilla/web-ext/releases/tag/1.9.1
