### ISSUE TITLE
web-ext lint should not exit the process when shouldExitProgram is set to false

### ISSUE THREAD

**Issue by rpl** [mozilla/web-ext#823]
### Is this a bug or feature request?

bug

### What is the current behavior?

When web-ext is used as a library to be integrated into another tool (e.g. gulp, grunt, webpack etc.)
it should not exit the nodejs application that integrates it, which should be achievable using the [`shouldExitProgram`](https://github.com/mozilla/web-ext/blob/4be7a6a4f7ca35c8c31227c5e3778d61a7e5291b/src/program.js#L121-L122) property of the `Program` class.

Unfortunately, when the `web-ext lint` command is executed, web-ext currently passes [`runAsBinary: true`](https://github.com/mozilla/web-ext/blob/4be7a6a4f7ca35c8c31227c5e3778d61a7e5291b/src/cmd/lint.js#L89) to the created `Linter` instance, which is going to make the command to exit the nodejs process once the linting scan and the linting report has been completed.

### What is the expected or desired behavior?

We should set `runAsBinary` to `false` when `shouldExitProgram` is set to `false`, so that the `web-ext lint` command will have the same behavior of the other commands when integrated into another nodejs application.

**Comment by kumar303** [comment]
Something that also bothers me about this code (which is unrelated to the bug) is calling `this.yargs.exitProcess(this.shouldExitProgram)` from `execute()`. We should call it [from the constructor](https://github.com/mozilla/web-ext/blob/ec8d3ef7dcbf2c1d5459e5fc58a07f6cd1d33770/src/program.js#L57-L61) instead.

**Comment by eviljeff** [comment]
@kumar303 is this a good first bug?  If so can you provide a few more details?

**Comment by wagnerand** [comment]
@kumar303 and @rpl think this is a good first bug.

If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started.

**Comment by kumar303** [comment]
There are details in the description about the context of the bug, where to find the sources, and how to fix the issue. For any contributor who wants to work on this, just let us know if you need further clarifications or if you need help getting started.

**Comment by ccarruitero** [comment]
Since seems that no one is working on this, I will work on this issue.
