### ISSUE TITLE
Option `--ignore-files` doesn't seem to affect `web-ext sign`

### ISSUE THREAD

**Issue by felixgirault** [mozilla/web-ext#843]
Hi,

### Is this a bug or feature request?

A bug.

### What is the current behavior?

I'm trying to package and sign an extension, which is built with webpack.
I've got source directories in the tree that I don't want to include into the packaged extension.

With the `web-ext build` command, I'm using the global option `--ignore-file` to ignore those source directories, and it works as expected (i.e. `web-ext build --ignore-files ./src`).
But with `web-ext sign`, this option doesn't seem to be taken into account.

This makes the validation step fail, because it tries to validate source files written in ES6, and it keeps finding syntax errors in them.

### What is the expected or desired behavior?

I would expect `web-ext sign` to understand the `--ignore-files` options, as it is a global one.

### Version information (for bug reports)

```
node: v6.7.0
npm: 3.10.3
web-ext: 1.8.1
```

### Notes

If I understand the code correctly, it seems that in the `sign` command, the `--ignore-files` is not passed to the `build` sub-command (https://github.com/mozilla/web-ext/blob/master/src/cmd/sign.js#L69).

I'll be glad to contribute fixing this, but I wanted to check first if this was a documentation issue or one in the code.

**Comment by kumar303** [comment]
Whoa, good catch!

**Comment by Asenar** [comment]
thanks you !

it seems this was not covered by the tests unit :/

**Comment by carlin-q-scott** [comment]
I'm able to reproduce this issue with v3.0.0 of web-ext. Was there a regression?

**Comment by Rob--W** [comment]
@carlin-q-scott Could you file a new issue with the exact reproduction steps?
