### ISSUE TITLE
Change name to webext

### ISSUE THREAD

**Issue by bfred-it** [mozilla/web-ext#850]
It's a bit shorter, I can give you the name: https://www.npmjs.com/package/webext

**Comment by kumar303** [comment]
Thanks but I think `web-ext` is fine. We'd have to update too many things to change it. I added the dash originally because `webext` was taken but the maintainer later made the package point to `web-ext` so at least that will prevent any confusion in case people land on `webext`.

**Comment by bfred-it** [comment]
Yep, I got the webext name from the original maintainer and _redirected_ it to yours for that reason. :)
