### ISSUE TITLE
Install/run a web extension using custom preferences

### ISSUE THREAD

**Issue by kumar303** [mozilla/web-ext#88]
A run/install command was added in https://github.com/mozilla/web-ext/issues/6 but it only launches Firefox with default preferences. Allow the caller to specify custom preferences. This would be a more lightweight way of customizing Firefox as opposed to creating a custom profile (https://github.com/mozilla/web-ext/issues/69).

**Comment by kumar303** [comment]
I think this should be a pretty easy change actually, so I'm putting back the good first bug label. It only needs:
* A new repeatable option like `--pref="key:value" --pref="key2:value2" ...`
* An update to [firefox.configureProfile()](https://github.com/mozilla/web-ext/blob/master/src/firefox/index.js#L93) to add each preference
* Tests
I am happy to mentor this.

**Comment by kumar303** [comment]
Here is a good use case: Let's say you want to test your extension in 30 different locales. Instead of making 30 profiles, you could just run it like `web-ext --pref=general.useragent.locale:fr-FR` for each locale.

**Comment by wagnerand** [comment]
Please refer to https://wiki.mozilla.org/Add-ons/Contribute/AMO/Code if this is your first contribution.

If you want to work on this issue and need more information on how or where to fix it, please comment here and we will be happy to provide more details.

Mentor: @kumar303

**Comment by davidamidon** [comment]
Hello, I would like to try my hand at this fix. Although I will certainly require direction, I am very eager to participate.

**Comment by kumar303** [comment]
Hi @davidamidon ! I'm here to help, let me know if you have any questions about how to get started.

**Comment by davidamidon** [comment]
@kumar303 Thank you! Should I ask in here or is there a better place? I've got everything installed I think. For this fix the code would go in /src/firefox/index.js?

**Comment by kumar303** [comment]
Yes, this is a good place to ask questions. The locations are as follows:

* Custom preferences are applied to profiles [here](https://github.com/mozilla/web-ext/blob/0d1b82454ec5d3a6a58ddeb3e4c66432e6fbad77/src/firefox/index.js#L216).
* New command line options are defined [here](https://github.com/mozilla/web-ext/blob/0d1b82454ec5d3a6a58ddeb3e4c66432e6fbad77/src/program.js#L223).
* The configuration of profiles is [tested here](https://github.com/mozilla/web-ext/blob/0d1b82454ec5d3a6a58ddeb3e4c66432e6fbad77/tests/unit/test-firefox/test.firefox.js#L289).

**Comment by davidamidon** [comment]
Ok, I've been looking this over but I'm not sure how to start it. From what I understand;

- In  web-ext/src/firefox/preferences.js the below is used to hard code the contained preferences
`const prefsCommon: FirefoxPreferences = {`

- They are then being exported over to  web-ext/src/firefox/index.js 
-  web-ext/src/program.js  is the list of what we want as custom preferences?

You stated 

> A new repeatable option like --pref="key:value" --pref="key2:value2" ...

So some form of a loop to take in 1 or more custom preferences.

Hopefully I am on the correct path so far.

**Comment by kumar303** [comment]
Hi. I wouldn't worry about making a repeating option yet, that can be added later. An easy first step is to accept this new option:

    web-ext run --pref="key:value"

You can use `log.info(...)` in the [run()](https://github.com/mozilla/web-ext/blob/master/src/cmd/run.js#L160) function to make sure you configured the new option correctly.

After that, take a look at [configureProfile()](https://github.com/mozilla/web-ext/blob/master/src/firefox/index.js#L205). This feature would set a new preference in the profile probably within this function. However, there is no need to modify `src/firefox/preferences.js` because that's a separate feature. The code for adding a custom preference needs to call `profile.setPreference(customPref, customValue)`.

The `configureProfile()` function is called by [copyProfile()](https://github.com/mozilla/web-ext/blob/master/src/firefox/index.js#L290) and [createProfile()](https://github.com/mozilla/web-ext/blob/master/src/firefox/index.js#L241). The run command calls either of these in [getProfile()](https://github.com/mozilla/web-ext/blob/master/src/cmd/run.js#L198).

**Comment by saintsebastian** [comment]
@kumar303 if there is not work currently done on that issue, I'd like to try a hand

**Comment by kumar303** [comment]
@saintsebastian I haven't seen a pull request for this yet (unless I missed it?) so, yeah, feel free to work on a patch for this. Thanks!

**Comment by kumar303** [comment]
@saintsebastian this is a great feature, thanks for all your work on it!

We just released it in [1.7.0](https://github.com/mozilla/web-ext/releases/tag/1.7.0) so the next step is to add it to the [run command documentation](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/web-ext_command_reference#web-ext_run). Could you try to add it? I can help if you have questions and can also review the docs after you add them.

**Comment by saintsebastian** [comment]
@kumar303 thank you, it was fun working on it.
Here is the draft I have for this occasion. I think that’s pretty much everything a given user need to know, but we can also include information on where to find those preferences in the first place (about:config) or that some of them cannot be changed.

`--pref`
Repeated option that allows to customise certain Firefox profile settings without creating of modifying a profile. Accepts arguments in a form of `--pref ‘general.useragent.locale=fr-FR’`. Can be used in combination with specified Firefox profile.

**Comment by kumar303** [comment]
That looks good to me! Just a few small nits:
* We use international English spelling elsewhere in the docs so customise should be customize
* "creating of modifying..." (typo) -> "creating or modifying..."
* The example should be `--pref general.useragent.locale=fr-FR` without the quotes because Luca and I have been testing this and it works fine without quotes (surprisingly).

Please sign into the MDN page via Github and make the edit. Let me know if you run into issues.

**Comment by saintsebastian** [comment]
@kumar303 I have a question - how to add numbered lines in a code block in editor?

**Comment by kumar303** [comment]
Thanks for the edit! It requires you to edit the source and add a new css class to the pre tag (which is annoying). I updated it for you. What you wrote was great but while I was in there I just made the tense and tone more consistent with how the other options are documented. 

I also mentioned the environment variable for the option which we do in all option docs. However, I was unsure how it works since this is the first option we have that can be specified multiple times. Could you look at this issue when you get a chance? https://github.com/mozilla/web-ext/issues/725

**Comment by kumar303** [comment]
This is documented now 🍶 https://developer.mozilla.org/en-US/Add-ons/WebExtensions/web-ext_command_reference?document_saved=true#--pref

**Comment by saintsebastian** [comment]
Sure, thank you for the edits!
