### ISSUE TITLE
lint command complains about not implemented features, but features are implemented and work

### ISSUE THREAD

**Issue by cadeyrn** [mozilla/web-ext#909]
### Is this a bug or feature request?

bug since web-ext 1.9.0.

### What is the current behavior?

After execution of web-ext lint there are three warnings for my add-on, see the attached screenshot.

<img width="1147" alt="bildschirmfoto 2017-04-18 um 22 03 30" src="https://cloud.githubusercontent.com/assets/1100614/25150638/e83c274c-2482-11e7-9c75-9710b81d01c2.png">

### What is the expected or desired behavior?

No warnings because all of these are supported in Firefox 52 and work without any problem. There were no warnings in web-ext 1.8.1. Here you can see the result of the same test with web-ext 1.8.1:

<img width="685" alt="bildschirmfoto 2017-04-18 um 22 01 58" src="https://cloud.githubusercontent.com/assets/1100614/25150588/c04fe52a-2482-11e7-9b75-60ecf333887e.png">

### Version information (for bug reports)

* **Firefox version**: Firefox 52.0.2
* **Your OS and version**: macOS 10.12.4

**Comment by andymckay** [comment]
We've added in the full schema from Firefox and are now trying to warn about unknown APIs. Looks like addons-linter might be missing those. Do you have a link to your add-on?

**Comment by andymckay** [comment]
cc @mstriemer

**Comment by cadeyrn** [comment]
The add-on is not yet uploaded to AMO, but you can find the repository here:
https://git.agenedia.com/firefox-add-ons/bookmarks-organizer/tree/master

**Comment by andymckay** [comment]
Thanks, those look like legitimate uses to me. Fortunately these are just warnings and shouldn't block anything.

**Comment by andymckay** [comment]
https://github.com/mozilla/addons-linter/issues/1209

**Comment by kumar303** [comment]
Yeah, it seems like you shouldn't see warnings about these APIs if you plan to target Firefox 52.

@cadeyrn are you specifying Firefox 52 as `strict_min_version` in your [manifest.json](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/applications)?

**Comment by cadeyrn** [comment]
Yes, I have "strict_min_version": "52.0" in my manifest.json.

**Comment by mstriemer** [comment]
This is fixed by mozilla/addons-linter#1209 as Andy linked to. There was a problem with the omnibox schemas that gets fixed there. I tested this extension against that branch on addons-linter and it passes without any warnings.

This will be fixed in the next web-ext release so I'm going to close this since it's being tracked on addons-linter.
