### ISSUE TITLE
Add contribution docs

### ISSUE THREAD

**Issue by kumar303** [mozilla/web-ext#91]
Let's move the [development docs](https://github.com/mozilla/web-ext#development-of-web-ext) to a standard `CONTRIBUTING.md` file so that it shows up before someone submits a pull request.

**Comment by atiqueahmedziad** [comment]
Hi Kumar, 
Would `CONTRIBUTING.md` file contain all the writings below the #Development of web-ext ?

**Comment by kumar303** [comment]
Yes, I think we can just move the current development section to CONTRIBUTING.md and provide a link to it in the main readme.
