### ISSUE TITLE
Use linter with Firefox schema based manifest validation

### ISSUE THREAD

**Issue by mstriemer** [mozilla/web-ext#930]
addons-linter now has manifest validation based on the Firefox schemas. There were some bug fixes after it was released so we should update web-ext to use this new build.

@kumar303 I didn't see anything about making a new release in the README. Is this managed by CI so we just need to update the package.json and make a new tag?

**Comment by mstriemer** [comment]
This is from https://bugzilla.mozilla.org/show_bug.cgi?id=1358523.

**Comment by rpl** [comment]
@mstriemer Yes, the release to npm is managed by the CI when a new release tag.

The description of the procedure that web-ext follows to release a new version is in the CONTRIBUTING.md file: https://github.com/mozilla/web-ext/blob/master/CONTRIBUTING.md#creating-a-release

**Comment by kumar303** [comment]
It looks like we got the update from https://github.com/mozilla/web-ext/pull/922 -- can this issue be closed?

The patch in https://github.com/mozilla/web-ext/pull/923 looks like it's about to land so after that I can create a new web-ext release for you.

**Comment by mstriemer** [comment]
Yeah, the linter update is merged in now. I'll close this and keep an eye out for the new web-ext release.
