### ISSUE TITLE
Can't send Msg from Background to Content script using web-ext

### ISSUE THREAD

**Issue by rappazf** [mozilla/web-ext#938]
### Is this a feature request or a bug?
bug

### What is the current behavior?
I made a test extension that use a browser_action button to send a msg from background.js to content.js

1. I load the extension with <code>web-ext --verbose --firefox="C:\Program Files\Nightly\firefox.exe" run</code>
2. I navigate to a web page
3. I click on the button test of the extension (no icone ... don't know why)

The console gives the error
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.

### What is the expected or desired behavior?
If I pack the test extension with <code>web-ext build</code>, and I drag the zip archive on the add_on page, the message is sent correctly in the content script

### Version information (for bug reports)

* **Firefox version**:
55.0a1 (2017-05-04) (64-bit)
* **Your OS and version**:
Windows 10 E (1511)
* Paste the output of these commands:

````
node --version 
6.10.2
npm --version
3.10.10
web-ext --version
1.9.1
````
[test-0.0.1.zip](https://github.com/mozilla/web-ext/files/978983/test-0.0.1.zip)
[log.txt](https://github.com/mozilla/web-ext/files/978984/log.txt)

**Comment by kumar303** [comment]
Hi. Thanks for the bug report and thanks for including logs and source.

This could indicate a Firefox issue or a timing issue with establishing the messaging:
````
[firefox/index.js][debug] Firefox stdout: console.error:
  Handler function threw an exception: TypeError: threadActor is null
Stack: _windowReady@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/actors/tab.js:1231:1
_changeTopLevelDocument/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/actors/tab.js:1169:7
exports.makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js:101:14
Line: 1231, column: 1
````
I haven't looked at the extension source yet but could you tell me if the *Could not establish connection* error also happens when you [install as a temporary add-on](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Temporary_Installation_in_Firefox) manually (i.e. without `web-ext`)?

**Comment by rappazf** [comment]
Hi 
Same error if I load the addon via the temporary addon function  in the about:debugging page in Nightly, or if I run <code>web-ext run</code> which start FF 53.02: Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.
François

**Comment by kumar303** [comment]
Ah, ok, this means it's a bug in Firefox itself (perhaps something that has broken in Nightly). Can you file a bug here? https://bugzilla.mozilla.org/enter_bug.cgi?product=Toolkit&component=WebExtensions%3A%20General

It would be most helpful to add:
- The exact steps to reproduce it starting with installing it as a temporary add-on from the `about:debugging` page (on which Firefox version?)
- A confirmation that the same steps do *not* reproduce the bug on Firefox 53
- The source of the add-on that triggers the error (same one you attached here)
- If you can, include some logging messages from the [Browser Console](https://developer.mozilla.org/en-US/docs/Tools/Browser_Console), not from `web-ext`

**Comment by rappazf** [comment]
As I said in my initial message: the addon works when I install it as a zip archive dragged on the addon page of Nigthly... So it has something to do with web-ext, has it ?

**Comment by kumar303** [comment]
> Same error if I load the addon via the temporary addon function in the about:debugging page in Nightly, and navigate to a new web page.

I interpreted this to mean you can also reproduce the bug when you install the add-on temporarily from `about:debugging`, i.e. without using `web-ext`. Did I misunderstand?

**Comment by rappazf** [comment]
That's correct.  the only way I have it working is when I zip it and drag it on the add-on page. Why don't you try it yourself ?

**Comment by kumar303** [comment]
> That's correct.

Okay, then this is a Firefox bug, not a `web-ext` bug. It would be really helpful if you can re-file it: https://bugzilla.mozilla.org/enter_bug.cgi?product=Toolkit&component=WebExtensions%3A%20General Thanks again for taking the time to report it here.
