### ISSUE TITLE
Warnings for locale-dependent CSS using predefined messages

### ISSUE THREAD

**Issue by joelpurra** [mozilla/web-ext#951]
### Is this a feature request or a bug?

Bug

### What is the current behavior?

After following the [guidelines for locale-dependent CSS](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Internationalization#Locale-dependent_CSS) using predefined messages (documentation for [WebExtensions](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Internationalization#Predefined_messages), [Chrome](https://developer.chrome.com/extensions/i18n#overview-predefined), [Opera](https://dev.opera.com/extensions/internationalization/#predefined-messages)) for my [text to speech browser extension](https://joelpurra.com/projects/talkie/) I get warnings running `web-ext lint`.

```text
Code               Message        Description                                               File                          Line   Column
CSS_SYNTAX_ERROR   Unknown word   An error was found in the CSS file being processed as a   resources/style/options.css   64     5
                                  result further processing of that file is not possible
```

Reformatted:

```text
Code: CSS_SYNTAX_ERROR
Message: Unknown word
Description: An error was found in the CSS file being processed as a result further processing of that file is not possible
File: resources/style/options.css
Line: 64
Column: 5
```

Line 64 in `resources/style/options.css`:

```css
    margin-__MSG_@@bidi_start_edge__: 1em;
```

### What is the expected or desired behavior?

As the CSS is following guidelines, I expect to have no warnings. Similarly, I also expect no warnings when submitting the WebExtension to AMO.

### Version information (for bug reports)

node: v7.10.0 
npm: v4.2.0
web-ext: v1.9.1

**Comment by kumar303** [comment]
Hi, thanks for taking the time to file an issue. Since this is a bug in the linter library I re-filed it over there: https://github.com/mozilla/addons-linter/issues/1299
