### ISSUE TITLE
neeb question/bug-report - referring to #877

### ISSUE THREAD

**Issue by michapixel** [mozilla/web-ext#991]
i got a webextension which i currently just want to run in private so i delisted it (set to invisible)

### Is this a feature request or a bug?
bug i guess

### What is the current behavior?
web-ext sign --api-key=user:XXX --api-secret=XXX
```
Building web extension from C:\webserver\www\tests\FF_extensions\error_notifier\build
Validating add-on [...]
[...]
Validation results: https://addons.mozilla.org/en-US/developers/upload/XXXXXXXXXXX
Your add-on has been submitted for review. It passed validation but could not be automatically signed because this is a listed add-on.
FAIL
```
### What is the expected or desired behavior?
i get a signed xpi i guess, haven't done this before.

### Version information (for bug reports)
* **Firefox version**:
55.0b5 (32-Bit)
* **Your OS and version**:
Win 7

$ node --version && npm --version && web-ext --version
v6.9.4
3.10.10
1.10.0

**Comment by michapixel** [comment]
#877 because when i patch the mentioned formData
```
var formData = {
	        upload: this._fs.createReadStream(xpiPath)
	      };
```
to 
```
var formData = {
	        upload: this._fs.createReadStream(xpiPath),
	        channel: 'unlisted'
	      };
```
i only get timeouts ...

**Comment by kumar303** [comment]
Hi. I'm not sure what the bug is that you're reporting. Did you create an [unlisted extension](https://developer.mozilla.org/en-US/Add-ons/Distribution#Self-distributed_(unlisted)_versions)? If so, web-ext will work fine (as far as I know).

**Comment by michapixel** [comment]
Can't I use a previously listed extension?

Am 30.06.2017 6:16 nachm. schrieb "Kumar McMillan" <notifications@github.com
>:

Hi. I'm not sure what the bug is that you're reporting. Did you create
an unlisted
extension
<https://developer.mozilla.org/en-US/Add-ons/Distribution#Self-distributed_(unlisted)_versions>?
If so, web-ext will work fine (as far as I know).

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mozilla/web-ext/issues/991#issuecomment-312310532>, or mute
the thread

**Comment by kumar303** [comment]
> Can't I use a previously listed extension?

No, that is the open bug you linked to (https://github.com/mozilla/web-ext/issues/877). I'm going to close this one since it's a duplicate. Sorry that the workaround isn't helping you. I'm not sure if the `channel` parameter is still supported by the API or not.
