### ISSUE TITLE
Don't show the command in error messages

### ISSUE THREAD

**Issue by kumar303** [mozilla/web-ext#994]
### Is this a feature request or a bug?

feature

### What is the current behavior?

If you encounter an error, web-ext will always prefix the command to the error message, like:

```
$ web-ext run --target firefox-android -v --android-device FA6AX0301736

run: UsageError: Select one of the packages using --firefox-apk

```

### What is the expected or desired behavior?

I don't think we need to show the command. It can just be:

```
$ web-ext run --target firefox-android -v --android-device FA6AX0301736

UsageError: Select one of the packages using --firefox-apk

```

The command name is added as a [prefix here](https://github.com/mozilla/web-ext/blob/4a4641c561ab43d6293b1e00e1ad617e9134f4c3/src/program.js#L153). When removed, it should still be added for verbose mode, like:

```js
log.debug(`Command executed: ${cmd}`);
```

Originally, the command prefix was added to help in bug reports but really we always need a verbose log for debug reports anyway. Also, you can look at the command line to seed what command was run.

**Comment by wagnerand** [comment]
Mentor: @kumar303 

If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started.

**Comment by Divya063** [comment]
Is this issue still available?

**Comment by kumar303** [comment]
Hi @Divya063, yes it is.

**Comment by Divya063** [comment]
@kumar303 There is a pull request referring to this issue

**Comment by kumar303** [comment]
@Divya063 oh, wow, sorry about that but thanks for pointing out the pull request! 😬 I have merged it. Thank you for the patch, @tsl143
