### ISSUE TITLE
Fails on signing beta versions of listed add-ons.

### ISSUE THREAD

**Issue by Treora** [mozilla/web-ext#997]
### Is this a feature request or a bug?

Bug report

### What is the current behavior?

Running `web-ext sign` on a listed extension results in an error (which has already been discussed in #804). This even happens with beta versions:

> Your add-on has been submitted for review. It passed validation but could not be automatically signed because this is a listed add-on.

Despite the error, the extension is directly signed by AMO, and can be installed from the extension's 'development channel'.

### What is the expected or desired behavior?

When the extension to be signed is a beta version, the extension does not need review, so there is no reason to fail. I would expect the same behaviour as with an unlisted addon.

### Version information (for bug reports)

````
$ node --version && npm --version && web-ext --version
v6.7.0
3.10.3
1.10.0
````

**Comment by maciex** [comment]
```
$ node --version && npm --version && web-ext --version
v6.12.0
3.10.10
2.2.2
```

It seems I got this error too. The Add-on was uploaded, but the web-ext tool errored.

**Comment by maciex** [comment]
```
$ node --version && npm --version && web-ext --version
v6.12.0
3.10.10
2.2.2
```

It seems I got this error too. The Add-on was uploaded, but the web-ext tool errored.

**Comment by Rob--W** [comment]
Beta channels aren't supported any more by AMO.
